package itest

import (
	"hexchess-svc/model"
	"time"
)

var TestUser = []model.User{
	{
		ID:       1,
		Username: "user1",
		Country:  "us",
		Bio:      "",
		JoinedOn: TimeNow.Local(),
	},
	{
		ID:       2,
		Username: "user2",
		Country:  "us",
		Bio:      "",
		JoinedOn: TimeNow.Local(),
	},
}

var TestUserStats = []model.UserStats{
	{
		TotalWins:    17,
		TotalLosses:  14,
		AvgElo:       1025,
		HighestElo:   1050,
		TotalWinrate: 53,
		ModeStats: []model.ModeStats{
			{Mode: model.ModeCorrespondence7, Rank: 1, Wins: 2, Losses: 2, Winrate: 50, Elo: 1000, HighestElo: 1000},
			{Mode: model.ModeTimed3Plus2, Rank: 1, Wins: 5, Losses: 4, Winrate: 55, Elo: 1020, HighestElo: 1020},
			{Mode: model.ModeTimed15Plus10, Rank: 1, Wins: 4, Losses: 3, Winrate: 57, Elo: 1030, HighestElo: 1030},
			{Mode: model.ModeTimed1Plus0, Rank: 1, Wins: 6, Losses: 5, Winrate: 54, Elo: 1050, HighestElo: 1050},
		},
	},
}

var TestReplays = []model.FullReplay{
	{
		Replay: model.Replay{
			ID:          1,
			WhiteID:     1,
			BlackID:     2,
			Mode:        model.ModeCorrespondence7,
			Result:      model.WhiteWin,
			Cause:       model.Checkmate,
			WinEloDiff:  30,
			LoseEloDiff: -30,
			PlayedOn:    TimeNow.Local(),
			Rating:      1000,
			TurnCount:   42,
		},
		ReplayUsers: model.ReplayUsers{
			WhiteName:    "user1",
			BlackName:    "user2",
			WhiteCountry: "us",
			BlackCountry: "us",
			WhiteElo:     1000,
			BlackElo:     1000,
		},
		ReplayColorElos: model.ReplayColorElos{
			WhiteEloDiff: 30,
			BlackEloDiff: -30,
		},
	},
	{
		Replay: model.Replay{
			ID:          2,
			WhiteID:     2,
			BlackID:     3,
			Mode:        model.ModeCorrespondence7,
			Result:      model.BlackWin,
			Cause:       model.Checkmate,
			WinEloDiff:  30,
			LoseEloDiff: -30,
			PlayedOn:    (TimeNow.Add(time.Hour * 24)).Local(),
			Rating:      950,
			TurnCount:   36,
		},
		ReplayUsers: model.ReplayUsers{
			WhiteName:    "user2",
			BlackName:    "user3",
			WhiteCountry: "us",
			BlackCountry: "us",
			WhiteElo:     1000,
			BlackElo:     900,
		},
		ReplayColorElos: model.ReplayColorElos{
			WhiteEloDiff: -30,
			BlackEloDiff: 30,
		},
	},
	{
		Replay: model.Replay{
			ID:          3,
			WhiteID:     3,
			BlackID:     1,
			Mode:        model.ModeCorrespondence7,
			Result:      model.Draw,
			Cause:       model.Checkmate,
			WinEloDiff:  0,
			LoseEloDiff: 0,
			PlayedOn:    (TimeNow.Add(time.Hour * 24 * 2)).Local(),
			Rating:      950,
			TurnCount:   38,
		},
		ReplayUsers: model.ReplayUsers{
			WhiteName:    "user3",
			BlackName:    "user1",
			WhiteCountry: "us",
			BlackCountry: "us",
			WhiteElo:     900,
			BlackElo:     1000,
		},
		ReplayColorElos: model.ReplayColorElos{
			WhiteEloDiff: 0,
			BlackEloDiff: 0,
		},
	},
	{
		Replay: model.Replay{
			ID:          4,
			WhiteID:     1,
			BlackID:     0,
			Mode:        model.ModeCorrespondence7,
			Result:      model.WhiteWin,
			Cause:       model.Checkmate,
			WinEloDiff:  0,
			LoseEloDiff: 0,
			PlayedOn:    (TimeNow.Add(time.Hour * 24 * 3)).Local(),
			Rating:      1000,
			TurnCount:   40,
		},
		ReplayUsers: model.ReplayUsers{
			WhiteName:    "user1",
			BlackName:    "",
			WhiteCountry: "us",
			BlackCountry: "",
			WhiteElo:     1000,
			BlackElo:     1000,
		},
		ReplayColorElos: model.ReplayColorElos{
			WhiteEloDiff: 0,
			BlackEloDiff: 0,
		},
	},
	{
		Replay: model.Replay{
			ID:          5,
			WhiteID:     1,
			BlackID:     2,
			Mode:        model.ModeCorrespondence7,
			Result:      model.BlackWin,
			Cause:       model.Checkmate,
			WinEloDiff:  30,
			LoseEloDiff: -30,
			PlayedOn:    (TimeNow.Add(time.Hour * 24 * 4)).Local(),
			Rating:      1000,
			TurnCount:   34,
		},
		ReplayUsers: model.ReplayUsers{
			WhiteName:    "user1",
			BlackName:    "user2",
			WhiteCountry: "us",
			BlackCountry: "us",
			WhiteElo:     1000,
			BlackElo:     1000,
		},
		ReplayColorElos: model.ReplayColorElos{
			WhiteEloDiff: -30,
			BlackEloDiff: 30,
		},
	},
}

var TestChallenge = []model.Challenge{
	{
		ChallengerID:      1,
		ChallengerName:    "user1",
		ChallengerCountry: "us",
		ChallengerElo:     1020,
		ChallengeeID:      2,
		ChallengeeName:    "user2",
		ChallengeeCountry: "us",
		ChallengeeElo:     1000,
		Mode:              model.ModeTimed3Plus2,
		StartColor:        model.Random,
		MadeOn:            TimeNow.Local(),
		ExpiresOn:         TimeNow.Local().Add(time.Hour * 24 * 7),
	},
	{
		ChallengerID:      3,
		ChallengerName:    "user3",
		ChallengerCountry: "us",
		ChallengerElo:     900,
		ChallengeeID:      1,
		ChallengeeName:    "user1",
		ChallengeeCountry: "us",
		ChallengeeElo:     1000,
		Mode:              model.ModeCorrespondence1,
		StartColor:        model.Random,
		MadeOn:            TimeNow.Local(),
		ExpiresOn:         TimeNow.Local().Add(time.Hour * 24 * 7),
	},
	{
		ChallengerID:      5,
		ChallengerName:    "user5",
		ChallengerCountry: "us",
		ChallengerElo:     1500,
		ChallengeeID:      2,
		ChallengeeName:    "user2",
		ChallengeeCountry: "us",
		ChallengeeElo:     1000,
		Mode:              model.ModeCorrespondence1,
		StartColor:        model.Random,
		MadeOn:            TimeNow.Local(),
		ExpiresOn:         TimeNow.Local().Add(time.Hour * 24 * 7),
	},
	{
		ChallengerID:      5,
		ChallengerName:    "user5",
		ChallengerCountry: "us",
		ChallengerElo:     1500,
		ChallengeeID:      4,
		ChallengeeName:    "user4",
		ChallengeeCountry: "us",
		ChallengeeElo:     2000,
		Mode:              model.ModeCorrespondence1,
		StartColor:        model.Random,
		MadeOn:            TimeNow.Local(),
		ExpiresOn:         TimeNow.Local().Add(time.Hour * 24 * 7),
	},
}

var Tournaments = []model.Tournament{
	{
		ID:             1,
		TournamentKey:  Tournament0LobbyKey,
		Name:           "Test Tournament 0",
		Rounds:         2,
		MaxPlayerCount: 4,
		Countdown:      "5m1s",
		CreatedOn:      TimeNow,
		CreatedBy:      1,
		Status:         model.TournamentLobby,
		Ruleset:        model.TournamentKnockout,
		Mode:           model.ModeCorrespondence1,
	},
	{
		ID:             2,
		TournamentKey:  Tournament1LobbyFilledKey,
		Name:           "Test Tournament 1",
		Rounds:         1,
		MaxPlayerCount: 2,
		Countdown:      "5m2s",
		CreatedOn:      TimeNow,
		CreatedBy:      1,
		Mode:           model.ModeCorrespondence7,
	},
	{
		ID:             3,
		TournamentKey:  Tournament2ScheduledKnockoutKey,
		Name:           "Test Tournament 2",
		Rounds:         2,
		MaxPlayerCount: 4,
		Countdown:      "5m3s",
		CreatedOn:      TimeNow,
		CreatedBy:      1,
		Ruleset:        model.TournamentKnockout,
		Status:         model.TournamentScheduled,
		Mode:           model.ModeCorrespondence1,
	},
	{
		ID:             4,
		TournamentKey:  Tournament3ScheduledRoundRobinKey,
		Name:           "Test Tournament 3",
		Rounds:         4,
		MaxPlayerCount: -1,
		Countdown:      "10m0s",
		CreatedOn:      TimeNow,
		CreatedBy:      1,
		Ruleset:        model.TournamentRoundRobin,
		Status:         model.TournamentScheduled,
		Mode:           model.ModeCorrespondence1,
	},
	{
		ID:             5,
		TournamentKey:  Tournament4ScheduledSwissKey,
		Name:           "Test Tournament 4",
		Rounds:         3,
		MaxPlayerCount: -1,
		Countdown:      "11m0s",
		CreatedOn:      TimeNow,
		CreatedBy:      1,
		Ruleset:        model.TournamentSwiss,
		Status:         model.TournamentScheduled,
		Mode:           model.ModeCorrespondence1,
	},
	{
		ID:             6,
		TournamentKey:  Tournament5InProgressKnockoutKey,
		Name:           "Test Tournament 5",
		Rounds:         2,
		MaxPlayerCount: 4,
		Countdown:      "12m0s",
		CreatedOn:      TimeNow,
		CreatedBy:      1,
		Ruleset:        model.TournamentKnockout,
		Status:         model.TournamentInProgress,
		Mode:           model.ModeCorrespondence1,
	},
	{
		ID:             7,
		TournamentKey:  Tournament6InProgressRoundRobinKey,
		Name:           "Test Tournament 6",
		Rounds:         4,
		MaxPlayerCount: -1,
		Countdown:      "1h1m1s",
		CreatedOn:      TimeNow,
		CreatedBy:      1,
		Ruleset:        model.TournamentRoundRobin,
		Status:         model.TournamentInProgress,
		Mode:           model.ModeCorrespondence1,
	},
	{
		ID:             8,
		TournamentKey:  Tournament7InProgressSwissKey,
		Name:           "Test Tournament 7",
		Rounds:         3,
		MaxPlayerCount: -1,
		Countdown:      "1h2m2.002s",
		CreatedOn:      TimeNow,
		CreatedBy:      1,
		Ruleset:        model.TournamentSwiss,
		Status:         model.TournamentInProgress,
		Mode:           model.ModeCorrespondence1,
	},
	{
		ID:             9,
		TournamentKey:  Tournament8FinishedKey,
		Name:           "Test Tournament 8",
		Rounds:         1,
		MaxPlayerCount: -1,
		Countdown:      "5m0s",
		CreatedOn:      TimeNow,
		CreatedBy:      1,
		Status:         model.TournamentFinished,
		Ruleset:        model.TournamentSwiss,
		Mode:           model.ModeCorrespondence1,
	},
	{
		ID:             10,
		TournamentKey:  Tournament9InProgressUncompletedKey,
		Name:           "Test Tournament 9",
		Rounds:         1,
		MaxPlayerCount: -1,
		Countdown:      "1m0s",
		CreatedOn:      TimeNow,
		CreatedBy:      1,
		Status:         model.TournamentInProgress,
		Ruleset:        model.TournamentSwiss,
		Mode:           model.ModeCorrespondence1,
	},
}

var MatchesTournament9 = []model.FullMatch{
	{
		Ordering:      2,
		GameID:        GameIDNotFinished,
		CreatedOn:     TimeNow.Add(time.Minute * 1),
		TournamentKey: Tournament9InProgressUncompletedKey,
		Round:         1,
		WhiteID:       10,
		BlackID:       11,
	},
	{
		Ordering:      1,
		GameID:        model.GameID(TournamentMatchInsts[0].GameID),
		CreatedOn:     TimeNow.Add(time.Minute * 1),
		TournamentKey: Tournament9InProgressUncompletedKey,
		Round:         1,
		WhiteID:       10,
		BlackID:       11,
		Replay: &model.TournamentReplay{
			Replay: model.Replay{
				WhiteID:     10,
				BlackID:     11,
				Mode:        model.ModeCorrespondence7,
				Result:      model.WhiteWin,
				Cause:       model.Checkmate,
				WinEloDiff:  30,
				LoseEloDiff: -30,
				PlayedOn:    time.Date(2020, 1, 1, 1, 0, 0, 0, time.UTC),
			},
			ReplayColorElos: model.ReplayColorElos{WhiteEloDiff: 30, BlackEloDiff: -30},
		},
	},
}

var TournamentLbdChangeSets = []struct {
	Mode    model.GameMode
	ID      int64
	EloDiff float64
}{
	{model.ModeCorrespondence1, 4, 1400},
	{model.ModeCorrespondence1, 3, 1300},
	{model.ModeCorrespondence1, 2, 1200},
	{model.ModeCorrespondence1, 1, 1100},
}

// Tournament9RankedParticipants Ordered by `JoinedOn`, ranked with values in `TournamentLbdChangeSets`
var Tournament9RankedParticipants = []model.Participant{
	{
		User:       model.User{ID: 4, Username: "user4", Country: "us", JoinedOn: TimeNow},
		Elo:        2000,
		HighestElo: 2000,
		Rank:       1,
	},
	{
		User:       model.User{ID: 3, Username: "user3", Country: "us", JoinedOn: TimeNow},
		Elo:        900,
		HighestElo: 900,
		Rank:       2,
	},
	{
		User:       model.User{ID: 2, Username: "user2", Country: "us", JoinedOn: TimeNow},
		Elo:        1000,
		HighestElo: 1000,
		Rank:       3,
	},
	{
		User:       model.User{ID: 1, Username: "user1", Country: "us", JoinedOn: TimeNow},
		Elo:        1000,
		HighestElo: 1000,
		Rank:       4,
	},
}

// Tournament8RankedParticipants Ordered by `JoinedOn`, ranked with values in `TournamentLbdChangeSets`
var Tournament8RankedParticipants = []model.Participant{
	{
		User:       model.User{ID: 2, Username: "user2", Country: "us", JoinedOn: TimeNow},
		Elo:        1000,
		HighestElo: 1000,
		Rank:       3,
	},
	{
		User:       model.User{ID: 1, Username: "user1", Country: "us", JoinedOn: TimeNow},
		Elo:        1000,
		HighestElo: 1000,
		Rank:       4,
	},
}
