// Contract for data and messages for information exchange within Hexchess

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndKind int32

const (
	EndKind_NOT_ENDED EndKind = 0
	EndKind_FINISHED  EndKind = 1
	EndKind_ABORTED   EndKind = 2
)

// Enum value maps for EndKind.
var (
	EndKind_name = map[int32]string{
		0: "NOT_ENDED",
		1: "FINISHED",
		2: "ABORTED",
	}
	EndKind_value = map[string]int32{
		"NOT_ENDED": 0,
		"FINISHED":  1,
		"ABORTED":   2,
	}
)

func (x EndKind) Enum() *EndKind {
	p := new(EndKind)
	*p = x
	return p
}

func (x EndKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndKind) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (EndKind) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x EndKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndKind.Descriptor instead.
func (EndKind) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Elo           float64                `protobuf:"fixed64,4,opt,name=elo,proto3" json:"elo,omitempty"`
	IsGuest       bool                   `protobuf:"varint,5,opt,name=isGuest,proto3" json:"isGuest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerState) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerState) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *PlayerState) GetElo() float64 {
	if x != nil {
		return x.Elo
	}
	return 0
}

func (x *PlayerState) GetIsGuest() bool {
	if x != nil {
		return x.IsGuest
	}
	return false
}

type ChatMessages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*ChatMessage         `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessages) Reset() {
	*x = ChatMessages{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessages) ProtoMessage() {}

func (x *ChatMessages) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessages.ProtoReflect.Descriptor instead.
func (*ChatMessages) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessages) GetChats() []*ChatMessage {
	if x != nil {
		return x.Chats
	}
	return nil
}

type PieceMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piece         uint32                 `protobuf:"varint,1,opt,name=piece,proto3" json:"piece,omitempty"`
	FromFile      uint32                 `protobuf:"varint,2,opt,name=fromFile,proto3" json:"fromFile,omitempty"`
	FromRank      uint32                 `protobuf:"varint,3,opt,name=fromRank,proto3" json:"fromRank,omitempty"`
	ToFile        uint32                 `protobuf:"varint,4,opt,name=toFile,proto3" json:"toFile,omitempty"`
	ToRank        uint32                 `protobuf:"varint,5,opt,name=toRank,proto3" json:"toRank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PieceMove) Reset() {
	*x = PieceMove{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PieceMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PieceMove) ProtoMessage() {}

func (x *PieceMove) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PieceMove.ProtoReflect.Descriptor instead.
func (*PieceMove) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *PieceMove) GetPiece() uint32 {
	if x != nil {
		return x.Piece
	}
	return 0
}

func (x *PieceMove) GetFromFile() uint32 {
	if x != nil {
		return x.FromFile
	}
	return 0
}

func (x *PieceMove) GetFromRank() uint32 {
	if x != nil {
		return x.FromRank
	}
	return 0
}

func (x *PieceMove) GetToFile() uint32 {
	if x != nil {
		return x.ToFile
	}
	return 0
}

func (x *PieceMove) GetToRank() uint32 {
	if x != nil {
		return x.ToRank
	}
	return 0
}

type Hex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          uint32                 `protobuf:"varint,1,opt,name=file,proto3" json:"file,omitempty"`
	Rank          uint32                 `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hex) Reset() {
	*x = Hex{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hex) ProtoMessage() {}

func (x *Hex) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hex.ProtoReflect.Descriptor instead.
func (*Hex) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Hex) GetFile() uint32 {
	if x != nil {
		return x.File
	}
	return 0
}

func (x *Hex) GetRank() uint32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type PieceMoves struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piece         uint32                 `protobuf:"varint,1,opt,name=piece,proto3" json:"piece,omitempty"`
	FromFile      uint32                 `protobuf:"varint,2,opt,name=fromFile,proto3" json:"fromFile,omitempty"`
	FromRank      uint32                 `protobuf:"varint,3,opt,name=fromRank,proto3" json:"fromRank,omitempty"`
	Moves         []*Hex                 `protobuf:"bytes,4,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PieceMoves) Reset() {
	*x = PieceMoves{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PieceMoves) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PieceMoves) ProtoMessage() {}

func (x *PieceMoves) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PieceMoves.ProtoReflect.Descriptor instead.
func (*PieceMoves) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *PieceMoves) GetPiece() uint32 {
	if x != nil {
		return x.Piece
	}
	return 0
}

func (x *PieceMoves) GetFromFile() uint32 {
	if x != nil {
		return x.FromFile
	}
	return 0
}

func (x *PieceMoves) GetFromRank() uint32 {
	if x != nil {
		return x.FromRank
	}
	return 0
}

func (x *PieceMoves) GetMoves() []*Hex {
	if x != nil {
		return x.Moves
	}
	return nil
}

type BoardFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pieces        []uint32               `protobuf:"varint,1,rep,packed,name=pieces,proto3" json:"pieces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardFile) Reset() {
	*x = BoardFile{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardFile) ProtoMessage() {}

func (x *BoardFile) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardFile.ProtoReflect.Descriptor instead.
func (*BoardFile) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *BoardFile) GetPieces() []uint32 {
	if x != nil {
		return x.Pieces
	}
	return nil
}

type ChessBoard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsWhiteTurn   bool                   `protobuf:"varint,1,opt,name=is_white_turn,json=isWhiteTurn,proto3" json:"is_white_turn,omitempty"`
	File          []*BoardFile           `protobuf:"bytes,2,rep,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChessBoard) Reset() {
	*x = ChessBoard{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChessBoard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChessBoard) ProtoMessage() {}

func (x *ChessBoard) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChessBoard.ProtoReflect.Descriptor instead.
func (*ChessBoard) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ChessBoard) GetIsWhiteTurn() bool {
	if x != nil {
		return x.IsWhiteTurn
	}
	return false
}

func (x *ChessBoard) GetFile() []*BoardFile {
	if x != nil {
		return x.File
	}
	return nil
}

type HistMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piece         uint32                 `protobuf:"varint,1,opt,name=piece,proto3" json:"piece,omitempty"`
	FromFile      uint32                 `protobuf:"varint,2,opt,name=from_file,json=fromFile,proto3" json:"from_file,omitempty"`
	FromRank      uint32                 `protobuf:"varint,3,opt,name=from_rank,json=fromRank,proto3" json:"from_rank,omitempty"`
	ToFile        uint32                 `protobuf:"varint,4,opt,name=to_file,json=toFile,proto3" json:"to_file,omitempty"`
	ToRank        uint32                 `protobuf:"varint,5,opt,name=to_rank,json=toRank,proto3" json:"to_rank,omitempty"`
	Notation      string                 `protobuf:"bytes,6,opt,name=notation,proto3" json:"notation,omitempty"`
	WhiteTimerMs  int64                  `protobuf:"varint,7,opt,name=white_timer_ms,json=whiteTimerMs,proto3" json:"white_timer_ms,omitempty"`
	BlackTimerMs  int64                  `protobuf:"varint,8,opt,name=black_timer_ms,json=blackTimerMs,proto3" json:"black_timer_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistMove) Reset() {
	*x = HistMove{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistMove) ProtoMessage() {}

func (x *HistMove) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistMove.ProtoReflect.Descriptor instead.
func (*HistMove) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *HistMove) GetPiece() uint32 {
	if x != nil {
		return x.Piece
	}
	return 0
}

func (x *HistMove) GetFromFile() uint32 {
	if x != nil {
		return x.FromFile
	}
	return 0
}

func (x *HistMove) GetFromRank() uint32 {
	if x != nil {
		return x.FromRank
	}
	return 0
}

func (x *HistMove) GetToFile() uint32 {
	if x != nil {
		return x.ToFile
	}
	return 0
}

func (x *HistMove) GetToRank() uint32 {
	if x != nil {
		return x.ToRank
	}
	return 0
}

func (x *HistMove) GetNotation() string {
	if x != nil {
		return x.Notation
	}
	return ""
}

func (x *HistMove) GetWhiteTimerMs() int64 {
	if x != nil {
		return x.WhiteTimerMs
	}
	return 0
}

func (x *HistMove) GetBlackTimerMs() int64 {
	if x != nil {
		return x.BlackTimerMs
	}
	return 0
}

type ChessGame struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Board            *ChessBoard            `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	WhiteMoves       []*PieceMoves          `protobuf:"bytes,2,rep,name=white_moves,json=whiteMoves,proto3" json:"white_moves,omitempty"`
	BlackMoves       []*PieceMoves          `protobuf:"bytes,3,rep,name=black_moves,json=blackMoves,proto3" json:"black_moves,omitempty"`
	TakenWhitePieces []uint32               `protobuf:"varint,4,rep,packed,name=taken_white_pieces,json=takenWhitePieces,proto3" json:"taken_white_pieces,omitempty"`
	TakenBlackPieces []uint32               `protobuf:"varint,5,rep,packed,name=taken_black_pieces,json=takenBlackPieces,proto3" json:"taken_black_pieces,omitempty"`
	Moves            []*HistMove            `protobuf:"bytes,6,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChessGame) Reset() {
	*x = ChessGame{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChessGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChessGame) ProtoMessage() {}

func (x *ChessGame) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChessGame.ProtoReflect.Descriptor instead.
func (*ChessGame) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ChessGame) GetBoard() *ChessBoard {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *ChessGame) GetWhiteMoves() []*PieceMoves {
	if x != nil {
		return x.WhiteMoves
	}
	return nil
}

func (x *ChessGame) GetBlackMoves() []*PieceMoves {
	if x != nil {
		return x.BlackMoves
	}
	return nil
}

func (x *ChessGame) GetTakenWhitePieces() []uint32 {
	if x != nil {
		return x.TakenWhitePieces
	}
	return nil
}

func (x *ChessGame) GetTakenBlackPieces() []uint32 {
	if x != nil {
		return x.TakenBlackPieces
	}
	return nil
}

func (x *ChessGame) GetMoves() []*HistMove {
	if x != nil {
		return x.Moves
	}
	return nil
}

type ChessState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Game          *ChessGame             `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	WhitePlayer   *PlayerState           `protobuf:"bytes,4,opt,name=white_player,json=whitePlayer,proto3" json:"white_player,omitempty"`
	BlackPlayer   *PlayerState           `protobuf:"bytes,5,opt,name=black_player,json=blackPlayer,proto3" json:"black_player,omitempty"`
	FirstColor    string                 `protobuf:"bytes,6,opt,name=first_color,json=firstColor,proto3" json:"first_color,omitempty"`
	Mode          string                 `protobuf:"bytes,7,opt,name=mode,proto3" json:"mode,omitempty"`
	Touch         int64                  `protobuf:"varint,8,opt,name=touch,proto3" json:"touch,omitempty"`
	InitialBoard  *ChessBoard            `protobuf:"bytes,9,opt,name=initial_board,json=initialBoard,proto3" json:"initial_board,omitempty"`
	UndoId        int64                  `protobuf:"varint,10,opt,name=undo_id,json=undoId,proto3" json:"undo_id,omitempty"`
	EndState      EndKind                `protobuf:"varint,11,opt,name=end_state,json=endState,proto3,enum=messages.EndKind" json:"end_state,omitempty"`
	StartTimeMs   int64                  `protobuf:"varint,12,opt,name=start_time_ms,json=startTimeMs,proto3" json:"start_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChessState) Reset() {
	*x = ChessState{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChessState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChessState) ProtoMessage() {}

func (x *ChessState) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChessState.ProtoReflect.Descriptor instead.
func (*ChessState) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ChessState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChessState) GetGame() *ChessGame {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *ChessState) GetWhitePlayer() *PlayerState {
	if x != nil {
		return x.WhitePlayer
	}
	return nil
}

func (x *ChessState) GetBlackPlayer() *PlayerState {
	if x != nil {
		return x.BlackPlayer
	}
	return nil
}

func (x *ChessState) GetFirstColor() string {
	if x != nil {
		return x.FirstColor
	}
	return ""
}

func (x *ChessState) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ChessState) GetTouch() int64 {
	if x != nil {
		return x.Touch
	}
	return 0
}

func (x *ChessState) GetInitialBoard() *ChessBoard {
	if x != nil {
		return x.InitialBoard
	}
	return nil
}

func (x *ChessState) GetUndoId() int64 {
	if x != nil {
		return x.UndoId
	}
	return 0
}

func (x *ChessState) GetEndState() EndKind {
	if x != nil {
		return x.EndState
	}
	return EndKind_NOT_ENDED
}

func (x *ChessState) GetStartTimeMs() int64 {
	if x != nil {
		return x.StartTimeMs
	}
	return 0
}

type HistMoves struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moves         []*HistMove            `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistMoves) Reset() {
	*x = HistMoves{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistMoves) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistMoves) ProtoMessage() {}

func (x *HistMoves) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistMoves.ProtoReflect.Descriptor instead.
func (*HistMoves) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *HistMoves) GetMoves() []*HistMove {
	if x != nil {
		return x.Moves
	}
	return nil
}

type PieceMoveList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moves         []*PieceMove           `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PieceMoveList) Reset() {
	*x = PieceMoveList{}
	mi := &file_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PieceMoveList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PieceMoveList) ProtoMessage() {}

func (x *PieceMoveList) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PieceMoveList.ProtoReflect.Descriptor instead.
func (*PieceMoveList) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *PieceMoveList) GetMoves() []*PieceMove {
	if x != nil {
		return x.Moves
	}
	return nil
}

type MoveHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitialGame   *ChessGame             `protobuf:"bytes,1,opt,name=initial_game,json=initialGame,proto3" json:"initial_game,omitempty"`
	Steps         []*HistMove            `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveHistory) Reset() {
	*x = MoveHistory{}
	mi := &file_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveHistory) ProtoMessage() {}

func (x *MoveHistory) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveHistory.ProtoReflect.Descriptor instead.
func (*MoveHistory) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *MoveHistory) GetInitialGame() *ChessGame {
	if x != nil {
		return x.InitialGame
	}
	return nil
}

func (x *MoveHistory) GetSteps() []*HistMove {
	if x != nil {
		return x.Steps
	}
	return nil
}

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Promotion     uint32                 `protobuf:"varint,1,opt,name=promotion,proto3" json:"promotion,omitempty"`
	FromFile      uint32                 `protobuf:"varint,2,opt,name=fromFile,proto3" json:"fromFile,omitempty"`
	FromRank      uint32                 `protobuf:"varint,3,opt,name=fromRank,proto3" json:"fromRank,omitempty"`
	ToFile        uint32                 `protobuf:"varint,4,opt,name=toFile,proto3" json:"toFile,omitempty"`
	ToRank        uint32                 `protobuf:"varint,5,opt,name=toRank,proto3" json:"toRank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{13}
}

func (x *Move) GetPromotion() uint32 {
	if x != nil {
		return x.Promotion
	}
	return 0
}

func (x *Move) GetFromFile() uint32 {
	if x != nil {
		return x.FromFile
	}
	return 0
}

func (x *Move) GetFromRank() uint32 {
	if x != nil {
		return x.FromRank
	}
	return 0
}

func (x *Move) GetToFile() uint32 {
	if x != nil {
		return x.ToFile
	}
	return 0
}

func (x *Move) GetToRank() uint32 {
	if x != nil {
		return x.ToRank
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerState           `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SentAt        string                 `protobuf:"bytes,3,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{14}
}

func (x *ChatMessage) GetPlayer() *PlayerState {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *ChatMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatMessage) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ForfeitInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForfeitInput) Reset() {
	*x = ForfeitInput{}
	mi := &file_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForfeitInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForfeitInput) ProtoMessage() {}

func (x *ForfeitInput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForfeitInput.ProtoReflect.Descriptor instead.
func (*ForfeitInput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{15}
}

type MoveInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Move          *Move                  `protobuf:"bytes,1,opt,name=move,proto3" json:"move,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveInput) Reset() {
	*x = MoveInput{}
	mi := &file_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveInput) ProtoMessage() {}

func (x *MoveInput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveInput.ProtoReflect.Descriptor instead.
func (*MoveInput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{16}
}

func (x *MoveInput) GetMove() *Move {
	if x != nil {
		return x.Move
	}
	return nil
}

type ChatInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatInput) Reset() {
	*x = ChatInput{}
	mi := &file_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatInput) ProtoMessage() {}

func (x *ChatInput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatInput.ProtoReflect.Descriptor instead.
func (*ChatInput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{17}
}

func (x *ChatInput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UndoInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndoInput) Reset() {
	*x = UndoInput{}
	mi := &file_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndoInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoInput) ProtoMessage() {}

func (x *UndoInput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoInput.ProtoReflect.Descriptor instead.
func (*UndoInput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{18}
}

func (x *UndoInput) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type PingInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingInput) Reset() {
	*x = PingInput{}
	mi := &file_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingInput) ProtoMessage() {}

func (x *PingInput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingInput.ProtoReflect.Descriptor instead.
func (*PingInput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{19}
}

type GameInput struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*GameInput_Forfeit
	//	*GameInput_Move
	//	*GameInput_Chat
	//	*GameInput_Undo
	//	*GameInput_Ping
	Value         isGameInput_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameInput) Reset() {
	*x = GameInput{}
	mi := &file_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInput) ProtoMessage() {}

func (x *GameInput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInput.ProtoReflect.Descriptor instead.
func (*GameInput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{20}
}

func (x *GameInput) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GameInput) GetValue() isGameInput_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GameInput) GetForfeit() *ForfeitInput {
	if x != nil {
		if x, ok := x.Value.(*GameInput_Forfeit); ok {
			return x.Forfeit
		}
	}
	return nil
}

func (x *GameInput) GetMove() *MoveInput {
	if x != nil {
		if x, ok := x.Value.(*GameInput_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *GameInput) GetChat() *ChatInput {
	if x != nil {
		if x, ok := x.Value.(*GameInput_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *GameInput) GetUndo() *UndoInput {
	if x != nil {
		if x, ok := x.Value.(*GameInput_Undo); ok {
			return x.Undo
		}
	}
	return nil
}

func (x *GameInput) GetPing() *PingInput {
	if x != nil {
		if x, ok := x.Value.(*GameInput_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isGameInput_Value interface {
	isGameInput_Value()
}

type GameInput_Forfeit struct {
	Forfeit *ForfeitInput `protobuf:"bytes,2,opt,name=forfeit,proto3,oneof"`
}

type GameInput_Move struct {
	Move *MoveInput `protobuf:"bytes,3,opt,name=move,proto3,oneof"`
}

type GameInput_Chat struct {
	Chat *ChatInput `protobuf:"bytes,4,opt,name=chat,proto3,oneof"`
}

type GameInput_Undo struct {
	Undo *UndoInput `protobuf:"bytes,5,opt,name=undo,proto3,oneof"`
}

type GameInput_Ping struct {
	Ping *PingInput `protobuf:"bytes,6,opt,name=ping,proto3,oneof"`
}

func (*GameInput_Forfeit) isGameInput_Value() {}

func (*GameInput_Move) isGameInput_Value() {}

func (*GameInput_Chat) isGameInput_Value() {}

func (*GameInput_Undo) isGameInput_Value() {}

func (*GameInput_Ping) isGameInput_Value() {}

type ErrorOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorOutput) Reset() {
	*x = ErrorOutput{}
	mi := &file_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorOutput) ProtoMessage() {}

func (x *ErrorOutput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorOutput.ProtoReflect.Descriptor instead.
func (*ErrorOutput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{21}
}

func (x *ErrorOutput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InitOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *ChessState            `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Self          *PlayerState           `protobuf:"bytes,2,opt,name=self,proto3" json:"self,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitOutput) Reset() {
	*x = InitOutput{}
	mi := &file_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitOutput) ProtoMessage() {}

func (x *InitOutput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitOutput.ProtoReflect.Descriptor instead.
func (*InitOutput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{22}
}

func (x *InitOutput) GetState() *ChessState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *InitOutput) GetSelf() *PlayerState {
	if x != nil {
		return x.Self
	}
	return nil
}

type PlayersOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WhitePlayer   *PlayerState           `protobuf:"bytes,1,opt,name=white_player,json=whitePlayer,proto3" json:"white_player,omitempty"`
	BlackPlayer   *PlayerState           `protobuf:"bytes,2,opt,name=black_player,json=blackPlayer,proto3" json:"black_player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayersOutput) Reset() {
	*x = PlayersOutput{}
	mi := &file_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayersOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayersOutput) ProtoMessage() {}

func (x *PlayersOutput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayersOutput.ProtoReflect.Descriptor instead.
func (*PlayersOutput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{23}
}

func (x *PlayersOutput) GetWhitePlayer() *PlayerState {
	if x != nil {
		return x.WhitePlayer
	}
	return nil
}

func (x *PlayersOutput) GetBlackPlayer() *PlayerState {
	if x != nil {
		return x.BlackPlayer
	}
	return nil
}

type MoveOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Move          *HistMove              `protobuf:"bytes,1,opt,name=move,proto3" json:"move,omitempty"`
	Game          *ChessGame             `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveOutput) Reset() {
	*x = MoveOutput{}
	mi := &file_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveOutput) ProtoMessage() {}

func (x *MoveOutput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveOutput.ProtoReflect.Descriptor instead.
func (*MoveOutput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{24}
}

func (x *MoveOutput) GetMove() *HistMove {
	if x != nil {
		return x.Move
	}
	return nil
}

func (x *MoveOutput) GetGame() *ChessGame {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *MoveOutput) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UndoOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	UndoId        int64                  `protobuf:"varint,2,opt,name=undo_id,json=undoId,proto3" json:"undo_id,omitempty"`
	Game          *ChessGame             `protobuf:"bytes,3,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndoOutput) Reset() {
	*x = UndoOutput{}
	mi := &file_messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndoOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoOutput) ProtoMessage() {}

func (x *UndoOutput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoOutput.ProtoReflect.Descriptor instead.
func (*UndoOutput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{25}
}

func (x *UndoOutput) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *UndoOutput) GetUndoId() int64 {
	if x != nil {
		return x.UndoId
	}
	return 0
}

func (x *UndoOutput) GetGame() *ChessGame {
	if x != nil {
		return x.Game
	}
	return nil
}

type ForfeitOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndState      EndKind                `protobuf:"varint,1,opt,name=end_state,json=endState,proto3,enum=messages.EndKind" json:"end_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForfeitOutput) Reset() {
	*x = ForfeitOutput{}
	mi := &file_messages_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForfeitOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForfeitOutput) ProtoMessage() {}

func (x *ForfeitOutput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForfeitOutput.ProtoReflect.Descriptor instead.
func (*ForfeitOutput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{26}
}

func (x *ForfeitOutput) GetEndState() EndKind {
	if x != nil {
		return x.EndState
	}
	return EndKind_NOT_ENDED
}

type ReplayOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WhiteId       int64                  `protobuf:"varint,2,opt,name=white_id,json=whiteId,proto3" json:"white_id,omitempty"`
	BlackId       int64                  `protobuf:"varint,3,opt,name=black_id,json=blackId,proto3" json:"black_id,omitempty"`
	WhiteName     string                 `protobuf:"bytes,4,opt,name=white_name,json=whiteName,proto3" json:"white_name,omitempty"`
	BlackName     string                 `protobuf:"bytes,5,opt,name=black_name,json=blackName,proto3" json:"black_name,omitempty"`
	WhiteCountry  string                 `protobuf:"bytes,6,opt,name=white_country,json=whiteCountry,proto3" json:"white_country,omitempty"`
	BlackCountry  string                 `protobuf:"bytes,7,opt,name=black_country,json=blackCountry,proto3" json:"black_country,omitempty"`
	Mode          string                 `protobuf:"bytes,8,opt,name=mode,proto3" json:"mode,omitempty"`
	Result        string                 `protobuf:"bytes,9,opt,name=result,proto3" json:"result,omitempty"`
	Cause         string                 `protobuf:"bytes,10,opt,name=cause,proto3" json:"cause,omitempty"`
	WinEloDiff    float64                `protobuf:"fixed64,11,opt,name=win_elo_diff,json=winEloDiff,proto3" json:"win_elo_diff,omitempty"`
	LoseEloDiff   float64                `protobuf:"fixed64,12,opt,name=lose_elo_diff,json=loseEloDiff,proto3" json:"lose_elo_diff,omitempty"`
	WhiteElo      float64                `protobuf:"fixed64,13,opt,name=white_elo,json=whiteElo,proto3" json:"white_elo,omitempty"`
	BlackElo      float64                `protobuf:"fixed64,14,opt,name=black_elo,json=blackElo,proto3" json:"black_elo,omitempty"`
	WhiteEloDiff  float64                `protobuf:"fixed64,15,opt,name=white_elo_diff,json=whiteEloDiff,proto3" json:"white_elo_diff,omitempty"`
	BlackEloDiff  float64                `protobuf:"fixed64,16,opt,name=black_elo_diff,json=blackEloDiff,proto3" json:"black_elo_diff,omitempty"`
	PlayedOn      string                 `protobuf:"bytes,17,opt,name=played_on,json=playedOn,proto3" json:"played_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayOutput) Reset() {
	*x = ReplayOutput{}
	mi := &file_messages_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayOutput) ProtoMessage() {}

func (x *ReplayOutput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayOutput.ProtoReflect.Descriptor instead.
func (*ReplayOutput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{27}
}

func (x *ReplayOutput) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReplayOutput) GetWhiteId() int64 {
	if x != nil {
		return x.WhiteId
	}
	return 0
}

func (x *ReplayOutput) GetBlackId() int64 {
	if x != nil {
		return x.BlackId
	}
	return 0
}

func (x *ReplayOutput) GetWhiteName() string {
	if x != nil {
		return x.WhiteName
	}
	return ""
}

func (x *ReplayOutput) GetBlackName() string {
	if x != nil {
		return x.BlackName
	}
	return ""
}

func (x *ReplayOutput) GetWhiteCountry() string {
	if x != nil {
		return x.WhiteCountry
	}
	return ""
}

func (x *ReplayOutput) GetBlackCountry() string {
	if x != nil {
		return x.BlackCountry
	}
	return ""
}

func (x *ReplayOutput) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ReplayOutput) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ReplayOutput) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *ReplayOutput) GetWinEloDiff() float64 {
	if x != nil {
		return x.WinEloDiff
	}
	return 0
}

func (x *ReplayOutput) GetLoseEloDiff() float64 {
	if x != nil {
		return x.LoseEloDiff
	}
	return 0
}

func (x *ReplayOutput) GetWhiteElo() float64 {
	if x != nil {
		return x.WhiteElo
	}
	return 0
}

func (x *ReplayOutput) GetBlackElo() float64 {
	if x != nil {
		return x.BlackElo
	}
	return 0
}

func (x *ReplayOutput) GetWhiteEloDiff() float64 {
	if x != nil {
		return x.WhiteEloDiff
	}
	return 0
}

func (x *ReplayOutput) GetBlackEloDiff() float64 {
	if x != nil {
		return x.BlackEloDiff
	}
	return 0
}

func (x *ReplayOutput) GetPlayedOn() string {
	if x != nil {
		return x.PlayedOn
	}
	return ""
}

type GameOutputID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameOutputID) Reset() {
	*x = GameOutputID{}
	mi := &file_messages_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameOutputID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOutputID) ProtoMessage() {}

func (x *GameOutputID) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOutputID.ProtoReflect.Descriptor instead.
func (*GameOutputID) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{28}
}

func (x *GameOutputID) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameOutputID) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type GameOutput struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	GameId    string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	MessageId string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*GameOutput_Error
	//	*GameOutput_Init
	//	*GameOutput_Players
	//	*GameOutput_Move
	//	*GameOutput_Chat
	//	*GameOutput_Undo
	//	*GameOutput_Forfeit
	//	*GameOutput_Replay
	Value         isGameOutput_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameOutput) Reset() {
	*x = GameOutput{}
	mi := &file_messages_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOutput) ProtoMessage() {}

func (x *GameOutput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOutput.ProtoReflect.Descriptor instead.
func (*GameOutput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{29}
}

func (x *GameOutput) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameOutput) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GameOutput) GetValue() isGameOutput_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GameOutput) GetError() *ErrorOutput {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *GameOutput) GetInit() *InitOutput {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *GameOutput) GetPlayers() *PlayersOutput {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Players); ok {
			return x.Players
		}
	}
	return nil
}

func (x *GameOutput) GetMove() *MoveOutput {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *GameOutput) GetChat() *ChatMessage {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *GameOutput) GetUndo() *UndoOutput {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Undo); ok {
			return x.Undo
		}
	}
	return nil
}

func (x *GameOutput) GetForfeit() *ForfeitOutput {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Forfeit); ok {
			return x.Forfeit
		}
	}
	return nil
}

func (x *GameOutput) GetReplay() *ReplayOutput {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Replay); ok {
			return x.Replay
		}
	}
	return nil
}

type isGameOutput_Value interface {
	isGameOutput_Value()
}

type GameOutput_Error struct {
	Error *ErrorOutput `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type GameOutput_Init struct {
	Init *InitOutput `protobuf:"bytes,4,opt,name=init,proto3,oneof"`
}

type GameOutput_Players struct {
	Players *PlayersOutput `protobuf:"bytes,5,opt,name=players,proto3,oneof"`
}

type GameOutput_Move struct {
	Move *MoveOutput `protobuf:"bytes,6,opt,name=move,proto3,oneof"`
}

type GameOutput_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,7,opt,name=chat,proto3,oneof"`
}

type GameOutput_Undo struct {
	Undo *UndoOutput `protobuf:"bytes,8,opt,name=undo,proto3,oneof"`
}

type GameOutput_Forfeit struct {
	Forfeit *ForfeitOutput `protobuf:"bytes,9,opt,name=forfeit,proto3,oneof"`
}

type GameOutput_Replay struct {
	Replay *ReplayOutput `protobuf:"bytes,10,opt,name=replay,proto3,oneof"`
}

func (*GameOutput_Error) isGameOutput_Value() {}

func (*GameOutput_Init) isGameOutput_Value() {}

func (*GameOutput_Players) isGameOutput_Value() {}

func (*GameOutput_Move) isGameOutput_Value() {}

func (*GameOutput_Chat) isGameOutput_Value() {}

func (*GameOutput_Undo) isGameOutput_Value() {}

func (*GameOutput_Forfeit) isGameOutput_Value() {}

func (*GameOutput_Replay) isGameOutput_Value() {}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\bmessages\"w\n" +
	"\vPlayerState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x10\n" +
	"\x03elo\x18\x04 \x01(\x01R\x03elo\x12\x18\n" +
	"\aisGuest\x18\x05 \x01(\bR\aisGuest\";\n" +
	"\fChatMessages\x12+\n" +
	"\x05chats\x18\x01 \x03(\v2\x15.messages.ChatMessageR\x05chats\"\x89\x01\n" +
	"\tPieceMove\x12\x14\n" +
	"\x05piece\x18\x01 \x01(\rR\x05piece\x12\x1a\n" +
	"\bfromFile\x18\x02 \x01(\rR\bfromFile\x12\x1a\n" +
	"\bfromRank\x18\x03 \x01(\rR\bfromRank\x12\x16\n" +
	"\x06toFile\x18\x04 \x01(\rR\x06toFile\x12\x16\n" +
	"\x06toRank\x18\x05 \x01(\rR\x06toRank\"-\n" +
	"\x03Hex\x12\x12\n" +
	"\x04file\x18\x01 \x01(\rR\x04file\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\rR\x04rank\"\x7f\n" +
	"\n" +
	"PieceMoves\x12\x14\n" +
	"\x05piece\x18\x01 \x01(\rR\x05piece\x12\x1a\n" +
	"\bfromFile\x18\x02 \x01(\rR\bfromFile\x12\x1a\n" +
	"\bfromRank\x18\x03 \x01(\rR\bfromRank\x12#\n" +
	"\x05moves\x18\x04 \x03(\v2\r.messages.HexR\x05moves\"#\n" +
	"\tBoardFile\x12\x16\n" +
	"\x06pieces\x18\x01 \x03(\rR\x06pieces\"Y\n" +
	"\n" +
	"ChessBoard\x12\"\n" +
	"\ris_white_turn\x18\x01 \x01(\bR\visWhiteTurn\x12'\n" +
	"\x04file\x18\x02 \x03(\v2\x13.messages.BoardFileR\x04file\"\xf4\x01\n" +
	"\bHistMove\x12\x14\n" +
	"\x05piece\x18\x01 \x01(\rR\x05piece\x12\x1b\n" +
	"\tfrom_file\x18\x02 \x01(\rR\bfromFile\x12\x1b\n" +
	"\tfrom_rank\x18\x03 \x01(\rR\bfromRank\x12\x17\n" +
	"\ato_file\x18\x04 \x01(\rR\x06toFile\x12\x17\n" +
	"\ato_rank\x18\x05 \x01(\rR\x06toRank\x12\x1a\n" +
	"\bnotation\x18\x06 \x01(\tR\bnotation\x12$\n" +
	"\x0ewhite_timer_ms\x18\a \x01(\x03R\fwhiteTimerMs\x12$\n" +
	"\x0eblack_timer_ms\x18\b \x01(\x03R\fblackTimerMs\"\xab\x02\n" +
	"\tChessGame\x12*\n" +
	"\x05board\x18\x01 \x01(\v2\x14.messages.ChessBoardR\x05board\x125\n" +
	"\vwhite_moves\x18\x02 \x03(\v2\x14.messages.PieceMovesR\n" +
	"whiteMoves\x125\n" +
	"\vblack_moves\x18\x03 \x03(\v2\x14.messages.PieceMovesR\n" +
	"blackMoves\x12,\n" +
	"\x12taken_white_pieces\x18\x04 \x03(\rR\x10takenWhitePieces\x12,\n" +
	"\x12taken_black_pieces\x18\x05 \x03(\rR\x10takenBlackPieces\x12(\n" +
	"\x05moves\x18\x06 \x03(\v2\x12.messages.HistMoveR\x05moves\"\xac\x03\n" +
	"\n" +
	"ChessState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04game\x18\x02 \x01(\v2\x13.messages.ChessGameR\x04game\x128\n" +
	"\fwhite_player\x18\x04 \x01(\v2\x15.messages.PlayerStateR\vwhitePlayer\x128\n" +
	"\fblack_player\x18\x05 \x01(\v2\x15.messages.PlayerStateR\vblackPlayer\x12\x1f\n" +
	"\vfirst_color\x18\x06 \x01(\tR\n" +
	"firstColor\x12\x12\n" +
	"\x04mode\x18\a \x01(\tR\x04mode\x12\x14\n" +
	"\x05touch\x18\b \x01(\x03R\x05touch\x129\n" +
	"\rinitial_board\x18\t \x01(\v2\x14.messages.ChessBoardR\finitialBoard\x12\x17\n" +
	"\aundo_id\x18\n" +
	" \x01(\x03R\x06undoId\x12.\n" +
	"\tend_state\x18\v \x01(\x0e2\x11.messages.EndKindR\bendState\x12\"\n" +
	"\rstart_time_ms\x18\f \x01(\x03R\vstartTimeMs\"5\n" +
	"\tHistMoves\x12(\n" +
	"\x05moves\x18\x01 \x03(\v2\x12.messages.HistMoveR\x05moves\":\n" +
	"\rPieceMoveList\x12)\n" +
	"\x05moves\x18\x01 \x03(\v2\x13.messages.PieceMoveR\x05moves\"o\n" +
	"\vMoveHistory\x126\n" +
	"\finitial_game\x18\x01 \x01(\v2\x13.messages.ChessGameR\vinitialGame\x12(\n" +
	"\x05steps\x18\x02 \x03(\v2\x12.messages.HistMoveR\x05steps\"\x8c\x01\n" +
	"\x04Move\x12\x1c\n" +
	"\tpromotion\x18\x01 \x01(\rR\tpromotion\x12\x1a\n" +
	"\bfromFile\x18\x02 \x01(\rR\bfromFile\x12\x1a\n" +
	"\bfromRank\x18\x03 \x01(\rR\bfromRank\x12\x16\n" +
	"\x06toFile\x18\x04 \x01(\rR\x06toFile\x12\x16\n" +
	"\x06toRank\x18\x05 \x01(\rR\x06toRank\"\x7f\n" +
	"\vChatMessage\x12-\n" +
	"\x06player\x18\x01 \x01(\v2\x15.messages.PlayerStateR\x06player\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\asent_at\x18\x03 \x01(\tR\x06sentAt\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\"\x0e\n" +
	"\fForfeitInput\"/\n" +
	"\tMoveInput\x12\"\n" +
	"\x04move\x18\x01 \x01(\v2\x0e.messages.MoveR\x04move\"%\n" +
	"\tChatInput\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x1f\n" +
	"\tUndoInput\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\"\v\n" +
	"\tPingInput\"\x92\x02\n" +
	"\tGameInput\x12\x1c\n" +
	"\tmessageId\x18\x01 \x01(\tR\tmessageId\x122\n" +
	"\aforfeit\x18\x02 \x01(\v2\x16.messages.ForfeitInputH\x00R\aforfeit\x12)\n" +
	"\x04move\x18\x03 \x01(\v2\x13.messages.MoveInputH\x00R\x04move\x12)\n" +
	"\x04chat\x18\x04 \x01(\v2\x13.messages.ChatInputH\x00R\x04chat\x12)\n" +
	"\x04undo\x18\x05 \x01(\v2\x13.messages.UndoInputH\x00R\x04undo\x12)\n" +
	"\x04ping\x18\x06 \x01(\v2\x13.messages.PingInputH\x00R\x04pingB\a\n" +
	"\x05value\"'\n" +
	"\vErrorOutput\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"c\n" +
	"\n" +
	"InitOutput\x12*\n" +
	"\x05state\x18\x01 \x01(\v2\x14.messages.ChessStateR\x05state\x12)\n" +
	"\x04self\x18\x02 \x01(\v2\x15.messages.PlayerStateR\x04self\"\x83\x01\n" +
	"\rPlayersOutput\x128\n" +
	"\fwhite_player\x18\x01 \x01(\v2\x15.messages.PlayerStateR\vwhitePlayer\x128\n" +
	"\fblack_player\x18\x02 \x01(\v2\x15.messages.PlayerStateR\vblackPlayer\"|\n" +
	"\n" +
	"MoveOutput\x12&\n" +
	"\x04move\x18\x01 \x01(\v2\x12.messages.HistMoveR\x04move\x12'\n" +
	"\x04game\x18\x02 \x01(\v2\x13.messages.ChessGameR\x04game\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\"b\n" +
	"\n" +
	"UndoOutput\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x17\n" +
	"\aundo_id\x18\x02 \x01(\x03R\x06undoId\x12'\n" +
	"\x04game\x18\x03 \x01(\v2\x13.messages.ChessGameR\x04game\"?\n" +
	"\rForfeitOutput\x12.\n" +
	"\tend_state\x18\x01 \x01(\x0e2\x11.messages.EndKindR\bendState\"\x87\x04\n" +
	"\fReplayOutput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bwhite_id\x18\x02 \x01(\x03R\awhiteId\x12\x19\n" +
	"\bblack_id\x18\x03 \x01(\x03R\ablackId\x12\x1d\n" +
	"\n" +
	"white_name\x18\x04 \x01(\tR\twhiteName\x12\x1d\n" +
	"\n" +
	"black_name\x18\x05 \x01(\tR\tblackName\x12#\n" +
	"\rwhite_country\x18\x06 \x01(\tR\fwhiteCountry\x12#\n" +
	"\rblack_country\x18\a \x01(\tR\fblackCountry\x12\x12\n" +
	"\x04mode\x18\b \x01(\tR\x04mode\x12\x16\n" +
	"\x06result\x18\t \x01(\tR\x06result\x12\x14\n" +
	"\x05cause\x18\n" +
	" \x01(\tR\x05cause\x12 \n" +
	"\fwin_elo_diff\x18\v \x01(\x01R\n" +
	"winEloDiff\x12\"\n" +
	"\rlose_elo_diff\x18\f \x01(\x01R\vloseEloDiff\x12\x1b\n" +
	"\twhite_elo\x18\r \x01(\x01R\bwhiteElo\x12\x1b\n" +
	"\tblack_elo\x18\x0e \x01(\x01R\bblackElo\x12$\n" +
	"\x0ewhite_elo_diff\x18\x0f \x01(\x01R\fwhiteEloDiff\x12$\n" +
	"\x0eblack_elo_diff\x18\x10 \x01(\x01R\fblackEloDiff\x12\x1b\n" +
	"\tplayed_on\x18\x11 \x01(\tR\bplayedOn\"F\n" +
	"\fGameOutputID\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"\xc9\x03\n" +
	"\n" +
	"GameOutput\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12-\n" +
	"\x05error\x18\x03 \x01(\v2\x15.messages.ErrorOutputH\x00R\x05error\x12*\n" +
	"\x04init\x18\x04 \x01(\v2\x14.messages.InitOutputH\x00R\x04init\x123\n" +
	"\aplayers\x18\x05 \x01(\v2\x17.messages.PlayersOutputH\x00R\aplayers\x12*\n" +
	"\x04move\x18\x06 \x01(\v2\x14.messages.MoveOutputH\x00R\x04move\x12+\n" +
	"\x04chat\x18\a \x01(\v2\x15.messages.ChatMessageH\x00R\x04chat\x12*\n" +
	"\x04undo\x18\b \x01(\v2\x14.messages.UndoOutputH\x00R\x04undo\x123\n" +
	"\aforfeit\x18\t \x01(\v2\x17.messages.ForfeitOutputH\x00R\aforfeit\x120\n" +
	"\x06replay\x18\n" +
	" \x01(\v2\x16.messages.ReplayOutputH\x00R\x06replayB\a\n" +
	"\x05value*3\n" +
	"\aEndKind\x12\r\n" +
	"\tNOT_ENDED\x10\x00\x12\f\n" +
	"\bFINISHED\x10\x01\x12\v\n" +
	"\aABORTED\x10\x02B\x11Z\x0fhexchess-svc/pbb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_messages_proto_goTypes = []any{
	(EndKind)(0),          // 0: messages.EndKind
	(*PlayerState)(nil),   // 1: messages.PlayerState
	(*ChatMessages)(nil),  // 2: messages.ChatMessages
	(*PieceMove)(nil),     // 3: messages.PieceMove
	(*Hex)(nil),           // 4: messages.Hex
	(*PieceMoves)(nil),    // 5: messages.PieceMoves
	(*BoardFile)(nil),     // 6: messages.BoardFile
	(*ChessBoard)(nil),    // 7: messages.ChessBoard
	(*HistMove)(nil),      // 8: messages.HistMove
	(*ChessGame)(nil),     // 9: messages.ChessGame
	(*ChessState)(nil),    // 10: messages.ChessState
	(*HistMoves)(nil),     // 11: messages.HistMoves
	(*PieceMoveList)(nil), // 12: messages.PieceMoveList
	(*MoveHistory)(nil),   // 13: messages.MoveHistory
	(*Move)(nil),          // 14: messages.Move
	(*ChatMessage)(nil),   // 15: messages.ChatMessage
	(*ForfeitInput)(nil),  // 16: messages.ForfeitInput
	(*MoveInput)(nil),     // 17: messages.MoveInput
	(*ChatInput)(nil),     // 18: messages.ChatInput
	(*UndoInput)(nil),     // 19: messages.UndoInput
	(*PingInput)(nil),     // 20: messages.PingInput
	(*GameInput)(nil),     // 21: messages.GameInput
	(*ErrorOutput)(nil),   // 22: messages.ErrorOutput
	(*InitOutput)(nil),    // 23: messages.InitOutput
	(*PlayersOutput)(nil), // 24: messages.PlayersOutput
	(*MoveOutput)(nil),    // 25: messages.MoveOutput
	(*UndoOutput)(nil),    // 26: messages.UndoOutput
	(*ForfeitOutput)(nil), // 27: messages.ForfeitOutput
	(*ReplayOutput)(nil),  // 28: messages.ReplayOutput
	(*GameOutputID)(nil),  // 29: messages.GameOutputID
	(*GameOutput)(nil),    // 30: messages.GameOutput
}
var file_messages_proto_depIdxs = []int32{
	15, // 0: messages.ChatMessages.chats:type_name -> messages.ChatMessage
	4,  // 1: messages.PieceMoves.moves:type_name -> messages.Hex
	6,  // 2: messages.ChessBoard.file:type_name -> messages.BoardFile
	7,  // 3: messages.ChessGame.board:type_name -> messages.ChessBoard
	5,  // 4: messages.ChessGame.white_moves:type_name -> messages.PieceMoves
	5,  // 5: messages.ChessGame.black_moves:type_name -> messages.PieceMoves
	8,  // 6: messages.ChessGame.moves:type_name -> messages.HistMove
	9,  // 7: messages.ChessState.game:type_name -> messages.ChessGame
	1,  // 8: messages.ChessState.white_player:type_name -> messages.PlayerState
	1,  // 9: messages.ChessState.black_player:type_name -> messages.PlayerState
	7,  // 10: messages.ChessState.initial_board:type_name -> messages.ChessBoard
	0,  // 11: messages.ChessState.end_state:type_name -> messages.EndKind
	8,  // 12: messages.HistMoves.moves:type_name -> messages.HistMove
	3,  // 13: messages.PieceMoveList.moves:type_name -> messages.PieceMove
	9,  // 14: messages.MoveHistory.initial_game:type_name -> messages.ChessGame
	8,  // 15: messages.MoveHistory.steps:type_name -> messages.HistMove
	1,  // 16: messages.ChatMessage.player:type_name -> messages.PlayerState
	14, // 17: messages.MoveInput.move:type_name -> messages.Move
	16, // 18: messages.GameInput.forfeit:type_name -> messages.ForfeitInput
	17, // 19: messages.GameInput.move:type_name -> messages.MoveInput
	18, // 20: messages.GameInput.chat:type_name -> messages.ChatInput
	19, // 21: messages.GameInput.undo:type_name -> messages.UndoInput
	20, // 22: messages.GameInput.ping:type_name -> messages.PingInput
	10, // 23: messages.InitOutput.state:type_name -> messages.ChessState
	1,  // 24: messages.InitOutput.self:type_name -> messages.PlayerState
	1,  // 25: messages.PlayersOutput.white_player:type_name -> messages.PlayerState
	1,  // 26: messages.PlayersOutput.black_player:type_name -> messages.PlayerState
	8,  // 27: messages.MoveOutput.move:type_name -> messages.HistMove
	9,  // 28: messages.MoveOutput.game:type_name -> messages.ChessGame
	9,  // 29: messages.UndoOutput.game:type_name -> messages.ChessGame
	0,  // 30: messages.ForfeitOutput.end_state:type_name -> messages.EndKind
	22, // 31: messages.GameOutput.error:type_name -> messages.ErrorOutput
	23, // 32: messages.GameOutput.init:type_name -> messages.InitOutput
	24, // 33: messages.GameOutput.players:type_name -> messages.PlayersOutput
	25, // 34: messages.GameOutput.move:type_name -> messages.MoveOutput
	15, // 35: messages.GameOutput.chat:type_name -> messages.ChatMessage
	26, // 36: messages.GameOutput.undo:type_name -> messages.UndoOutput
	27, // 37: messages.GameOutput.forfeit:type_name -> messages.ForfeitOutput
	28, // 38: messages.GameOutput.replay:type_name -> messages.ReplayOutput
	39, // [39:39] is the sub-list for method output_type
	39, // [39:39] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[20].OneofWrappers = []any{
		(*GameInput_Forfeit)(nil),
		(*GameInput_Move)(nil),
		(*GameInput_Chat)(nil),
		(*GameInput_Undo)(nil),
		(*GameInput_Ping)(nil),
	}
	file_messages_proto_msgTypes[29].OneofWrappers = []any{
		(*GameOutput_Error)(nil),
		(*GameOutput_Init)(nil),
		(*GameOutput_Players)(nil),
		(*GameOutput_Move)(nil),
		(*GameOutput_Chat)(nil),
		(*GameOutput_Undo)(nil),
		(*GameOutput_Forfeit)(nil),
		(*GameOutput_Replay)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
