// Code generated by MockGen. DO NOT EDIT.
// Source: google.go
//
// Generated by this command:
//
//	mockgen -source=google.go -destination=./google_mock.go -package=cloud
//

// Package cloud is a generated GoMock package.
package cloud

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	idtoken "google.golang.org/api/idtoken"
)

// MockGoogleTokenValidator is a mock of GoogleTokenValidator interface.
type MockGoogleTokenValidator struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleTokenValidatorMockRecorder
	isgomock struct{}
}

// MockGoogleTokenValidatorMockRecorder is the mock recorder for MockGoogleTokenValidator.
type MockGoogleTokenValidatorMockRecorder struct {
	mock *MockGoogleTokenValidator
}

// NewMockGoogleTokenValidator creates a new mock instance.
func NewMockGoogleTokenValidator(ctrl *gomock.Controller) *MockGoogleTokenValidator {
	mock := &MockGoogleTokenValidator{ctrl: ctrl}
	mock.recorder = &MockGoogleTokenValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleTokenValidator) EXPECT() *MockGoogleTokenValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockGoogleTokenValidator) Validate(ctx context.Context, idToken, audience string) (*idtoken.Payload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, idToken, audience)
	ret0, _ := ret[0].(*idtoken.Payload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockGoogleTokenValidatorMockRecorder) Validate(ctx, idToken, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockGoogleTokenValidator)(nil).Validate), ctx, idToken, audience)
}
