package data

import (
	"context"
	"github.com/stretchr/testify/assert"
	"hexchess-svc/util"
	"math"
	"testing"
	"time"
)

func TestUpdateGameResultTx(t *testing.T) {
	pgDB, closer := BeforeDbTests(t, true)
	defer closer()

	ctx := context.WithValue(context.Background(), util.Trace, "testing-update-stats")

	testUser0 := TestUserEntities[0]
	testUser1 := TestUserEntities[1]

	cs, err := UpdateGameResultTx(ctx, pgDB, GRParams{WhiteID: testUser0.ID, BlackID: testUser1.ID, Cause: Checkmate, IsWhiteWin: true, MoveList: nil})
	assert.NoError(t, err)

	u1, err := GetUserByID(ctx, pgDB.Q, testUser0.ID)
	assert.NoError(t, err)
	u2, err := GetUserByID(ctx, pgDB.Q, testUser1.ID)
	assert.NoError(t, err)
	r1, err := GetReplay(ctx, pgDB.Q, cs.ReplayID)
	assert.NoError(t, err)

	// assert a value relatively close to the actual value
	cs.WinEloDiff = math.Round(cs.WinEloDiff)
	cs.LoseEloDiff = math.Round(cs.LoseEloDiff)
	u1.Elo = math.Round(u1.Elo)
	u2.Elo = math.Round(u2.Elo)

	assert.Equal(t, float64(1015), u1.Elo)
	assert.Equal(t, float64(985), u2.Elo)

	expReplay := ReplayEntity{
		ID:           cs.ReplayID,
		WhiteID:      testUser0.ID,
		BlackID:      testUser1.ID,
		WhiteName:    testUser0.Username,
		BlackName:    testUser1.Username,
		WhiteCountry: "us",
		BlackCountry: "us",
		Result:       WhiteWin,
		Cause:        Checkmate,
		WinElo:       15,
		LoseElo:      -15,
		WhiteEloDiff: 15,
		BlackEloDiff: -15,
		WhiteElo:     1015,
		BlackElo:     985,
		PlayedOn:     time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC),
	}
	util.AssertEqualIgnoring(t, expReplay, r1, ReplayEntityCmpOpts)

	cs.ReplayID = 0 // we can't assert this and don't care to, since replayID is autogenerated
	expChange := GRChangeSet{WinID: testUser0.ID, LoseID: testUser1.ID, WinEloDiff: 15, LoseEloDiff: -15}
	assert.Equal(t, expChange, cs)
}
