// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package mutator

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchInsertChallenge = `-- name: BatchInsertChallenge :batchexec
INSERT INTO challenges (challenger_id, challengee_id, mode, start_color, made_on)
VALUES ($1, $2, $3, $4,
        $5)
`

type BatchInsertChallengeBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchInsertChallengeParams struct {
	ChallengerID int64
	ChallengeeID int64
	Mode         ModeEnum
	StartColor   ColorEnum
	MadeOn       pgtype.Timestamptz
}

func (q *Queries) BatchInsertChallenge(ctx context.Context, arg []BatchInsertChallengeParams) *BatchInsertChallengeBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ChallengerID,
			a.ChallengeeID,
			a.Mode,
			a.StartColor,
			a.MadeOn,
		}
		batch.Queue(batchInsertChallenge, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchInsertChallengeBatchResults{br, len(arg), false}
}

func (b *BatchInsertChallengeBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchInsertChallengeBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchInsertTournamentMatch = `-- name: BatchInsertTournamentMatch :batchexec
INSERT INTO tournament_matches (tournament_key, game_id, white_id, black_id, round, created_on)
VALUES ($1::uuid,
        $2,
        $3,
        $4,
        $5,
        COALESCE($6::timestamptz, CURRENT_TIMESTAMP)) ON CONFLICT
ON CONSTRAINT tournament_matches_pkey DO NOTHING
`

type BatchInsertTournamentMatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchInsertTournamentMatchParams struct {
	TournamentKey pgtype.UUID
	GameID        string
	WhiteID       int64
	BlackID       int64
	Round         int32
	CreatedOn     pgtype.Timestamptz
}

func (q *Queries) BatchInsertTournamentMatch(ctx context.Context, arg []BatchInsertTournamentMatchParams) *BatchInsertTournamentMatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.TournamentKey,
			a.GameID,
			a.WhiteID,
			a.BlackID,
			a.Round,
			a.CreatedOn,
		}
		batch.Queue(batchInsertTournamentMatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchInsertTournamentMatchBatchResults{br, len(arg), false}
}

func (b *BatchInsertTournamentMatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchInsertTournamentMatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchInsertTournamentParticipant = `-- name: BatchInsertTournamentParticipant :batchexec
INSERT INTO tournament_participants (tournament_key, user_id, joined_on)
VALUES ($1::uuid, $2, $3::timestamptz)
`

type BatchInsertTournamentParticipantBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchInsertTournamentParticipantParams struct {
	TournamentKey pgtype.UUID
	UserID        int64
	JoinedOn      pgtype.Timestamptz
}

func (q *Queries) BatchInsertTournamentParticipant(ctx context.Context, arg []BatchInsertTournamentParticipantParams) *BatchInsertTournamentParticipantBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.TournamentKey,
			a.UserID,
			a.JoinedOn,
		}
		batch.Queue(batchInsertTournamentParticipant, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchInsertTournamentParticipantBatchResults{br, len(arg), false}
}

func (b *BatchInsertTournamentParticipantBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchInsertTournamentParticipantBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchInsertUser = `-- name: BatchInsertUser :batchone
INSERT INTO users (username,
                   country,
                   password,
                   salt,
                   joined_on)
VALUES ($1,
        $2,
        $3,
        $4,
        $5) RETURNING
    id,
    username,
    country,
    bio,
    joined_on
`

type BatchInsertUserBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchInsertUserParams struct {
	Username string
	Country  string
	Password string
	Salt     string
	JoinedOn pgtype.Timestamptz
}

type BatchInsertUserRow struct {
	ID       int64
	Username string
	Country  string
	Bio      string
	JoinedOn pgtype.Timestamptz
}

func (q *Queries) BatchInsertUser(ctx context.Context, arg []BatchInsertUserParams) *BatchInsertUserBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Username,
			a.Country,
			a.Password,
			a.Salt,
			a.JoinedOn,
		}
		batch.Queue(batchInsertUser, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchInsertUserBatchResults{br, len(arg), false}
}

func (b *BatchInsertUserBatchResults) QueryRow(f func(int, BatchInsertUserRow, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i BatchInsertUserRow
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.Username,
			&i.Country,
			&i.Bio,
			&i.JoinedOn,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *BatchInsertUserBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertRedisEventMetrics = `-- name: InsertRedisEventMetrics :batchexec
INSERT INTO redis_queue_metrics (group_id, event_id, stream_name, consumed_on, processed_on) 
VALUES ($1, $2, $3, $4, $5) ON CONFLICT
ON CONSTRAINT redis_queue_metrics_pkey DO NOTHING
`

type InsertRedisEventMetricsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertRedisEventMetricsParams struct {
	GroupId     pgtype.UUID
	EventId     pgtype.UUID
	StreamName  string
	ConsumedOn  pgtype.Timestamptz
	ProcessedOn pgtype.Timestamptz
}

func (q *Queries) InsertRedisEventMetrics(ctx context.Context, arg []InsertRedisEventMetricsParams) *InsertRedisEventMetricsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.GroupId,
			a.EventId,
			a.StreamName,
			a.ConsumedOn,
			a.ProcessedOn,
		}
		batch.Queue(insertRedisEventMetrics, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertRedisEventMetricsBatchResults{br, len(arg), false}
}

func (b *InsertRedisEventMetricsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertRedisEventMetricsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertUserElo = `-- name: UpsertUserElo :batchexec
INSERT INTO user_mode_elos AS u (user_id, mode, elo, highest_elo, wins, losses, draws)
VALUES (
    $1, $2, COALESCE ($3::FLOAT8, $4::FLOAT8), GREATEST($3, $4), $5, $6, $7)
ON CONFLICT ON CONSTRAINT user_mode_elos_pkey
    DO
UPDATE SET
    elo = COALESCE ($3, u.elo),
    highest_elo = GREATEST(u.highest_elo, $3),
    wins = u.wins + $5,
    losses = u.losses + $6,
    draws = u.draws + $7
`

type UpsertUserEloBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertUserEloParams struct {
	UserID     int64
	Mode       ModeEnum
	Elo        pgtype.Float8
	DefaultElo float64
	Wins       int32
	Losses     int32
	Draws      int32
}

func (q *Queries) UpsertUserElo(ctx context.Context, arg []UpsertUserEloParams) *UpsertUserEloBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.UserID,
			a.Mode,
			a.Elo,
			a.DefaultElo,
			a.Wins,
			a.Losses,
			a.Draws,
		}
		batch.Queue(upsertUserElo, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertUserEloBatchResults{br, len(arg), false}
}

func (b *UpsertUserEloBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertUserEloBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
