// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package mutator

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEventKey = `-- name: InsertEventKey :exec
INSERT INTO event_keys (id, data)
VALUES ($1, $2)
`

type InsertEventKeyParams struct {
	ID   pgtype.UUID
	Data []byte
}

func (q *Queries) InsertEventKey(ctx context.Context, arg InsertEventKeyParams) error {
	_, err := q.db.Exec(ctx, insertEventKey, arg.ID, arg.Data)
	return err
}
