// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gamemeta.sql

package mutator

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateGameMeta = `-- name: UpdateGameMeta :one
INSERT INTO games_metadata (game_id, mode, white_id, black_id, updated_on, ordering)
VALUES ($1, $2, $3, $4, $5,
        nextval('games_metadata_ordering_seq')) ON CONFLICT (game_id)
DO
UPDATE SET
    mode = $2,
    white_id = $3,
    black_id = $4,
    updated_on = $5,
    ordering = nextval('games_metadata_ordering_seq')
    RETURNING (xmax = 0) AS is_new_row, (SELECT total FROM games_metadata_count) AS count
`

type UpdateGameMetaParams struct {
	GameID    string
	Mode      ModeEnum
	WhiteID   pgtype.Int8
	BlackID   pgtype.Int8
	UpdatedOn pgtype.Timestamptz
}

type UpdateGameMetaRow struct {
	IsNewRow bool
	Count    int64
}

func (q *Queries) UpdateGameMeta(ctx context.Context, arg UpdateGameMetaParams) (UpdateGameMetaRow, error) {
	row := q.db.QueryRow(ctx, updateGameMeta,
		arg.GameID,
		arg.Mode,
		arg.WhiteID,
		arg.BlackID,
		arg.UpdatedOn,
	)
	var i UpdateGameMetaRow
	err := row.Scan(&i.IsNewRow, &i.Count)
	return i, err
}
