// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mutator

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CauseEnum string

const (
	CauseEnumCHECKMATE CauseEnum = "CHECKMATE"
	CauseEnumFORFEIT   CauseEnum = "FORFEIT"
	CauseEnumSTALEMATE CauseEnum = "STALEMATE"
)

func (e *CauseEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CauseEnum(s)
	case string:
		*e = CauseEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for CauseEnum: %T", src)
	}
	return nil
}

type NullCauseEnum struct {
	CauseEnum CauseEnum
	Valid     bool // Valid is true if CauseEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCauseEnum) Scan(value interface{}) error {
	if value == nil {
		ns.CauseEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CauseEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCauseEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CauseEnum), nil
}

type ColorEnum string

const (
	ColorEnumWHITE  ColorEnum = "WHITE"
	ColorEnumBLACK  ColorEnum = "BLACK"
	ColorEnumRANDOM ColorEnum = "RANDOM"
)

func (e *ColorEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ColorEnum(s)
	case string:
		*e = ColorEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ColorEnum: %T", src)
	}
	return nil
}

type NullColorEnum struct {
	ColorEnum ColorEnum
	Valid     bool // Valid is true if ColorEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullColorEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ColorEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ColorEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullColorEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ColorEnum), nil
}

type ModeEnum string

const (
	ModeEnumTIMED10          ModeEnum = "TIMED_1+0"
	ModeEnumTIMED32          ModeEnum = "TIMED_3+2"
	ModeEnumTIMED1510        ModeEnum = "TIMED_15+10"
	ModeEnumCORRESPONDENCE1  ModeEnum = "CORRESPONDENCE_1"
	ModeEnumCORRESPONDENCE7  ModeEnum = "CORRESPONDENCE_7"
	ModeEnumCORRESPONDENCE14 ModeEnum = "CORRESPONDENCE_14"
	ModeEnumTIMED50          ModeEnum = "TIMED_5+0"
)

func (e *ModeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModeEnum(s)
	case string:
		*e = ModeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ModeEnum: %T", src)
	}
	return nil
}

type NullModeEnum struct {
	ModeEnum ModeEnum
	Valid    bool // Valid is true if ModeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ModeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModeEnum), nil
}

type QueueTypeEnum string

const (
	QueueTypeEnumTOURNAMENTADVANCEEVENT QueueTypeEnum = "TOURNAMENT_ADVANCE_EVENT"
)

func (e *QueueTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QueueTypeEnum(s)
	case string:
		*e = QueueTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for QueueTypeEnum: %T", src)
	}
	return nil
}

type NullQueueTypeEnum struct {
	QueueTypeEnum QueueTypeEnum
	Valid         bool // Valid is true if QueueTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQueueTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.QueueTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QueueTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQueueTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QueueTypeEnum), nil
}

type ResultEnum string

const (
	ResultEnumWHITEWINS ResultEnum = "WHITE_WINS"
	ResultEnumBLACKWINS ResultEnum = "BLACK_WINS"
	ResultEnumDRAW      ResultEnum = "DRAW"
	ResultEnumRANDOM    ResultEnum = "RANDOM"
)

func (e *ResultEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResultEnum(s)
	case string:
		*e = ResultEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ResultEnum: %T", src)
	}
	return nil
}

type NullResultEnum struct {
	ResultEnum ResultEnum
	Valid      bool // Valid is true if ResultEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResultEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ResultEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResultEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResultEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResultEnum), nil
}

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState
	Valid         bool // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type TournamentRulesetEnum string

const (
	TournamentRulesetEnumKNOCKOUT   TournamentRulesetEnum = "KNOCKOUT"
	TournamentRulesetEnumROUNDROBIN TournamentRulesetEnum = "ROUND_ROBIN"
	TournamentRulesetEnumSWISS      TournamentRulesetEnum = "SWISS"
)

func (e *TournamentRulesetEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TournamentRulesetEnum(s)
	case string:
		*e = TournamentRulesetEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TournamentRulesetEnum: %T", src)
	}
	return nil
}

type NullTournamentRulesetEnum struct {
	TournamentRulesetEnum TournamentRulesetEnum
	Valid                 bool // Valid is true if TournamentRulesetEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTournamentRulesetEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TournamentRulesetEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TournamentRulesetEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTournamentRulesetEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TournamentRulesetEnum), nil
}

type TournamentStatusEnum string

const (
	TournamentStatusEnumLOBBY      TournamentStatusEnum = "LOBBY"
	TournamentStatusEnumSCHEDULED  TournamentStatusEnum = "SCHEDULED"
	TournamentStatusEnumINPROGRESS TournamentStatusEnum = "IN_PROGRESS"
	TournamentStatusEnumFINISHED   TournamentStatusEnum = "FINISHED"
	TournamentStatusEnumCANCELLED  TournamentStatusEnum = "CANCELLED"
)

func (e *TournamentStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TournamentStatusEnum(s)
	case string:
		*e = TournamentStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TournamentStatusEnum: %T", src)
	}
	return nil
}

type NullTournamentStatusEnum struct {
	TournamentStatusEnum TournamentStatusEnum
	Valid                bool // Valid is true if TournamentStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTournamentStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TournamentStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TournamentStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTournamentStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TournamentStatusEnum), nil
}

type Challenge struct {
	ChallengerID int64
	ChallengeeID int64
	StartColor   ColorEnum
	MadeOn       pgtype.Timestamptz
	Mode         ModeEnum
}

type EventKey struct {
	ID         pgtype.UUID
	Data       []byte
	ConsumedAt pgtype.Timestamp
}

type GamesMetadataCount struct {
	Total int64
}

type GamesMetadatum struct {
	Ordering  int64
	GameID    string
	Mode      ModeEnum
	WhiteID   pgtype.Int8
	BlackID   pgtype.Int8
	UpdatedOn pgtype.Timestamptz
}

type GooseDbVersion struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    pgtype.Timestamp
}

type RedisQueueMetric struct {
	EventID     pgtype.UUID
	GroupID     pgtype.UUID
	StreamName  string
	ConsumedOn  pgtype.Timestamptz
	ProcessedOn pgtype.Timestamptz
}

type Replay struct {
	ID             int64
	WhiteID        pgtype.Int8
	BlackID        pgtype.Int8
	Mode           ModeEnum
	Result         ResultEnum
	Cause          CauseEnum
	PlayedOn       pgtype.Timestamptz
	WinEloDiff     float64
	LoseEloDiff    float64
	WhiteElo       float64
	BlackElo       float64
	GameID         string
	TurnCount      int32
	Rating         pgtype.Float8
	PlayedOnAsDays pgtype.Int4
}

type ReplayMoveHistory struct {
	ReplayID int64
	Data     []byte
}

type RiverJob struct {
	ID           int64
	State        RiverJobState
	Attempt      int16
	MaxAttempts  int16
	AttemptedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	FinalizedAt  pgtype.Timestamptz
	ScheduledAt  pgtype.Timestamptz
	Priority     int16
	Args         []byte
	AttemptedBy  []string
	Errors       [][]byte
	Kind         string
	Metadata     []byte
	Queue        string
	Tags         []string
	UniqueKey    []byte
	UniqueStates pgtype.Bits
}

type RiverLeader struct {
	ElectedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	LeaderID  string
	Name      string
}

type RiverMigration struct {
	Line      string
	Version   int64
	CreatedAt pgtype.Timestamptz
}

type RiverNotification struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Payload   string
	Topic     string
}

type RiverQueue struct {
	Name      string
	CreatedAt pgtype.Timestamptz
	Metadata  []byte
	PausedAt  pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Tournament struct {
	ID                 int64
	TournamentKey      pgtype.UUID
	Name               string
	Rounds             int32
	Status             TournamentStatusEnum
	Mode               ModeEnum
	Countdown          int64
	CountdownStartedOn pgtype.Timestamptz
	CreatedOn          pgtype.Timestamptz
	CreatedBy          int64
	UpdatedOn          pgtype.Timestamptz
	Ruleset            TournamentRulesetEnum
	WinnerID           pgtype.Int8
}

type TournamentMatch struct {
	Ordering      int64
	TournamentKey pgtype.UUID
	Round         int32
	GameID        string
	CreatedOn     pgtype.Timestamptz
	WhiteID       int64
	BlackID       int64
}

type TournamentParticipant struct {
	TournamentKey pgtype.UUID
	UserID        int64
	JoinedOn      pgtype.Timestamptz
}

type User struct {
	ID               int64
	Username         string
	Country          string
	Bio              string
	JoinedOn         pgtype.Timestamptz
	Password         string
	Salt             string
	LoginAttempts    int32
	LastLoginAttempt pgtype.Timestamptz
	GoogleAccountID  pgtype.Text
}

type UserModeElo struct {
	UserID     int64
	Mode       ModeEnum
	Elo        float64
	HighestElo float64
	Wins       int32
	Losses     int32
	Draws      int32
}

type UsersMetadatum struct {
	ID    int64
	Count pgtype.Int4
}
