// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mutator

import (
	"context"
)

type Querier interface {
	BatchInsertChallenge(ctx context.Context, arg []BatchInsertChallengeParams) *BatchInsertChallengeBatchResults
	BatchInsertTournamentMatch(ctx context.Context, arg []BatchInsertTournamentMatchParams) *BatchInsertTournamentMatchBatchResults
	BatchInsertTournamentParticipant(ctx context.Context, arg []BatchInsertTournamentParticipantParams) *BatchInsertTournamentParticipantBatchResults
	BatchInsertUser(ctx context.Context, arg []BatchInsertUserParams) *BatchInsertUserBatchResults
	DeleteChallenge(ctx context.Context, arg DeleteChallengeParams) (DeleteChallengeRow, error)
	DeleteExpiredChallenges(ctx context.Context, arg DeleteExpiredChallengesParams) error
	DeleteTournamentParticipant(ctx context.Context, arg DeleteTournamentParticipantParams) ([]int64, error)
	IncrLoginAttempts(ctx context.Context, id int64) error
	InsertChallenge(ctx context.Context, arg InsertChallengeParams) (InsertChallengeRow, error)
	InsertEventKey(ctx context.Context, arg InsertEventKeyParams) error
	InsertRedisEventMetrics(ctx context.Context, arg []InsertRedisEventMetricsParams) *InsertRedisEventMetricsBatchResults
	InsertReplay(ctx context.Context, arg InsertReplayParams) (int64, error)
	InsertTournament(ctx context.Context, arg InsertTournamentParams) (int64, error)
	InsertTournamentParticipant(ctx context.Context, arg InsertTournamentParticipantParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error)
	ResetLoginAttempts(ctx context.Context, id int64) error
	UpdateGameMeta(ctx context.Context, arg UpdateGameMetaParams) (UpdateGameMetaRow, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateTournamentStatus(ctx context.Context, arg UpdateTournamentStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpsertReplayMoveHistories(ctx context.Context, arg UpsertReplayMoveHistoriesParams) error
	UpsertUserElo(ctx context.Context, arg []UpsertUserEloParams) *UpsertUserEloBatchResults
}

var _ Querier = (*Queries)(nil)
