// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: replay.sql

package mutator

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertReplay = `-- name: InsertReplay :one
INSERT INTO replays (game_id,
                     white_id,
                     black_id,
                     result,
                     cause,
                     win_elo_diff,
                     lose_elo_diff,
                     white_elo,
                     black_elo,
                     played_on,
                     mode,
                     turn_count)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        COALESCE($10, CURRENT_TIMESTAMP)::TIMESTAMPTZ,
        $11,
        $12) RETURNING id
`

type InsertReplayParams struct {
	GameID    string
	WhiteID   pgtype.Int8
	BlackID   pgtype.Int8
	Result    ResultEnum
	Cause     CauseEnum
	WinElo    float64
	LoseElo   float64
	WhiteElo  float64
	BlackElo  float64
	PlayedOn  pgtype.Timestamptz
	Mode      ModeEnum
	TurnCount int32
}

func (q *Queries) InsertReplay(ctx context.Context, arg InsertReplayParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertReplay,
		arg.GameID,
		arg.WhiteID,
		arg.BlackID,
		arg.Result,
		arg.Cause,
		arg.WinElo,
		arg.LoseElo,
		arg.WhiteElo,
		arg.BlackElo,
		arg.PlayedOn,
		arg.Mode,
		arg.TurnCount,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertReplayMoveHistories = `-- name: UpsertReplayMoveHistories :exec
INSERT INTO replay_move_histories (replay_id, data)
VALUES ($1, $2) ON CONFLICT
ON CONSTRAINT replay_move_histories_pkey
    DO
UPDATE
    SET data = $2
`

type UpsertReplayMoveHistoriesParams struct {
	ReplayID int64
	Data     []byte
}

func (q *Queries) UpsertReplayMoveHistories(ctx context.Context, arg UpsertReplayMoveHistoriesParams) error {
	_, err := q.db.Exec(ctx, upsertReplayMoveHistories, arg.ReplayID, arg.Data)
	return err
}
