// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tournament.sql

package mutator

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTournamentParticipant = `-- name: DeleteTournamentParticipant :many
DELETE
FROM tournament_participants tp USING tournaments t
WHERE
    tp.tournament_key = $1
  AND
    tp.user_id = $2
  AND
    t.tournament_key = tp.tournament_key
  AND
    t.status = 'LOBBY'::tournament_status_enum
    RETURNING user_id
`

type DeleteTournamentParticipantParams struct {
	TournamentKey pgtype.UUID
	UserID        int64
}

func (q *Queries) DeleteTournamentParticipant(ctx context.Context, arg DeleteTournamentParticipantParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, deleteTournamentParticipant, arg.TournamentKey, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTournament = `-- name: InsertTournament :one
INSERT INTO tournaments (tournament_key, name, rounds, ruleset, status, countdown, countdown_started_on, created_on,
                         created_by, updated_on, mode)
VALUES ($1::uuid,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11) RETURNING id
`

type InsertTournamentParams struct {
	TournamentKey      pgtype.UUID
	Name               string
	Rounds             int32
	Ruleset            TournamentRulesetEnum
	Status             TournamentStatusEnum
	Countdown          int64
	CountdownStartedOn pgtype.Timestamptz
	CreatedOn          pgtype.Timestamptz
	CreatedBy          int64
	UpdatedOn          pgtype.Timestamptz
	Mode               ModeEnum
}

func (q *Queries) InsertTournament(ctx context.Context, arg InsertTournamentParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertTournament,
		arg.TournamentKey,
		arg.Name,
		arg.Rounds,
		arg.Ruleset,
		arg.Status,
		arg.Countdown,
		arg.CountdownStartedOn,
		arg.CreatedOn,
		arg.CreatedBy,
		arg.UpdatedOn,
		arg.Mode,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTournamentParticipant = `-- name: InsertTournamentParticipant :exec
INSERT INTO tournament_participants (tournament_key, user_id, joined_on)
VALUES ($1::uuid, $2, $3)
`

type InsertTournamentParticipantParams struct {
	TournamentKey pgtype.UUID
	UserID        int64
	JoinedOn      pgtype.Timestamptz
}

func (q *Queries) InsertTournamentParticipant(ctx context.Context, arg InsertTournamentParticipantParams) error {
	_, err := q.db.Exec(ctx, insertTournamentParticipant, arg.TournamentKey, arg.UserID, arg.JoinedOn)
	return err
}

const updateTournamentStatus = `-- name: UpdateTournamentStatus :exec
UPDATE tournaments
SET status               = $1,
    updated_on           = COALESCE($2, CURRENT_TIMESTAMP),
    rounds               = COALESCE($3, rounds),
    winner_id            = COALESCE($4, winner_id),
    countdown_started_on = COALESCE($5, countdown_started_on)
WHERE tournament_key = $6
`

type UpdateTournamentStatusParams struct {
	Status             TournamentStatusEnum
	UpdatedOn          pgtype.Timestamptz
	Rounds             pgtype.Int4
	WinnerID           pgtype.Int8
	CountdownStartedOn pgtype.Timestamptz
	TournamentKey      pgtype.UUID
}

func (q *Queries) UpdateTournamentStatus(ctx context.Context, arg UpdateTournamentStatusParams) error {
	_, err := q.db.Exec(ctx, updateTournamentStatus,
		arg.Status,
		arg.UpdatedOn,
		arg.Rounds,
		arg.WinnerID,
		arg.CountdownStartedOn,
		arg.TournamentKey,
	)
	return err
}
