// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package mutator

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const incrLoginAttempts = `-- name: IncrLoginAttempts :exec
UPDATE users
SET last_login_attempt = CURRENT_TIMESTAMP,
    login_attempts     = login_attempts + 1
WHERE id = $1
`

func (q *Queries) IncrLoginAttempts(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrLoginAttempts, id)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (username,
                   country,
                   password,
                   salt,
                   google_account_id,
                   joined_on)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        COALESCE($6::TIMESTAMPTZ, CURRENT_TIMESTAMP)) RETURNING
    id,
    username,
    country,
    bio,
    joined_on
`

type InsertUserParams struct {
	Username        string
	Country         string
	Password        string
	Salt            string
	GoogleAccountID pgtype.Text
	JoinedOn        pgtype.Timestamptz
}

type InsertUserRow struct {
	ID       int64
	Username string
	Country  string
	Bio      string
	JoinedOn pgtype.Timestamptz
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Username,
		arg.Country,
		arg.Password,
		arg.Salt,
		arg.GoogleAccountID,
		arg.JoinedOn,
	)
	var i InsertUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Country,
		&i.Bio,
		&i.JoinedOn,
	)
	return i, err
}

const resetLoginAttempts = `-- name: ResetLoginAttempts :exec
UPDATE users
SET last_login_attempt = CURRENT_TIMESTAMP,
    login_attempts     = 0
WHERE id = $1
`

func (q *Queries) ResetLoginAttempts(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, resetLoginAttempts, id)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password = $1,
    salt     = $2
WHERE id = $3
`

type UpdatePasswordParams struct {
	Password string
	Salt     string
	ID       int64
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.Password, arg.Salt, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = COALESCE($1, username),
    country  = COALESCE($2, country),
    bio      = COALESCE($3, bio)
WHERE id = $4 RETURNING
    id,
    username,
    country,
    bio,
    joined_on
`

type UpdateUserParams struct {
	Username pgtype.Text
	Country  pgtype.Text
	Bio      pgtype.Text
	ID       int64
}

type UpdateUserRow struct {
	ID       int64
	Username string
	Country  string
	Bio      string
	JoinedOn pgtype.Timestamptz
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Country,
		arg.Bio,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Country,
		&i.Bio,
		&i.JoinedOn,
	)
	return i, err
}
