version: "1"

networks:
  elk:
    driver: bridge

volumes:
  redis_data:
    driver: local
  localstack-data:
    driver: local

services:
  redis-game-store:
    image: redis/redis-stack-server
    container_name: hexchess-redis-game-store
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  redis-cache:
    image: redis/redis-stack-server
    container_name: hexchess-redis-cache
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
  redis-pubsub:
    image: redis/redis-stack-server
    container_name: hexchess-redis-pubsub
    ports:
      - "6381:6379"