namespace serialization.io;

table Player {
    id: long;
    name: string;
    country: string;
    elo: float;
}

struct Hexagon {
    file: byte;
    rank: byte;
}

struct PieceMove {
    piece: byte;
    from: Hexagon;
    to: Hexagon;
}

table PieceMoves {
    hex: Hexagon;
    moves: [Hexagon];
}

table ChessBoard {
    is_white_turn: bool;
    pieces: [byte];
}

table ChessGame {
    board: ChessBoard;
    white_moves: [PieceMoves];
    black_moves: [PieceMoves];
    taken_white_pieces: [byte];
    taken_black_pieces: [byte];
}

table ChessRoom {
    id: string;
    move_list: [PieceMove];
    white_player: Player;
    black_player: Player;
    is_ended: bool;
    first_color: byte;
    time_control: byte;
    touch: long;
}