// Contract for GRPC server APIs within Hexchess

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchmakingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*MatchmakingRequest_Begin
	//	*MatchmakingRequest_Confirm
	Value         isMatchmakingRequest_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchmakingRequest) Reset() {
	*x = MatchmakingRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchmakingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchmakingRequest) ProtoMessage() {}

func (x *MatchmakingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchmakingRequest.ProtoReflect.Descriptor instead.
func (*MatchmakingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *MatchmakingRequest) GetValue() isMatchmakingRequest_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MatchmakingRequest) GetBegin() *MatchmakingBeginRequest {
	if x != nil {
		if x, ok := x.Value.(*MatchmakingRequest_Begin); ok {
			return x.Begin
		}
	}
	return nil
}

func (x *MatchmakingRequest) GetConfirm() *MatchmakingConfirmRequest {
	if x != nil {
		if x, ok := x.Value.(*MatchmakingRequest_Confirm); ok {
			return x.Confirm
		}
	}
	return nil
}

type isMatchmakingRequest_Value interface {
	isMatchmakingRequest_Value()
}

type MatchmakingRequest_Begin struct {
	Begin *MatchmakingBeginRequest `protobuf:"bytes,1,opt,name=begin,proto3,oneof"`
}

type MatchmakingRequest_Confirm struct {
	Confirm *MatchmakingConfirmRequest `protobuf:"bytes,2,opt,name=confirm,proto3,oneof"`
}

func (*MatchmakingRequest_Begin) isMatchmakingRequest_Value() {}

func (*MatchmakingRequest_Confirm) isMatchmakingRequest_Value() {}

type MatchmakingBeginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserElo       float64                `protobuf:"fixed64,2,opt,name=user_elo,json=userElo,proto3" json:"user_elo,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchmakingBeginRequest) Reset() {
	*x = MatchmakingBeginRequest{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchmakingBeginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchmakingBeginRequest) ProtoMessage() {}

func (x *MatchmakingBeginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchmakingBeginRequest.ProtoReflect.Descriptor instead.
func (*MatchmakingBeginRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *MatchmakingBeginRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MatchmakingBeginRequest) GetUserElo() float64 {
	if x != nil {
		return x.UserElo
	}
	return 0
}

func (x *MatchmakingBeginRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type MatchmakingConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accept        bool                   `protobuf:"varint,1,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchmakingConfirmRequest) Reset() {
	*x = MatchmakingConfirmRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchmakingConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchmakingConfirmRequest) ProtoMessage() {}

func (x *MatchmakingConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchmakingConfirmRequest.ProtoReflect.Descriptor instead.
func (*MatchmakingConfirmRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *MatchmakingConfirmRequest) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type MatchmakingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*MatchmakingResponse_Begin
	//	*MatchmakingResponse_Confirm
	Value         isMatchmakingResponse_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchmakingResponse) Reset() {
	*x = MatchmakingResponse{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchmakingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchmakingResponse) ProtoMessage() {}

func (x *MatchmakingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchmakingResponse.ProtoReflect.Descriptor instead.
func (*MatchmakingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *MatchmakingResponse) GetValue() isMatchmakingResponse_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MatchmakingResponse) GetBegin() *MatchmakingProposalResponse {
	if x != nil {
		if x, ok := x.Value.(*MatchmakingResponse_Begin); ok {
			return x.Begin
		}
	}
	return nil
}

func (x *MatchmakingResponse) GetConfirm() *MatchmakingConfirmResponse {
	if x != nil {
		if x, ok := x.Value.(*MatchmakingResponse_Confirm); ok {
			return x.Confirm
		}
	}
	return nil
}

type isMatchmakingResponse_Value interface {
	isMatchmakingResponse_Value()
}

type MatchmakingResponse_Begin struct {
	Begin *MatchmakingProposalResponse `protobuf:"bytes,1,opt,name=begin,proto3,oneof"`
}

type MatchmakingResponse_Confirm struct {
	Confirm *MatchmakingConfirmResponse `protobuf:"bytes,2,opt,name=confirm,proto3,oneof"`
}

func (*MatchmakingResponse_Begin) isMatchmakingResponse_Value() {}

func (*MatchmakingResponse_Confirm) isMatchmakingResponse_Value() {}

type MatchmakingProposalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserOneId     int64                  `protobuf:"varint,1,opt,name=user_one_id,json=userOneId,proto3" json:"user_one_id,omitempty"`
	UserTwoId     int64                  `protobuf:"varint,2,opt,name=user_two_id,json=userTwoId,proto3" json:"user_two_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchmakingProposalResponse) Reset() {
	*x = MatchmakingProposalResponse{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchmakingProposalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchmakingProposalResponse) ProtoMessage() {}

func (x *MatchmakingProposalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchmakingProposalResponse.ProtoReflect.Descriptor instead.
func (*MatchmakingProposalResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *MatchmakingProposalResponse) GetUserOneId() int64 {
	if x != nil {
		return x.UserOneId
	}
	return 0
}

func (x *MatchmakingProposalResponse) GetUserTwoId() int64 {
	if x != nil {
		return x.UserTwoId
	}
	return 0
}

type MatchmakingConfirmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchmakingConfirmResponse) Reset() {
	*x = MatchmakingConfirmResponse{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchmakingConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchmakingConfirmResponse) ProtoMessage() {}

func (x *MatchmakingConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchmakingConfirmResponse.ProtoReflect.Descriptor instead.
func (*MatchmakingConfirmResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x03api\"\x8f\x01\n" +
	"\x12MatchmakingRequest\x124\n" +
	"\x05begin\x18\x01 \x01(\v2\x1c.api.MatchmakingBeginRequestH\x00R\x05begin\x12:\n" +
	"\aconfirm\x18\x02 \x01(\v2\x1e.api.MatchmakingConfirmRequestH\x00R\aconfirmB\a\n" +
	"\x05value\"a\n" +
	"\x17MatchmakingBeginRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\buser_elo\x18\x02 \x01(\x01R\auserElo\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\"3\n" +
	"\x19MatchmakingConfirmRequest\x12\x16\n" +
	"\x06accept\x18\x01 \x01(\bR\x06accept\"\x95\x01\n" +
	"\x13MatchmakingResponse\x128\n" +
	"\x05begin\x18\x01 \x01(\v2 .api.MatchmakingProposalResponseH\x00R\x05begin\x12;\n" +
	"\aconfirm\x18\x02 \x01(\v2\x1f.api.MatchmakingConfirmResponseH\x00R\aconfirmB\a\n" +
	"\x05value\"]\n" +
	"\x1bMatchmakingProposalResponse\x12\x1e\n" +
	"\vuser_one_id\x18\x01 \x01(\x03R\tuserOneId\x12\x1e\n" +
	"\vuser_two_id\x18\x02 \x01(\x03R\tuserTwoId\"\x1c\n" +
	"\x1aMatchmakingConfirmResponse2_\n" +
	"\x11MatchmakerService\x12J\n" +
	"\x11MatchmakingStream\x12\x17.api.MatchmakingRequest\x1a\x18.api.MatchmakingResponse(\x010\x01B\x12Z\x10hexchess-svc/rpcb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_goTypes = []any{
	(*MatchmakingRequest)(nil),          // 0: api.MatchmakingRequest
	(*MatchmakingBeginRequest)(nil),     // 1: api.MatchmakingBeginRequest
	(*MatchmakingConfirmRequest)(nil),   // 2: api.MatchmakingConfirmRequest
	(*MatchmakingResponse)(nil),         // 3: api.MatchmakingResponse
	(*MatchmakingProposalResponse)(nil), // 4: api.MatchmakingProposalResponse
	(*MatchmakingConfirmResponse)(nil),  // 5: api.MatchmakingConfirmResponse
}
var file_api_proto_depIdxs = []int32{
	1, // 0: api.MatchmakingRequest.begin:type_name -> api.MatchmakingBeginRequest
	2, // 1: api.MatchmakingRequest.confirm:type_name -> api.MatchmakingConfirmRequest
	4, // 2: api.MatchmakingResponse.begin:type_name -> api.MatchmakingProposalResponse
	5, // 3: api.MatchmakingResponse.confirm:type_name -> api.MatchmakingConfirmResponse
	0, // 4: api.MatchmakerService.MatchmakingStream:input_type -> api.MatchmakingRequest
	3, // 5: api.MatchmakerService.MatchmakingStream:output_type -> api.MatchmakingResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_api_proto_msgTypes[0].OneofWrappers = []any{
		(*MatchmakingRequest_Begin)(nil),
		(*MatchmakingRequest_Confirm)(nil),
	}
	file_api_proto_msgTypes[3].OneofWrappers = []any{
		(*MatchmakingResponse_Begin)(nil),
		(*MatchmakingResponse_Confirm)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
