// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: challenge.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReceivedChallenges = `-- name: CountReceivedChallenges :one
SELECT COUNT(*)
FROM challenges
WHERE challengee_id = $1
`

func (q *Queries) CountReceivedChallenges(ctx context.Context, userid int64) (int64, error) {
	row := q.db.QueryRow(ctx, countReceivedChallenges, userid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const selectChallenge = `-- name: SelectChallenge :one
SELECT challenger_id, challengee_id, start_color, made_on, mode
FROM challenges
WHERE challenger_id = $1
  AND challengee_id = $2
`

type SelectChallengeParams struct {
	ChallengerID int64
	ChallengeeID int64
}

func (q *Queries) SelectChallenge(ctx context.Context, arg SelectChallengeParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, selectChallenge, arg.ChallengerID, arg.ChallengeeID)
	var i Challenge
	err := row.Scan(
		&i.ChallengerID,
		&i.ChallengeeID,
		&i.StartColor,
		&i.MadeOn,
		&i.Mode,
	)
	return i, err
}

const selectChallengesByParticipant = `-- name: SelectChallengesByParticipant :many
SELECT c.challenger_id,
       c.challengee_id,
       u2.username AS challenger_name,
       u2.country  AS challenger_country,
       e2.elo      AS challenger_elo,
       u1.username AS challengee_name,
       u1.country  AS challengee_country,
       e1.elo      AS challengee_elo,
       c.mode,
       c.start_color,
       c.made_on
FROM challenges c
         INNER JOIN users u1
                    ON u1.id = c.challengee_id
         INNER JOIN users u2
                    ON u2.id = c.challenger_id
         LEFT JOIN user_mode_elos e1
                   ON e1.user_id = c.challengee_id AND e1.mode = c.mode
         LEFT JOIN user_mode_elos e2
                   ON e2.user_id = c.challenger_id AND e2.mode = c.mode
WHERE (
    $1::BIGINT IS NULL
        OR
        challenger_id = $1::BIGINT
    )
  AND (
    $2::BIGINT IS NULL
        OR
        challengee_id = $2::BIGINT
    )
  AND made_on >= $3
ORDER BY made_on DESC
`

type SelectChallengesByParticipantParams struct {
	ChallengerID pgtype.Int8
	ChallengeeID pgtype.Int8
	Since        pgtype.Timestamptz
}

type SelectChallengesByParticipantRow struct {
	ChallengerID      int64
	ChallengeeID      int64
	ChallengerName    string
	ChallengerCountry string
	ChallengerElo     pgtype.Float8
	ChallengeeName    string
	ChallengeeCountry string
	ChallengeeElo     pgtype.Float8
	Mode              ModeEnum
	StartColor        ColorEnum
	MadeOn            pgtype.Timestamptz
}

func (q *Queries) SelectChallengesByParticipant(ctx context.Context, arg SelectChallengesByParticipantParams) ([]SelectChallengesByParticipantRow, error) {
	rows, err := q.db.Query(ctx, selectChallengesByParticipant, arg.ChallengerID, arg.ChallengeeID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectChallengesByParticipantRow
	for rows.Next() {
		var i SelectChallengesByParticipantRow
		if err := rows.Scan(
			&i.ChallengerID,
			&i.ChallengeeID,
			&i.ChallengerName,
			&i.ChallengerCountry,
			&i.ChallengerElo,
			&i.ChallengeeName,
			&i.ChallengeeCountry,
			&i.ChallengeeElo,
			&i.Mode,
			&i.StartColor,
			&i.MadeOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
