// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const selectByEventKeyID = `-- name: SelectByEventKeyID :one
SELECT data
FROM event_keys
WHERE id = $1
`

func (q *Queries) SelectByEventKeyID(ctx context.Context, arg pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, selectByEventKeyID, arg)
	var data []byte
	err := row.Scan(&data)
	return data, err
}
