// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gamemeta.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const selectGameMeta = `-- name: SelectGameMeta :one
SELECT ordering, game_id, mode, white_id, black_id, updated_on
FROM games_metadata
WHERE game_id = $1
`

func (q *Queries) SelectGameMeta(ctx context.Context, gameid string) (GamesMetadatum, error) {
	row := q.db.QueryRow(ctx, selectGameMeta, gameid)
	var i GamesMetadatum
	err := row.Scan(
		&i.Ordering,
		&i.GameID,
		&i.Mode,
		&i.WhiteID,
		&i.BlackID,
		&i.UpdatedOn,
	)
	return i, err
}

const selectGameMetas = `-- name: SelectGameMetas :many
SELECT gm.ordering,
       gm.game_id,
       gm.mode,
       gm.white_id,
       gm.black_id,
       u1.username AS white_name,
       u1.country  AS white_country,
       u2.username AS black_name,
       u2.country  AS black_country
FROM games_metadata gm
         LEFT JOIN users u1 ON u1.id = white_id
         LEFT JOIN users u2 ON u2.id = black_id
WHERE ($1::BIGINT IS NULL OR
     white_id = $1 OR
     black_id = $1)
  AND gm.ordering < $2
ORDER BY ordering DESC LIMIT $3::INT
`

type SelectGameMetasParams struct {
	ParticipantID pgtype.Int8
	AfterOrdering int64
	PerPage       pgtype.Int4
}

type SelectGameMetasRow struct {
	Ordering     int64
	GameID       string
	Mode         ModeEnum
	WhiteID      pgtype.Int8
	BlackID      pgtype.Int8
	WhiteName    pgtype.Text
	WhiteCountry pgtype.Text
	BlackName    pgtype.Text
	BlackCountry pgtype.Text
}

func (q *Queries) SelectGameMetas(ctx context.Context, arg SelectGameMetasParams) ([]SelectGameMetasRow, error) {
	rows, err := q.db.Query(ctx, selectGameMetas, arg.ParticipantID, arg.AfterOrdering, arg.PerPage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectGameMetasRow
	for rows.Next() {
		var i SelectGameMetasRow
		if err := rows.Scan(
			&i.Ordering,
			&i.GameID,
			&i.Mode,
			&i.WhiteID,
			&i.BlackID,
			&i.WhiteName,
			&i.WhiteCountry,
			&i.BlackName,
			&i.BlackCountry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectGameMetasCount = `-- name: SelectGameMetasCount :one
SELECT total
FROM games_metadata_count
`

func (q *Queries) SelectGameMetasCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, selectGameMetasCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}
