// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountReceivedChallenges(ctx context.Context, userid int64) (int64, error)
	SelectByEventKeyID(ctx context.Context, arg pgtype.UUID) ([]byte, error)
	SelectByGoogleAccountID(ctx context.Context, googleaccountid pgtype.Text) (SelectByGoogleAccountIDRow, error)
	SelectChallenge(ctx context.Context, arg SelectChallengeParams) (Challenge, error)
	SelectChallengesByParticipant(ctx context.Context, arg SelectChallengesByParticipantParams) ([]SelectChallengesByParticipantRow, error)
	SelectEloList(ctx context.Context, arg SelectEloListParams) ([]SelectEloListRow, error)
	SelectExistsUsersByIDs(ctx context.Context, ids []int64) ([]int64, error)
	SelectGameMeta(ctx context.Context, gameid string) (GamesMetadatum, error)
	SelectGameMetas(ctx context.Context, arg SelectGameMetasParams) ([]SelectGameMetasRow, error)
	SelectGameMetasCount(ctx context.Context) (int64, error)
	SelectLoginByName(ctx context.Context, username string) (SelectLoginByNameRow, error)
	SelectMatches(ctx context.Context, tournamentkey pgtype.UUID) ([]TournamentMatch, error)
	SelectMatchesByTournamentID(ctx context.Context, tournamentkey pgtype.UUID) ([]SelectMatchesByTournamentIDRow, error)
	SelectParticipants(ctx context.Context, tournamentkey pgtype.UUID) ([]TournamentParticipant, error)
	SelectParticipantsForMatchmakingByTournamentID(ctx context.Context, tournamentkey pgtype.UUID) ([]SelectParticipantsForMatchmakingByTournamentIDRow, error)
	SelectParticipantsWithUserByTournamentID(ctx context.Context, tournamentkey pgtype.UUID) ([]SelectParticipantsWithUserByTournamentIDRow, error)
	//     tm.mode
	SelectRecentMatchesByTournamentID(ctx context.Context, tournamentkey pgtype.UUID) ([]SelectRecentMatchesByTournamentIDRow, error)
	SelectReplayByGameID(ctx context.Context, gameID string) (SelectReplayByGameIDRow, error)
	SelectReplayByID(ctx context.Context, id int64) (SelectReplayByIDRow, error)
	SelectReplayElos(ctx context.Context, arg SelectReplayElosParams) ([]SelectReplayElosRow, error)
	SelectReplayIDByGameID(ctx context.Context, gameid string) (int64, error)
	SelectReplayMatchesByTournamentID(ctx context.Context, tournamentkey pgtype.UUID) ([]SelectReplayMatchesByTournamentIDRow, error)
	SelectReplayMoveHistoriesByIDs(ctx context.Context, replayids []int64) ([]ReplayMoveHistory, error)
	SelectReplayMoveHistoryByID(ctx context.Context, replayid int64) (ReplayMoveHistory, error)
	SelectReplayRowByID(ctx context.Context, id int64) (Replay, error)
	SelectReplaysByQuery(ctx context.Context, arg SelectReplaysByQueryParams) ([]SelectReplaysByQueryRow, error)
	SelectReplaysExistsByIDs(ctx context.Context, ids []int64) ([]int64, error)
	SelectTournamentByGameID(ctx context.Context, gameid string) (pgtype.UUID, error)
	SelectTournamentByID(ctx context.Context, tournamentkey pgtype.UUID) (SelectTournamentByIDRow, error)
	SelectTournamentStatus(ctx context.Context, tournamentkey pgtype.UUID) (SelectTournamentStatusRow, error)
	SelectTournamentWithParticipantCountByID(ctx context.Context, key pgtype.UUID) (SelectTournamentWithParticipantCountByIDRow, error)
	SelectTournaments(ctx context.Context, arg SelectTournamentsParams) ([]SelectTournamentsRow, error)
	SelectTournamentsByParticipant(ctx context.Context, arg SelectTournamentsByParticipantParams) ([]SelectTournamentsByParticipantRow, error)
	SelectUserByID(ctx context.Context, id int64) (SelectUserByIDRow, error)
	SelectUserElosByID(ctx context.Context, id int64) ([]UserModeElo, error)
	SelectUserElosByIDs(ctx context.Context, id []int64) ([]UserModeElo, error)
	SelectUserIDsByNames(ctx context.Context, usernames []string) ([]SelectUserIDsByNamesRow, error)
	SelectUserModeElosByIDs(ctx context.Context, arg SelectUserModeElosByIDsParams) ([]SelectUserModeElosByIDsRow, error)
	SelectUserWithEloByID(ctx context.Context, arg SelectUserWithEloByIDParams) (SelectUserWithEloByIDRow, error)
	SelectUserWithEloByIDs(ctx context.Context, arg SelectUserWithEloByIDsParams) ([]SelectUserWithEloByIDsRow, error)
	SelectUsersByIDs(ctx context.Context, id []int64) ([]SelectUsersByIDsRow, error)
	SelectUsersBySimilarity(ctx context.Context, arg SelectUsersBySimilarityParams) ([]SelectUsersBySimilarityRow, error)
}

var _ Querier = (*Queries)(nil)
