// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: replay.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const selectReplayByGameID = `-- name: SelectReplayByGameID :one
SELECT r.id,
       r.white_id,
       r.black_id,
       r.result,
       r.cause,
       r.played_on,
       r.win_elo_diff,
       r.lose_elo_diff,
       r.mode,
       r.rating,
       r.turn_count,
       u1.username AS white_name,
       u1.country  AS white_country,
       e1.elo      AS white_elo,
       u2.username AS black_name,
       u2.country  AS black_country,
       e2.elo      AS black_elo
FROM replays r
         -- ensures we get the white/black elo for mode at the time of retrieval
         LEFT JOIN users u1
                   ON u1.id = r.white_id
         LEFT JOIN users u2
                   ON u2.id = r.black_id
         LEFT JOIN user_mode_elos e1
                   ON e1.user_id = r.white_id AND e1.mode = r.mode
         LEFT JOIN user_mode_elos e2
                   ON e2.user_id = r.black_id AND e2.mode = r.mode
WHERE r.game_id = $1
`

type SelectReplayByGameIDRow struct {
	ID           int64
	WhiteID      pgtype.Int8
	BlackID      pgtype.Int8
	Result       ResultEnum
	Cause        CauseEnum
	PlayedOn     pgtype.Timestamptz
	WinEloDiff   float64
	LoseEloDiff  float64
	Mode         ModeEnum
	Rating       pgtype.Float8
	TurnCount    int32
	WhiteName    pgtype.Text
	WhiteCountry pgtype.Text
	WhiteElo     pgtype.Float8
	BlackName    pgtype.Text
	BlackCountry pgtype.Text
	BlackElo     pgtype.Float8
}

func (q *Queries) SelectReplayByGameID(ctx context.Context, gameID string) (SelectReplayByGameIDRow, error) {
	row := q.db.QueryRow(ctx, selectReplayByGameID, gameID)
	var i SelectReplayByGameIDRow
	err := row.Scan(
		&i.ID,
		&i.WhiteID,
		&i.BlackID,
		&i.Result,
		&i.Cause,
		&i.PlayedOn,
		&i.WinEloDiff,
		&i.LoseEloDiff,
		&i.Mode,
		&i.Rating,
		&i.TurnCount,
		&i.WhiteName,
		&i.WhiteCountry,
		&i.WhiteElo,
		&i.BlackName,
		&i.BlackCountry,
		&i.BlackElo,
	)
	return i, err
}

const selectReplayByID = `-- name: SelectReplayByID :one
SELECT r.id,
       r.white_id,
       r.black_id,
       r.result,
       r.cause,
       r.played_on,
       r.win_elo_diff,
       r.lose_elo_diff,
       r.mode,
       r.rating,
       r.turn_count,
       u1.username AS white_name,
       u1.country  AS white_country,
       e1.elo      AS white_elo,
       u2.username AS black_name,
       u2.country  AS black_country,
       e2.elo      AS black_elo
FROM replays r
         -- ensures we get the white/black elo for mode at the time of retrieval
         LEFT JOIN users u1
                   ON u1.id = r.white_id
         LEFT JOIN users u2
                   ON u2.id = r.black_id
         LEFT JOIN user_mode_elos e1
                   ON e1.user_id = r.white_id AND e1.mode = r.mode
         LEFT JOIN user_mode_elos e2
                   ON e2.user_id = r.black_id AND e2.mode = r.mode
WHERE r.id = $1
`

type SelectReplayByIDRow struct {
	ID           int64
	WhiteID      pgtype.Int8
	BlackID      pgtype.Int8
	Result       ResultEnum
	Cause        CauseEnum
	PlayedOn     pgtype.Timestamptz
	WinEloDiff   float64
	LoseEloDiff  float64
	Mode         ModeEnum
	Rating       pgtype.Float8
	TurnCount    int32
	WhiteName    pgtype.Text
	WhiteCountry pgtype.Text
	WhiteElo     pgtype.Float8
	BlackName    pgtype.Text
	BlackCountry pgtype.Text
	BlackElo     pgtype.Float8
}

func (q *Queries) SelectReplayByID(ctx context.Context, id int64) (SelectReplayByIDRow, error) {
	row := q.db.QueryRow(ctx, selectReplayByID, id)
	var i SelectReplayByIDRow
	err := row.Scan(
		&i.ID,
		&i.WhiteID,
		&i.BlackID,
		&i.Result,
		&i.Cause,
		&i.PlayedOn,
		&i.WinEloDiff,
		&i.LoseEloDiff,
		&i.Mode,
		&i.Rating,
		&i.TurnCount,
		&i.WhiteName,
		&i.WhiteCountry,
		&i.WhiteElo,
		&i.BlackName,
		&i.BlackCountry,
		&i.BlackElo,
	)
	return i, err
}

const selectReplayElos = `-- name: SelectReplayElos :many
SELECT id,
       mode,
       played_on,
       white_id,
       black_id,
       white_elo,
       black_elo -- gets the white/black elo at the time of insertion
FROM replays
WHERE (white_id = $1 OR black_id = $1)
  AND (played_on > $2 OR $2 IS NULL)
ORDER BY played_on
`

type SelectReplayElosParams struct {
	ID          pgtype.Int8
	PlayedAfter pgtype.Timestamptz
}

type SelectReplayElosRow struct {
	ID       int64
	Mode     ModeEnum
	PlayedOn pgtype.Timestamptz
	WhiteID  pgtype.Int8
	BlackID  pgtype.Int8
	WhiteElo float64
	BlackElo float64
}

func (q *Queries) SelectReplayElos(ctx context.Context, arg SelectReplayElosParams) ([]SelectReplayElosRow, error) {
	rows, err := q.db.Query(ctx, selectReplayElos, arg.ID, arg.PlayedAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectReplayElosRow
	for rows.Next() {
		var i SelectReplayElosRow
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.PlayedOn,
			&i.WhiteID,
			&i.BlackID,
			&i.WhiteElo,
			&i.BlackElo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectReplayIDByGameID = `-- name: SelectReplayIDByGameID :one
SELECT id
FROM replays
WHERE game_id = $1
`

func (q *Queries) SelectReplayIDByGameID(ctx context.Context, gameid string) (int64, error) {
	row := q.db.QueryRow(ctx, selectReplayIDByGameID, gameid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const selectReplayMoveHistoriesByIDs = `-- name: SelectReplayMoveHistoriesByIDs :many
SELECT replay_id, data
FROM replay_move_histories
WHERE replay_id = ANY ($1::bigint[])
`

func (q *Queries) SelectReplayMoveHistoriesByIDs(ctx context.Context, replayids []int64) ([]ReplayMoveHistory, error) {
	rows, err := q.db.Query(ctx, selectReplayMoveHistoriesByIDs, replayids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReplayMoveHistory
	for rows.Next() {
		var i ReplayMoveHistory
		if err := rows.Scan(&i.ReplayID, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectReplayMoveHistoryByID = `-- name: SelectReplayMoveHistoryByID :one
SELECT replay_id, data
FROM replay_move_histories
WHERE replay_id = $1
ORDER BY replay_id DESC LIMIT 1
`

func (q *Queries) SelectReplayMoveHistoryByID(ctx context.Context, replayid int64) (ReplayMoveHistory, error) {
	row := q.db.QueryRow(ctx, selectReplayMoveHistoryByID, replayid)
	var i ReplayMoveHistory
	err := row.Scan(&i.ReplayID, &i.Data)
	return i, err
}

const selectReplayRowByID = `-- name: SelectReplayRowByID :one
SELECT id, white_id, black_id, mode, result, cause, played_on, win_elo_diff, lose_elo_diff, white_elo, black_elo, game_id, turn_count, rating, played_on_as_days
FROM replays r
WHERE r.id = $1
`

func (q *Queries) SelectReplayRowByID(ctx context.Context, id int64) (Replay, error) {
	row := q.db.QueryRow(ctx, selectReplayRowByID, id)
	var i Replay
	err := row.Scan(
		&i.ID,
		&i.WhiteID,
		&i.BlackID,
		&i.Mode,
		&i.Result,
		&i.Cause,
		&i.PlayedOn,
		&i.WinEloDiff,
		&i.LoseEloDiff,
		&i.WhiteElo,
		&i.BlackElo,
		&i.GameID,
		&i.TurnCount,
		&i.Rating,
		&i.PlayedOnAsDays,
	)
	return i, err
}

const selectReplaysByQuery = `-- name: SelectReplaysByQuery :many
SELECT r.id,
       r.white_id,
       r.black_id,
       r.result,
       r.cause,
       r.played_on,
       r.win_elo_diff,
       r.lose_elo_diff,
       r.mode,
       r.rating,
       r.turn_count,
       u1.username AS white_name,
       u1.country  AS white_country,
       e1.elo      AS white_elo,
       u2.username AS black_name,
       u2.country  AS black_country,
       e2.elo      AS black_elo
FROM replays r
         -- ensures we get the white/black elo for mode at the time of retrieval
         LEFT JOIN users u1
                   ON u1.id = r.white_id
         LEFT JOIN users u2
                   ON u2.id = r.black_id
         LEFT JOIN user_mode_elos e1
                   ON e1.user_id = r.white_id AND e1.mode = r.mode
         LEFT JOIN user_mode_elos e2
                   ON e2.user_id = r.black_id AND e2.mode = r.mode
WHERE (r.mode = $1 OR $1 IS NULL)
    AND (r.result = $2 OR $2 IS NULL)
    AND (r.cause = $3 OR $3 IS NULL)
    AND (r.white_id = $4 OR $4 IS NULL)
    AND (r.black_id = $5 OR $5 IS NULL)
    AND (
        r.white_id = $6 OR r.black_id = $6 OR
        $6 IS NULL
    )
    AND (
        (r.white_id = $7 AND r.result = 'WHITE_WINS') OR
        (r.black_id = $7 AND r.result = 'BLACK_WINS') OR
        $7 IS NULL
    )
    AND (
        (r.white_id = $8 AND r.result = 'BLACK_WINS') OR
        (r.black_id = $8 AND r.result = 'WHITE_WINS') OR
        $8 IS NULL
    )
    AND (
        $9::INT IS NULL OR
            r.played_on_as_days >= $9::INT
    )
    AND (
        $10::INT IS NULL OR
            r.played_on_as_days <= $10::INT
    )
    AND
    CASE
        WHEN $11::TEXT = 'turnCount'
        THEN r.turn_count < $12 OR
              (r.turn_count = $12 AND r.id < $13)
        WHEN $11::TEXT = 'rating'
        THEN r.rating < $14 OR
              (r.rating = $14 AND r.id < $13)
        ELSE
          r.id < $13
    END
ORDER BY
    CASE
        WHEN $11::TEXT = 'turnCount'
        THEN r.turn_count
    END DESC,
    CASE
        WHEN $11::TEXT = 'rating'
        THEN r.rating
    END DESC,
    r.id DESC LIMIT $15
`

type SelectReplaysByQueryParams struct {
	Mode           NullModeEnum
	Result         NullResultEnum
	Cause          NullCauseEnum
	WhiteID        pgtype.Int8
	BlackID        pgtype.Int8
	UserID         pgtype.Int8
	WinnerID       pgtype.Int8
	LoserID        pgtype.Int8
	FromDateDays   pgtype.Int4
	ToDateDays     pgtype.Int4
	SortKey        string
	AfterTurnCount int32
	AfterID        int64
	AfterRating    pgtype.Float8
	PerPage        int32
}

type SelectReplaysByQueryRow struct {
	ID           int64
	WhiteID      pgtype.Int8
	BlackID      pgtype.Int8
	Result       ResultEnum
	Cause        CauseEnum
	PlayedOn     pgtype.Timestamptz
	WinEloDiff   float64
	LoseEloDiff  float64
	Mode         ModeEnum
	Rating       pgtype.Float8
	TurnCount    int32
	WhiteName    pgtype.Text
	WhiteCountry pgtype.Text
	WhiteElo     pgtype.Float8
	BlackName    pgtype.Text
	BlackCountry pgtype.Text
	BlackElo     pgtype.Float8
}

func (q *Queries) SelectReplaysByQuery(ctx context.Context, arg SelectReplaysByQueryParams) ([]SelectReplaysByQueryRow, error) {
	rows, err := q.db.Query(ctx, selectReplaysByQuery,
		arg.Mode,
		arg.Result,
		arg.Cause,
		arg.WhiteID,
		arg.BlackID,
		arg.UserID,
		arg.WinnerID,
		arg.LoserID,
		arg.FromDateDays,
		arg.ToDateDays,
		arg.SortKey,
		arg.AfterTurnCount,
		arg.AfterID,
		arg.AfterRating,
		arg.PerPage,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectReplaysByQueryRow
	for rows.Next() {
		var i SelectReplaysByQueryRow
		if err := rows.Scan(
			&i.ID,
			&i.WhiteID,
			&i.BlackID,
			&i.Result,
			&i.Cause,
			&i.PlayedOn,
			&i.WinEloDiff,
			&i.LoseEloDiff,
			&i.Mode,
			&i.Rating,
			&i.TurnCount,
			&i.WhiteName,
			&i.WhiteCountry,
			&i.WhiteElo,
			&i.BlackName,
			&i.BlackCountry,
			&i.BlackElo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectReplaysExistsByIDs = `-- name: SelectReplaysExistsByIDs :many
SELECT id
FROM replays
WHERE id = ANY ($1::bigint[])
`

func (q *Queries) SelectReplaysExistsByIDs(ctx context.Context, ids []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, selectReplaysExistsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
