// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tournament.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const selectMatches = `-- name: SelectMatches :many
SELECT ordering, tournament_key, round, game_id, created_on, white_id, black_id
FROM tournament_matches
WHERE tournament_key = $1::uuid
`

func (q *Queries) SelectMatches(ctx context.Context, tournamentkey pgtype.UUID) ([]TournamentMatch, error) {
	rows, err := q.db.Query(ctx, selectMatches, tournamentkey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TournamentMatch
	for rows.Next() {
		var i TournamentMatch
		if err := rows.Scan(
			&i.Ordering,
			&i.TournamentKey,
			&i.Round,
			&i.GameID,
			&i.CreatedOn,
			&i.WhiteID,
			&i.BlackID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectMatchesByTournamentID = `-- name: SelectMatchesByTournamentID :many
SELECT tm.round,
       tm.white_id,
       tm.black_id,
       r.result,
       e1.elo as white_elo,
       e2.elo as black_elo
FROM tournament_matches tm
         INNER JOIN tournaments t
                    ON t.tournament_key = tm.tournament_key
         LEFT JOIN replays r
                   ON r.game_id = tm.game_id
         LEFT JOIN user_mode_elos e1
                   ON tm.white_id = e1.user_id AND e1.mode = t.mode
         LEFT JOIN user_mode_elos e2
                   ON tm.black_id = e2.user_id AND e2.mode = t.mode
WHERE tm.tournament_key = $1
ORDER BY tm.round, tm.ordering
`

type SelectMatchesByTournamentIDRow struct {
	Round    int32
	WhiteID  int64
	BlackID  int64
	Result   NullResultEnum
	WhiteElo pgtype.Float8
	BlackElo pgtype.Float8
}

func (q *Queries) SelectMatchesByTournamentID(ctx context.Context, tournamentkey pgtype.UUID) ([]SelectMatchesByTournamentIDRow, error) {
	rows, err := q.db.Query(ctx, selectMatchesByTournamentID, tournamentkey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectMatchesByTournamentIDRow
	for rows.Next() {
		var i SelectMatchesByTournamentIDRow
		if err := rows.Scan(
			&i.Round,
			&i.WhiteID,
			&i.BlackID,
			&i.Result,
			&i.WhiteElo,
			&i.BlackElo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectParticipants = `-- name: SelectParticipants :many
SELECT tournament_key, user_id, joined_on
FROM tournament_participants
WHERE tournament_key = $1::uuid
`

func (q *Queries) SelectParticipants(ctx context.Context, tournamentkey pgtype.UUID) ([]TournamentParticipant, error) {
	rows, err := q.db.Query(ctx, selectParticipants, tournamentkey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TournamentParticipant
	for rows.Next() {
		var i TournamentParticipant
		if err := rows.Scan(&i.TournamentKey, &i.UserID, &i.JoinedOn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectParticipantsForMatchmakingByTournamentID = `-- name: SelectParticipantsForMatchmakingByTournamentID :many
SELECT tp.user_id, e.elo
FROM tournament_participants tp
         INNER JOIN tournaments t
                    ON t.tournament_key = tp.tournament_key
         LEFT JOIN user_mode_elos e -- must be a left join because mode elos are lazily initialized when user plays the first game.
                   ON tp.user_id = e.user_id AND e.mode = t.mode
WHERE tp.tournament_key = $1
ORDER BY tp.joined_on
`

type SelectParticipantsForMatchmakingByTournamentIDRow struct {
	UserID int64
	Elo    pgtype.Float8
}

func (q *Queries) SelectParticipantsForMatchmakingByTournamentID(ctx context.Context, tournamentkey pgtype.UUID) ([]SelectParticipantsForMatchmakingByTournamentIDRow, error) {
	rows, err := q.db.Query(ctx, selectParticipantsForMatchmakingByTournamentID, tournamentkey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectParticipantsForMatchmakingByTournamentIDRow
	for rows.Next() {
		var i SelectParticipantsForMatchmakingByTournamentIDRow
		if err := rows.Scan(&i.UserID, &i.Elo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectParticipantsWithUserByTournamentID = `-- name: SelectParticipantsWithUserByTournamentID :many
SELECT tp.tournament_key,
       tp.joined_on as tournament_joined_on,
       -- maintain parity with ` + "`" + `SelectUserWithEloByIDsRow` + "`" + `
       u.id         as user_id,
       u.username,
       u.country,
       u.bio,
       u.joined_on  as user_joined_on,
       e.elo,
       e.highest_elo,
       e.wins,
       e.losses,
       e.draws
FROM tournament_participants tp
         INNER JOIN tournaments t
                    ON t.tournament_key = tp.tournament_key
         INNER JOIN users u
                    ON u.id = tp.user_id
         LEFT JOIN user_mode_elos e -- must be a left join because mode elos are lazily initialized when user plays the first game.
                   ON u.id = e.user_id AND e.mode = t.mode
WHERE tp.tournament_key = $1::uuid
ORDER BY tp.joined_on DESC
`

type SelectParticipantsWithUserByTournamentIDRow struct {
	TournamentKey      pgtype.UUID
	TournamentJoinedOn pgtype.Timestamptz
	UserID             int64
	Username           string
	Country            string
	Bio                string
	UserJoinedOn       pgtype.Timestamptz
	Elo                pgtype.Float8
	HighestElo         pgtype.Float8
	Wins               pgtype.Int4
	Losses             pgtype.Int4
	Draws              pgtype.Int4
}

func (q *Queries) SelectParticipantsWithUserByTournamentID(ctx context.Context, tournamentkey pgtype.UUID) ([]SelectParticipantsWithUserByTournamentIDRow, error) {
	rows, err := q.db.Query(ctx, selectParticipantsWithUserByTournamentID, tournamentkey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectParticipantsWithUserByTournamentIDRow
	for rows.Next() {
		var i SelectParticipantsWithUserByTournamentIDRow
		if err := rows.Scan(
			&i.TournamentKey,
			&i.TournamentJoinedOn,
			&i.UserID,
			&i.Username,
			&i.Country,
			&i.Bio,
			&i.UserJoinedOn,
			&i.Elo,
			&i.HighestElo,
			&i.Wins,
			&i.Losses,
			&i.Draws,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectRecentMatchesByTournamentID = `-- name: SelectRecentMatchesByTournamentID :many
SELECT tm.game_id,
       tm.white_id,
       tm.black_id
FROM tournament_matches tm
WHERE tm.tournament_key = $1
ORDER BY tm.ordering
`

type SelectRecentMatchesByTournamentIDRow struct {
	GameID  string
	WhiteID int64
	BlackID int64
}

// tm.mode
func (q *Queries) SelectRecentMatchesByTournamentID(ctx context.Context, tournamentkey pgtype.UUID) ([]SelectRecentMatchesByTournamentIDRow, error) {
	rows, err := q.db.Query(ctx, selectRecentMatchesByTournamentID, tournamentkey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectRecentMatchesByTournamentIDRow
	for rows.Next() {
		var i SelectRecentMatchesByTournamentIDRow
		if err := rows.Scan(&i.GameID, &i.WhiteID, &i.BlackID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectReplayMatchesByTournamentID = `-- name: SelectReplayMatchesByTournamentID :many
SELECT tm.ordering,
       tm.game_id,
       tm.tournament_key,
       tm.round,
       tm.created_on,
       tm.white_id,
       tm.black_id,
       r.id as replay_id,
       r.result,
       r.cause,
       r.played_on,
       r.win_elo_diff,
       r.lose_elo_diff,
       r.mode
FROM tournament_matches tm
         -- must be a left join, if the game is not finished, it does not have a replay yet
         LEFT JOIN replays r
                   ON r.game_id = tm.game_id
WHERE tm.tournament_key = $1::uuid
ORDER BY tm.ordering DESC
`

type SelectReplayMatchesByTournamentIDRow struct {
	Ordering      int64
	GameID        string
	TournamentKey pgtype.UUID
	Round         int32
	CreatedOn     pgtype.Timestamptz
	WhiteID       int64
	BlackID       int64
	ReplayID      pgtype.Int8
	Result        NullResultEnum
	Cause         NullCauseEnum
	PlayedOn      pgtype.Timestamptz
	WinEloDiff    pgtype.Float8
	LoseEloDiff   pgtype.Float8
	Mode          NullModeEnum
}

func (q *Queries) SelectReplayMatchesByTournamentID(ctx context.Context, tournamentkey pgtype.UUID) ([]SelectReplayMatchesByTournamentIDRow, error) {
	rows, err := q.db.Query(ctx, selectReplayMatchesByTournamentID, tournamentkey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectReplayMatchesByTournamentIDRow
	for rows.Next() {
		var i SelectReplayMatchesByTournamentIDRow
		if err := rows.Scan(
			&i.Ordering,
			&i.GameID,
			&i.TournamentKey,
			&i.Round,
			&i.CreatedOn,
			&i.WhiteID,
			&i.BlackID,
			&i.ReplayID,
			&i.Result,
			&i.Cause,
			&i.PlayedOn,
			&i.WinEloDiff,
			&i.LoseEloDiff,
			&i.Mode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectTournamentByGameID = `-- name: SelectTournamentByGameID :one
SELECT tournament_key
FROM tournament_matches
WHERE game_id = $1
`

func (q *Queries) SelectTournamentByGameID(ctx context.Context, gameid string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, selectTournamentByGameID, gameid)
	var tournament_key pgtype.UUID
	err := row.Scan(&tournament_key)
	return tournament_key, err
}

const selectTournamentByID = `-- name: SelectTournamentByID :one
SELECT id,
       tournament_key,
       name,
       rounds,
       ruleset,
       status,
       winner_id,
       countdown,
       countdown_started_on,
       created_on,
       updated_on,
       created_by,
       mode
FROM tournaments
WHERE tournament_key = $1::uuid
`

type SelectTournamentByIDRow struct {
	ID                 int64
	TournamentKey      pgtype.UUID
	Name               string
	Rounds             int32
	Ruleset            TournamentRulesetEnum
	Status             TournamentStatusEnum
	WinnerID           pgtype.Int8
	Countdown          int64
	CountdownStartedOn pgtype.Timestamptz
	CreatedOn          pgtype.Timestamptz
	UpdatedOn          pgtype.Timestamptz
	CreatedBy          int64
	Mode               ModeEnum
}

func (q *Queries) SelectTournamentByID(ctx context.Context, tournamentkey pgtype.UUID) (SelectTournamentByIDRow, error) {
	row := q.db.QueryRow(ctx, selectTournamentByID, tournamentkey)
	var i SelectTournamentByIDRow
	err := row.Scan(
		&i.ID,
		&i.TournamentKey,
		&i.Name,
		&i.Rounds,
		&i.Ruleset,
		&i.Status,
		&i.WinnerID,
		&i.Countdown,
		&i.CountdownStartedOn,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.CreatedBy,
		&i.Mode,
	)
	return i, err
}

const selectTournamentStatus = `-- name: SelectTournamentStatus :one
SELECT status, winner_id
FROM tournaments
WHERE tournament_key = $1::uuid
`

type SelectTournamentStatusRow struct {
	Status   TournamentStatusEnum
	WinnerID pgtype.Int8
}

func (q *Queries) SelectTournamentStatus(ctx context.Context, tournamentkey pgtype.UUID) (SelectTournamentStatusRow, error) {
	row := q.db.QueryRow(ctx, selectTournamentStatus, tournamentkey)
	var i SelectTournamentStatusRow
	err := row.Scan(&i.Status, &i.WinnerID)
	return i, err
}

const selectTournamentWithParticipantCountByID = `-- name: SelectTournamentWithParticipantCountByID :one
SELECT t.tournament_key,
       t.rounds,
       t.ruleset,
       t.status,
       t.countdown_started_on,
       t.mode,
       (SELECT COUNT(*)
        FROM tournament_participants tp
        WHERE tp.tournament_key = t.tournament_key) ::INTEGER as participant_count
FROM tournaments t
WHERE t.tournament_key = $1
`

type SelectTournamentWithParticipantCountByIDRow struct {
	TournamentKey      pgtype.UUID
	Rounds             int32
	Ruleset            TournamentRulesetEnum
	Status             TournamentStatusEnum
	CountdownStartedOn pgtype.Timestamptz
	Mode               ModeEnum
	ParticipantCount   int32
}

func (q *Queries) SelectTournamentWithParticipantCountByID(ctx context.Context, key pgtype.UUID) (SelectTournamentWithParticipantCountByIDRow, error) {
	row := q.db.QueryRow(ctx, selectTournamentWithParticipantCountByID, key)
	var i SelectTournamentWithParticipantCountByIDRow
	err := row.Scan(
		&i.TournamentKey,
		&i.Rounds,
		&i.Ruleset,
		&i.Status,
		&i.CountdownStartedOn,
		&i.Mode,
		&i.ParticipantCount,
	)
	return i, err
}

const selectTournaments = `-- name: SelectTournaments :many
SELECT id,
       tournament_key,
       name,
       rounds,
       ruleset,
       status,
       winner_id,
       countdown,
       countdown_started_on,
       created_on,
       updated_on,
       created_by,
       mode
FROM tournaments
WHERE id < $1
ORDER BY id DESC LIMIT $2
`

type SelectTournamentsParams struct {
	AfterID int64
	PerPage int32
}

type SelectTournamentsRow struct {
	ID                 int64
	TournamentKey      pgtype.UUID
	Name               string
	Rounds             int32
	Ruleset            TournamentRulesetEnum
	Status             TournamentStatusEnum
	WinnerID           pgtype.Int8
	Countdown          int64
	CountdownStartedOn pgtype.Timestamptz
	CreatedOn          pgtype.Timestamptz
	UpdatedOn          pgtype.Timestamptz
	CreatedBy          int64
	Mode               ModeEnum
}

func (q *Queries) SelectTournaments(ctx context.Context, arg SelectTournamentsParams) ([]SelectTournamentsRow, error) {
	rows, err := q.db.Query(ctx, selectTournaments, arg.AfterID, arg.PerPage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectTournamentsRow
	for rows.Next() {
		var i SelectTournamentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TournamentKey,
			&i.Name,
			&i.Rounds,
			&i.Ruleset,
			&i.Status,
			&i.WinnerID,
			&i.Countdown,
			&i.CountdownStartedOn,
			&i.CreatedOn,
			&i.UpdatedOn,
			&i.CreatedBy,
			&i.Mode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectTournamentsByParticipant = `-- name: SelectTournamentsByParticipant :many
SELECT t.id,
       t.tournament_key,
       t.name,
       t.rounds,
       t.ruleset,
       t.status,
       t.winner_id,
       t.countdown,
       t.countdown_started_on,
       t.created_on,
       t.updated_on,
       t.created_by,
       t.mode
FROM tournament_participants tp
         INNER JOIN tournaments t
                    ON t.tournament_key = tp.tournament_key AND t.id < $1
WHERE tp.user_id = $2
ORDER BY t.id DESC LIMIT $3
`

type SelectTournamentsByParticipantParams struct {
	AfterID int64
	UserID  int64
	PerPage int32
}

type SelectTournamentsByParticipantRow struct {
	ID                 int64
	TournamentKey      pgtype.UUID
	Name               string
	Rounds             int32
	Ruleset            TournamentRulesetEnum
	Status             TournamentStatusEnum
	WinnerID           pgtype.Int8
	Countdown          int64
	CountdownStartedOn pgtype.Timestamptz
	CreatedOn          pgtype.Timestamptz
	UpdatedOn          pgtype.Timestamptz
	CreatedBy          int64
	Mode               ModeEnum
}

func (q *Queries) SelectTournamentsByParticipant(ctx context.Context, arg SelectTournamentsByParticipantParams) ([]SelectTournamentsByParticipantRow, error) {
	rows, err := q.db.Query(ctx, selectTournamentsByParticipant, arg.AfterID, arg.UserID, arg.PerPage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectTournamentsByParticipantRow
	for rows.Next() {
		var i SelectTournamentsByParticipantRow
		if err := rows.Scan(
			&i.ID,
			&i.TournamentKey,
			&i.Name,
			&i.Rounds,
			&i.Ruleset,
			&i.Status,
			&i.WinnerID,
			&i.Countdown,
			&i.CountdownStartedOn,
			&i.CreatedOn,
			&i.UpdatedOn,
			&i.CreatedBy,
			&i.Mode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
