// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const selectByGoogleAccountID = `-- name: SelectByGoogleAccountID :one
SELECT id, username, country
FROM users
WHERE google_account_id = $1
`

type SelectByGoogleAccountIDRow struct {
	ID       int64
	Username string
	Country  string
}

func (q *Queries) SelectByGoogleAccountID(ctx context.Context, googleaccountid pgtype.Text) (SelectByGoogleAccountIDRow, error) {
	row := q.db.QueryRow(ctx, selectByGoogleAccountID, googleaccountid)
	var i SelectByGoogleAccountIDRow
	err := row.Scan(&i.ID, &i.Username, &i.Country)
	return i, err
}

const selectEloList = `-- name: SelectEloList :many
SELECT user_id, elo
FROM user_mode_elos
WHERE user_id > $1
  AND mode = $2
ORDER BY user_id LIMIT $3
`

type SelectEloListParams struct {
	ID    int64
	Mode  ModeEnum
	Limit int32
}

type SelectEloListRow struct {
	UserID int64
	Elo    float64
}

func (q *Queries) SelectEloList(ctx context.Context, arg SelectEloListParams) ([]SelectEloListRow, error) {
	rows, err := q.db.Query(ctx, selectEloList, arg.ID, arg.Mode, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectEloListRow
	for rows.Next() {
		var i SelectEloListRow
		if err := rows.Scan(&i.UserID, &i.Elo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectExistsUsersByIDs = `-- name: SelectExistsUsersByIDs :many
SELECT id
FROM users
WHERE id = ANY ($1::bigint[])
`

func (q *Queries) SelectExistsUsersByIDs(ctx context.Context, ids []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, selectExistsUsersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectLoginByName = `-- name: SelectLoginByName :one
SELECT id, username, country, password, salt, login_attempts, last_login_attempt
FROM users
WHERE UPPER(username) = UPPER($1::TEXT)
`

type SelectLoginByNameRow struct {
	ID               int64
	Username         string
	Country          string
	Password         string
	Salt             string
	LoginAttempts    int32
	LastLoginAttempt pgtype.Timestamptz
}

func (q *Queries) SelectLoginByName(ctx context.Context, username string) (SelectLoginByNameRow, error) {
	row := q.db.QueryRow(ctx, selectLoginByName, username)
	var i SelectLoginByNameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Country,
		&i.Password,
		&i.Salt,
		&i.LoginAttempts,
		&i.LastLoginAttempt,
	)
	return i, err
}

const selectUserByID = `-- name: SelectUserByID :one
SELECT id,
       username,
       country,
       bio,
       joined_on
FROM users
WHERE id = $1
`

type SelectUserByIDRow struct {
	ID       int64
	Username string
	Country  string
	Bio      string
	JoinedOn pgtype.Timestamptz
}

func (q *Queries) SelectUserByID(ctx context.Context, id int64) (SelectUserByIDRow, error) {
	row := q.db.QueryRow(ctx, selectUserByID, id)
	var i SelectUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Country,
		&i.Bio,
		&i.JoinedOn,
	)
	return i, err
}

const selectUserElosByID = `-- name: SelectUserElosByID :many
SELECT user_id, mode, elo, highest_elo, wins, losses, draws
FROM user_mode_elos
WHERE user_id = $1
`

func (q *Queries) SelectUserElosByID(ctx context.Context, id int64) ([]UserModeElo, error) {
	rows, err := q.db.Query(ctx, selectUserElosByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserModeElo
	for rows.Next() {
		var i UserModeElo
		if err := rows.Scan(
			&i.UserID,
			&i.Mode,
			&i.Elo,
			&i.HighestElo,
			&i.Wins,
			&i.Losses,
			&i.Draws,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserElosByIDs = `-- name: SelectUserElosByIDs :many
SELECT user_id, mode, elo, highest_elo, wins, losses, draws
FROM user_mode_elos
WHERE user_id = ANY ($1::bigint[])
`

func (q *Queries) SelectUserElosByIDs(ctx context.Context, id []int64) ([]UserModeElo, error) {
	rows, err := q.db.Query(ctx, selectUserElosByIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserModeElo
	for rows.Next() {
		var i UserModeElo
		if err := rows.Scan(
			&i.UserID,
			&i.Mode,
			&i.Elo,
			&i.HighestElo,
			&i.Wins,
			&i.Losses,
			&i.Draws,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserIDsByNames = `-- name: SelectUserIDsByNames :many
SELECT id, username
FROM users
WHERE username = ANY ($1::text[])
`

type SelectUserIDsByNamesRow struct {
	ID       int64
	Username string
}

func (q *Queries) SelectUserIDsByNames(ctx context.Context, usernames []string) ([]SelectUserIDsByNamesRow, error) {
	rows, err := q.db.Query(ctx, selectUserIDsByNames, usernames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectUserIDsByNamesRow
	for rows.Next() {
		var i SelectUserIDsByNamesRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserModeElosByIDs = `-- name: SelectUserModeElosByIDs :many
SELECT user_id, elo, highest_elo, wins, losses, draws
FROM user_mode_elos
WHERE user_id = ANY ($1::bigint[])
  AND mode = $2
`

type SelectUserModeElosByIDsParams struct {
	ID   []int64
	Mode ModeEnum
}

type SelectUserModeElosByIDsRow struct {
	UserID     int64
	Elo        float64
	HighestElo float64
	Wins       int32
	Losses     int32
	Draws      int32
}

func (q *Queries) SelectUserModeElosByIDs(ctx context.Context, arg SelectUserModeElosByIDsParams) ([]SelectUserModeElosByIDsRow, error) {
	rows, err := q.db.Query(ctx, selectUserModeElosByIDs, arg.ID, arg.Mode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectUserModeElosByIDsRow
	for rows.Next() {
		var i SelectUserModeElosByIDsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Elo,
			&i.HighestElo,
			&i.Wins,
			&i.Losses,
			&i.Draws,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserWithEloByID = `-- name: SelectUserWithEloByID :one
SELECT u.id,
       u.username,
       u.country,
       u.bio,
       u.joined_on,
       e.elo,
       e.highest_elo,
       e.wins,
       e.losses,
       e.draws
FROM users u
         LEFT JOIN user_mode_elos e
                   ON u.id = e.user_id AND e.mode = $1
WHERE id = $2
`

type SelectUserWithEloByIDParams struct {
	Mode ModeEnum
	ID   int64
}

type SelectUserWithEloByIDRow struct {
	ID         int64
	Username   string
	Country    string
	Bio        string
	JoinedOn   pgtype.Timestamptz
	Elo        pgtype.Float8
	HighestElo pgtype.Float8
	Wins       pgtype.Int4
	Losses     pgtype.Int4
	Draws      pgtype.Int4
}

func (q *Queries) SelectUserWithEloByID(ctx context.Context, arg SelectUserWithEloByIDParams) (SelectUserWithEloByIDRow, error) {
	row := q.db.QueryRow(ctx, selectUserWithEloByID, arg.Mode, arg.ID)
	var i SelectUserWithEloByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Country,
		&i.Bio,
		&i.JoinedOn,
		&i.Elo,
		&i.HighestElo,
		&i.Wins,
		&i.Losses,
		&i.Draws,
	)
	return i, err
}

const selectUserWithEloByIDs = `-- name: SelectUserWithEloByIDs :many
SELECT u.id,
       u.username,
       u.country,
       u.bio,
       u.joined_on,
       e.elo,
       e.highest_elo,
       e.wins,
       e.losses,
       e.draws
FROM users u
         LEFT JOIN user_mode_elos e
                   ON u.id = e.user_id AND e.mode = $1
WHERE id = ANY ($2::bigint[])
`

type SelectUserWithEloByIDsParams struct {
	Mode ModeEnum
	Ids  []int64
}

type SelectUserWithEloByIDsRow struct {
	ID         int64
	Username   string
	Country    string
	Bio        string
	JoinedOn   pgtype.Timestamptz
	Elo        pgtype.Float8
	HighestElo pgtype.Float8
	Wins       pgtype.Int4
	Losses     pgtype.Int4
	Draws      pgtype.Int4
}

func (q *Queries) SelectUserWithEloByIDs(ctx context.Context, arg SelectUserWithEloByIDsParams) ([]SelectUserWithEloByIDsRow, error) {
	rows, err := q.db.Query(ctx, selectUserWithEloByIDs, arg.Mode, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectUserWithEloByIDsRow
	for rows.Next() {
		var i SelectUserWithEloByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Country,
			&i.Bio,
			&i.JoinedOn,
			&i.Elo,
			&i.HighestElo,
			&i.Wins,
			&i.Losses,
			&i.Draws,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUsersByIDs = `-- name: SelectUsersByIDs :many
SELECT id, username, country
FROM users
WHERE id = ANY ($1::bigint[])
`

type SelectUsersByIDsRow struct {
	ID       int64
	Username string
	Country  string
}

func (q *Queries) SelectUsersByIDs(ctx context.Context, id []int64) ([]SelectUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, selectUsersByIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectUsersByIDsRow
	for rows.Next() {
		var i SelectUsersByIDsRow
		if err := rows.Scan(&i.ID, &i.Username, &i.Country); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUsersBySimilarity = `-- name: SelectUsersBySimilarity :many
SELECT id,
       username,
       country,
       (username <-> $1) ::BIGINT AS rank
FROM users
WHERE username % $1::TEXT
ORDER BY rank DESC
    LIMIT $3
OFFSET $2
`

type SelectUsersBySimilarityParams struct {
	Username string
	Offset   int32
	Limit    int32
}

type SelectUsersBySimilarityRow struct {
	ID       int64
	Username string
	Country  string
	Rank     int64
}

func (q *Queries) SelectUsersBySimilarity(ctx context.Context, arg SelectUsersBySimilarityParams) ([]SelectUsersBySimilarityRow, error) {
	rows, err := q.db.Query(ctx, selectUsersBySimilarity, arg.Username, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectUsersBySimilarityRow
	for rows.Next() {
		var i SelectUsersBySimilarityRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Country,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
