syntax = "proto3";
option go_package = "hexchess-svc/pb";

package messages;

message PlayerState {
  int64 id = 1;
  string name = 2;
  string country = 3;
  double elo = 4;
  bool isGuest = 5;
}

message PieceMove {
  int32 piece = 1;
  int32 fromFile = 2;
  int32 fromRank = 3;
  int32 toFile = 4;
  int32 toRank = 5;
}

message PieceMoves {
  int32 piece = 1;
  int32 fromFile = 2;
  int32 fromRank = 3;
  repeated int64 moves = 4;
}

message BoardFile {
  repeated uint32 pieces = 1;
}

message ChessBoard {
  bool is_white_turn = 1;
  repeated BoardFile file = 2;
}

message HistMove {
  int32 piece = 1;
  int32 fromFile = 2;
  int32 fromRank = 3;
  int32 toFile = 4;
  int32 toRank = 5;
  bool collFile = 6;
  bool collRank = 7;
  bool  isTake = 8;
  bool  isCheck = 9;
}

message ChessGame {
  ChessBoard board = 1;
  repeated PieceMoves white_moves = 2;
  repeated PieceMoves black_moves = 3;
  repeated int32 taken_white_pieces = 4;
  repeated int32 taken_black_pieces = 5;
  repeated HistMove moves = 6;
}

message ChessState {
  string id = 1;
  ChessGame game = 2;
  PlayerState white_player = 4;
  PlayerState black_player = 5;
  bool is_ended = 6;
  string first_color = 7;
  string time_control = 8;
  int64 touch = 9;
  ChessBoard initial_board = 10;
}

message ForfeitInput {}

message Move {
  int32 promotion = 1;
  int32 fromFile = 2;
  int32 fromRank = 3;
  int32 toFile = 4;
  int32 toRank = 5;
}

message MoveInput {
  Move move = 1;
}

message ChatInput {
  string message = 1;
}

message GameInput {
  oneof value {
    ForfeitInput forfeit = 1;
    MoveInput move = 2;
    ChatInput chat = 3;
  }
}

message ErrorOutput {
  string message = 1;
}

message InitOutput {
  ChessState state = 1;
  PlayerState self = 2;
}

message PlayersOutput {
  PlayerState white_player = 1;
  PlayerState black_player = 2;
}

message MoveOutput {
  HistMove move = 1;
  ChessGame game = 2;
  string updated_at = 3;
}

message ChatOutput {
  PlayerState player = 1;
  string message = 2;
}

message ForfeitOutput {}

message GameOutputID {
  string game_id = 1;
  string message_id = 2;
}

message GameOutput {
  string game_id = 1;
  string message_id = 2;
  oneof value {
    ErrorOutput error = 3;
    InitOutput init = 4;
    PlayersOutput players = 5;
    MoveOutput move = 6;
    ChatOutput chat = 7;
    ForfeitOutput forfeit = 8;
  }
}

message HistMoves {
  repeated HistMove moves = 1;
}

message MoveHistory {
  ChessGame initial_game = 1;
  repeated MoveStep steps = 2;
}

message MoveStep {
  HistMove move = 1;
  ChessGame game = 3;
}

message MoveReplay {
  ChessGame initial_game = 1;
  repeated NotMoveStep steps = 2;
}

message NotMoveStep {
  string notMove = 1;
  PieceMove pm = 2;
  ChessGame game = 3;
}

message MakeMoveInput {
  Move move = 1;
  ChessGame game = 2;
}

message UserMsg {
  string user_id = 1;
  oneof value {
    ChallengeMsg challenge = 2;
  }
}

message ChallengeMsg {
  int64 challenger_id = 1;
  string challenger_name = 2;
  string challenger_country = 3;
  double challenger_elo = 4;
  int64 challengee_id = 5;
  string challengee_name = 6;
  string challengee_country = 7;
  double challengee_elo = 8;
  string time_control = 9;
  string start_color = 10;
  string made_on = 11;
}

message EloHistory {
  string timestamp = 1;
  double elo = 2;
}

message EloHistories {
  repeated EloHistory histories = 1;
}