// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pb/messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Elo           float64                `protobuf:"fixed64,4,opt,name=elo,proto3" json:"elo,omitempty"`
	IsGuest       bool                   `protobuf:"varint,5,opt,name=isGuest,proto3" json:"isGuest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_pb_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerState) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerState) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *PlayerState) GetElo() float64 {
	if x != nil {
		return x.Elo
	}
	return 0
}

func (x *PlayerState) GetIsGuest() bool {
	if x != nil {
		return x.IsGuest
	}
	return false
}

type PieceMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piece         int32                  `protobuf:"varint,1,opt,name=piece,proto3" json:"piece,omitempty"`
	FromFile      int32                  `protobuf:"varint,2,opt,name=fromFile,proto3" json:"fromFile,omitempty"`
	FromRank      int32                  `protobuf:"varint,3,opt,name=fromRank,proto3" json:"fromRank,omitempty"`
	ToFile        int32                  `protobuf:"varint,4,opt,name=toFile,proto3" json:"toFile,omitempty"`
	ToRank        int32                  `protobuf:"varint,5,opt,name=toRank,proto3" json:"toRank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PieceMove) Reset() {
	*x = PieceMove{}
	mi := &file_pb_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PieceMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PieceMove) ProtoMessage() {}

func (x *PieceMove) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PieceMove.ProtoReflect.Descriptor instead.
func (*PieceMove) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{1}
}

func (x *PieceMove) GetPiece() int32 {
	if x != nil {
		return x.Piece
	}
	return 0
}

func (x *PieceMove) GetFromFile() int32 {
	if x != nil {
		return x.FromFile
	}
	return 0
}

func (x *PieceMove) GetFromRank() int32 {
	if x != nil {
		return x.FromRank
	}
	return 0
}

func (x *PieceMove) GetToFile() int32 {
	if x != nil {
		return x.ToFile
	}
	return 0
}

func (x *PieceMove) GetToRank() int32 {
	if x != nil {
		return x.ToRank
	}
	return 0
}

type PieceMoves struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piece         int32                  `protobuf:"varint,1,opt,name=piece,proto3" json:"piece,omitempty"`
	FromFile      int32                  `protobuf:"varint,2,opt,name=fromFile,proto3" json:"fromFile,omitempty"`
	FromRank      int32                  `protobuf:"varint,3,opt,name=fromRank,proto3" json:"fromRank,omitempty"`
	Moves         []int64                `protobuf:"varint,4,rep,packed,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PieceMoves) Reset() {
	*x = PieceMoves{}
	mi := &file_pb_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PieceMoves) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PieceMoves) ProtoMessage() {}

func (x *PieceMoves) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PieceMoves.ProtoReflect.Descriptor instead.
func (*PieceMoves) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{2}
}

func (x *PieceMoves) GetPiece() int32 {
	if x != nil {
		return x.Piece
	}
	return 0
}

func (x *PieceMoves) GetFromFile() int32 {
	if x != nil {
		return x.FromFile
	}
	return 0
}

func (x *PieceMoves) GetFromRank() int32 {
	if x != nil {
		return x.FromRank
	}
	return 0
}

func (x *PieceMoves) GetMoves() []int64 {
	if x != nil {
		return x.Moves
	}
	return nil
}

type BoardFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pieces        []uint32               `protobuf:"varint,1,rep,packed,name=pieces,proto3" json:"pieces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardFile) Reset() {
	*x = BoardFile{}
	mi := &file_pb_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardFile) ProtoMessage() {}

func (x *BoardFile) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardFile.ProtoReflect.Descriptor instead.
func (*BoardFile) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{3}
}

func (x *BoardFile) GetPieces() []uint32 {
	if x != nil {
		return x.Pieces
	}
	return nil
}

type ChessBoard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsWhiteTurn   bool                   `protobuf:"varint,1,opt,name=is_white_turn,json=isWhiteTurn,proto3" json:"is_white_turn,omitempty"`
	File          []*BoardFile           `protobuf:"bytes,2,rep,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChessBoard) Reset() {
	*x = ChessBoard{}
	mi := &file_pb_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChessBoard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChessBoard) ProtoMessage() {}

func (x *ChessBoard) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChessBoard.ProtoReflect.Descriptor instead.
func (*ChessBoard) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ChessBoard) GetIsWhiteTurn() bool {
	if x != nil {
		return x.IsWhiteTurn
	}
	return false
}

func (x *ChessBoard) GetFile() []*BoardFile {
	if x != nil {
		return x.File
	}
	return nil
}

type ChessGame struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Board            *ChessBoard            `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	WhiteMoves       []*PieceMoves          `protobuf:"bytes,2,rep,name=white_moves,json=whiteMoves,proto3" json:"white_moves,omitempty"`
	BlackMoves       []*PieceMoves          `protobuf:"bytes,3,rep,name=black_moves,json=blackMoves,proto3" json:"black_moves,omitempty"`
	TakenWhitePieces []int32                `protobuf:"varint,4,rep,packed,name=taken_white_pieces,json=takenWhitePieces,proto3" json:"taken_white_pieces,omitempty"`
	TakenBlackPieces []int32                `protobuf:"varint,5,rep,packed,name=taken_black_pieces,json=takenBlackPieces,proto3" json:"taken_black_pieces,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChessGame) Reset() {
	*x = ChessGame{}
	mi := &file_pb_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChessGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChessGame) ProtoMessage() {}

func (x *ChessGame) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChessGame.ProtoReflect.Descriptor instead.
func (*ChessGame) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ChessGame) GetBoard() *ChessBoard {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *ChessGame) GetWhiteMoves() []*PieceMoves {
	if x != nil {
		return x.WhiteMoves
	}
	return nil
}

func (x *ChessGame) GetBlackMoves() []*PieceMoves {
	if x != nil {
		return x.BlackMoves
	}
	return nil
}

func (x *ChessGame) GetTakenWhitePieces() []int32 {
	if x != nil {
		return x.TakenWhitePieces
	}
	return nil
}

func (x *ChessGame) GetTakenBlackPieces() []int32 {
	if x != nil {
		return x.TakenBlackPieces
	}
	return nil
}

type ChessState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Game          *ChessGame             `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	MoveList      []*PieceMove           `protobuf:"bytes,3,rep,name=move_list,json=moveList,proto3" json:"move_list,omitempty"`
	WhitePlayer   *PlayerState           `protobuf:"bytes,4,opt,name=white_player,json=whitePlayer,proto3" json:"white_player,omitempty"`
	BlackPlayer   *PlayerState           `protobuf:"bytes,5,opt,name=black_player,json=blackPlayer,proto3" json:"black_player,omitempty"`
	IsEnded       bool                   `protobuf:"varint,6,opt,name=is_ended,json=isEnded,proto3" json:"is_ended,omitempty"`
	FirstColor    uint32                 `protobuf:"varint,7,opt,name=first_color,json=firstColor,proto3" json:"first_color,omitempty"`
	TimeControl   uint32                 `protobuf:"varint,8,opt,name=time_control,json=timeControl,proto3" json:"time_control,omitempty"`
	Touch         int64                  `protobuf:"varint,9,opt,name=touch,proto3" json:"touch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChessState) Reset() {
	*x = ChessState{}
	mi := &file_pb_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChessState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChessState) ProtoMessage() {}

func (x *ChessState) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChessState.ProtoReflect.Descriptor instead.
func (*ChessState) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ChessState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChessState) GetGame() *ChessGame {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *ChessState) GetMoveList() []*PieceMove {
	if x != nil {
		return x.MoveList
	}
	return nil
}

func (x *ChessState) GetWhitePlayer() *PlayerState {
	if x != nil {
		return x.WhitePlayer
	}
	return nil
}

func (x *ChessState) GetBlackPlayer() *PlayerState {
	if x != nil {
		return x.BlackPlayer
	}
	return nil
}

func (x *ChessState) GetIsEnded() bool {
	if x != nil {
		return x.IsEnded
	}
	return false
}

func (x *ChessState) GetFirstColor() uint32 {
	if x != nil {
		return x.FirstColor
	}
	return 0
}

func (x *ChessState) GetTimeControl() uint32 {
	if x != nil {
		return x.TimeControl
	}
	return 0
}

func (x *ChessState) GetTouch() int64 {
	if x != nil {
		return x.Touch
	}
	return 0
}

type ForfeitInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForfeitInput) Reset() {
	*x = ForfeitInput{}
	mi := &file_pb_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForfeitInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForfeitInput) ProtoMessage() {}

func (x *ForfeitInput) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForfeitInput.ProtoReflect.Descriptor instead.
func (*ForfeitInput) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{7}
}

type MoveInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Move          *PieceMove             `protobuf:"bytes,1,opt,name=move,proto3" json:"move,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveInput) Reset() {
	*x = MoveInput{}
	mi := &file_pb_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveInput) ProtoMessage() {}

func (x *MoveInput) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveInput.ProtoReflect.Descriptor instead.
func (*MoveInput) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{8}
}

func (x *MoveInput) GetMove() *PieceMove {
	if x != nil {
		return x.Move
	}
	return nil
}

type ChatInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatInput) Reset() {
	*x = ChatInput{}
	mi := &file_pb_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatInput) ProtoMessage() {}

func (x *ChatInput) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatInput.ProtoReflect.Descriptor instead.
func (*ChatInput) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ChatInput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GameInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*GameInput_Forfeit
	//	*GameInput_Move
	//	*GameInput_Chat
	Value         isGameInput_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameInput) Reset() {
	*x = GameInput{}
	mi := &file_pb_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInput) ProtoMessage() {}

func (x *GameInput) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInput.ProtoReflect.Descriptor instead.
func (*GameInput) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{10}
}

func (x *GameInput) GetValue() isGameInput_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GameInput) GetForfeit() *ForfeitInput {
	if x != nil {
		if x, ok := x.Value.(*GameInput_Forfeit); ok {
			return x.Forfeit
		}
	}
	return nil
}

func (x *GameInput) GetMove() *MoveInput {
	if x != nil {
		if x, ok := x.Value.(*GameInput_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *GameInput) GetChat() *ChatInput {
	if x != nil {
		if x, ok := x.Value.(*GameInput_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

type isGameInput_Value interface {
	isGameInput_Value()
}

type GameInput_Forfeit struct {
	Forfeit *ForfeitInput `protobuf:"bytes,1,opt,name=forfeit,proto3,oneof"`
}

type GameInput_Move struct {
	Move *MoveInput `protobuf:"bytes,2,opt,name=move,proto3,oneof"`
}

type GameInput_Chat struct {
	Chat *ChatInput `protobuf:"bytes,3,opt,name=chat,proto3,oneof"`
}

func (*GameInput_Forfeit) isGameInput_Value() {}

func (*GameInput_Move) isGameInput_Value() {}

func (*GameInput_Chat) isGameInput_Value() {}

type ErrorOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorOutput) Reset() {
	*x = ErrorOutput{}
	mi := &file_pb_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorOutput) ProtoMessage() {}

func (x *ErrorOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorOutput.ProtoReflect.Descriptor instead.
func (*ErrorOutput) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ErrorOutput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InitOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *ChessState            `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Self          *PlayerState           `protobuf:"bytes,2,opt,name=self,proto3" json:"self,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitOutput) Reset() {
	*x = InitOutput{}
	mi := &file_pb_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitOutput) ProtoMessage() {}

func (x *InitOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitOutput.ProtoReflect.Descriptor instead.
func (*InitOutput) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{12}
}

func (x *InitOutput) GetState() *ChessState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *InitOutput) GetSelf() *PlayerState {
	if x != nil {
		return x.Self
	}
	return nil
}

type PlayersOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WhitePlayer   *PlayerState           `protobuf:"bytes,1,opt,name=white_player,json=whitePlayer,proto3" json:"white_player,omitempty"`
	BlackPlayer   *PlayerState           `protobuf:"bytes,2,opt,name=black_player,json=blackPlayer,proto3" json:"black_player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayersOutput) Reset() {
	*x = PlayersOutput{}
	mi := &file_pb_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayersOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayersOutput) ProtoMessage() {}

func (x *PlayersOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayersOutput.ProtoReflect.Descriptor instead.
func (*PlayersOutput) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{13}
}

func (x *PlayersOutput) GetWhitePlayer() *PlayerState {
	if x != nil {
		return x.WhitePlayer
	}
	return nil
}

func (x *PlayersOutput) GetBlackPlayer() *PlayerState {
	if x != nil {
		return x.BlackPlayer
	}
	return nil
}

type MoveOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PieceMove     *PieceMove             `protobuf:"bytes,1,opt,name=pieceMove,proto3" json:"pieceMove,omitempty"`
	Game          *ChessGame             `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveOutput) Reset() {
	*x = MoveOutput{}
	mi := &file_pb_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveOutput) ProtoMessage() {}

func (x *MoveOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveOutput.ProtoReflect.Descriptor instead.
func (*MoveOutput) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{14}
}

func (x *MoveOutput) GetPieceMove() *PieceMove {
	if x != nil {
		return x.PieceMove
	}
	return nil
}

func (x *MoveOutput) GetGame() *ChessGame {
	if x != nil {
		return x.Game
	}
	return nil
}

type ChatOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerState           `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatOutput) Reset() {
	*x = ChatOutput{}
	mi := &file_pb_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatOutput) ProtoMessage() {}

func (x *ChatOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatOutput.ProtoReflect.Descriptor instead.
func (*ChatOutput) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{15}
}

func (x *ChatOutput) GetPlayer() *PlayerState {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *ChatOutput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ForfeitOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForfeitOutput) Reset() {
	*x = ForfeitOutput{}
	mi := &file_pb_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForfeitOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForfeitOutput) ProtoMessage() {}

func (x *ForfeitOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForfeitOutput.ProtoReflect.Descriptor instead.
func (*ForfeitOutput) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{16}
}

type GameOutputID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameOutputID) Reset() {
	*x = GameOutputID{}
	mi := &file_pb_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameOutputID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOutputID) ProtoMessage() {}

func (x *GameOutputID) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOutputID.ProtoReflect.Descriptor instead.
func (*GameOutputID) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{17}
}

func (x *GameOutputID) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameOutputID) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type GameOutput struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	GameId    string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	MessageId string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*GameOutput_Error
	//	*GameOutput_Init
	//	*GameOutput_Players
	//	*GameOutput_Move
	//	*GameOutput_Chat
	//	*GameOutput_Forfeit
	Value         isGameOutput_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameOutput) Reset() {
	*x = GameOutput{}
	mi := &file_pb_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOutput) ProtoMessage() {}

func (x *GameOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOutput.ProtoReflect.Descriptor instead.
func (*GameOutput) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{18}
}

func (x *GameOutput) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameOutput) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GameOutput) GetValue() isGameOutput_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GameOutput) GetError() *ErrorOutput {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *GameOutput) GetInit() *InitOutput {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *GameOutput) GetPlayers() *PlayersOutput {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Players); ok {
			return x.Players
		}
	}
	return nil
}

func (x *GameOutput) GetMove() *MoveOutput {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *GameOutput) GetChat() *ChatOutput {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *GameOutput) GetForfeit() *ForfeitOutput {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Forfeit); ok {
			return x.Forfeit
		}
	}
	return nil
}

type isGameOutput_Value interface {
	isGameOutput_Value()
}

type GameOutput_Error struct {
	Error *ErrorOutput `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type GameOutput_Init struct {
	Init *InitOutput `protobuf:"bytes,4,opt,name=init,proto3,oneof"`
}

type GameOutput_Players struct {
	Players *PlayersOutput `protobuf:"bytes,5,opt,name=players,proto3,oneof"`
}

type GameOutput_Move struct {
	Move *MoveOutput `protobuf:"bytes,6,opt,name=move,proto3,oneof"`
}

type GameOutput_Chat struct {
	Chat *ChatOutput `protobuf:"bytes,7,opt,name=chat,proto3,oneof"`
}

type GameOutput_Forfeit struct {
	Forfeit *ForfeitOutput `protobuf:"bytes,8,opt,name=forfeit,proto3,oneof"`
}

func (*GameOutput_Error) isGameOutput_Value() {}

func (*GameOutput_Init) isGameOutput_Value() {}

func (*GameOutput_Players) isGameOutput_Value() {}

func (*GameOutput_Move) isGameOutput_Value() {}

func (*GameOutput_Chat) isGameOutput_Value() {}

func (*GameOutput_Forfeit) isGameOutput_Value() {}

type UserMsg struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*UserMsg_Challenge
	Value         isUserMsg_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMsg) Reset() {
	*x = UserMsg{}
	mi := &file_pb_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMsg) ProtoMessage() {}

func (x *UserMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMsg.ProtoReflect.Descriptor instead.
func (*UserMsg) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{19}
}

func (x *UserMsg) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserMsg) GetValue() isUserMsg_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *UserMsg) GetChallenge() *ChallengeMsg {
	if x != nil {
		if x, ok := x.Value.(*UserMsg_Challenge); ok {
			return x.Challenge
		}
	}
	return nil
}

type isUserMsg_Value interface {
	isUserMsg_Value()
}

type UserMsg_Challenge struct {
	Challenge *ChallengeMsg `protobuf:"bytes,2,opt,name=challenge,proto3,oneof"`
}

func (*UserMsg_Challenge) isUserMsg_Value() {}

type ChallengeMsg struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChallengerId      int64                  `protobuf:"varint,1,opt,name=challenger_id,json=challengerId,proto3" json:"challenger_id,omitempty"`
	ChallengerName    string                 `protobuf:"bytes,2,opt,name=challenger_name,json=challengerName,proto3" json:"challenger_name,omitempty"`
	ChallengerCountry string                 `protobuf:"bytes,3,opt,name=challenger_country,json=challengerCountry,proto3" json:"challenger_country,omitempty"`
	ChallengerElo     float64                `protobuf:"fixed64,4,opt,name=challenger_elo,json=challengerElo,proto3" json:"challenger_elo,omitempty"`
	ChallengeeId      int64                  `protobuf:"varint,5,opt,name=challengee_id,json=challengeeId,proto3" json:"challengee_id,omitempty"`
	ChallengeeName    string                 `protobuf:"bytes,6,opt,name=challengee_name,json=challengeeName,proto3" json:"challengee_name,omitempty"`
	ChallengeeCountry string                 `protobuf:"bytes,7,opt,name=challengee_country,json=challengeeCountry,proto3" json:"challengee_country,omitempty"`
	ChallengeeElo     float64                `protobuf:"fixed64,8,opt,name=challengee_elo,json=challengeeElo,proto3" json:"challengee_elo,omitempty"`
	TimeControl       uint32                 `protobuf:"varint,9,opt,name=time_control,json=timeControl,proto3" json:"time_control,omitempty"`
	StartColor        uint32                 `protobuf:"varint,10,opt,name=start_color,json=startColor,proto3" json:"start_color,omitempty"`
	MadeOn            int64                  `protobuf:"varint,11,opt,name=made_on,json=madeOn,proto3" json:"made_on,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChallengeMsg) Reset() {
	*x = ChallengeMsg{}
	mi := &file_pb_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeMsg) ProtoMessage() {}

func (x *ChallengeMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeMsg.ProtoReflect.Descriptor instead.
func (*ChallengeMsg) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{20}
}

func (x *ChallengeMsg) GetChallengerId() int64 {
	if x != nil {
		return x.ChallengerId
	}
	return 0
}

func (x *ChallengeMsg) GetChallengerName() string {
	if x != nil {
		return x.ChallengerName
	}
	return ""
}

func (x *ChallengeMsg) GetChallengerCountry() string {
	if x != nil {
		return x.ChallengerCountry
	}
	return ""
}

func (x *ChallengeMsg) GetChallengerElo() float64 {
	if x != nil {
		return x.ChallengerElo
	}
	return 0
}

func (x *ChallengeMsg) GetChallengeeId() int64 {
	if x != nil {
		return x.ChallengeeId
	}
	return 0
}

func (x *ChallengeMsg) GetChallengeeName() string {
	if x != nil {
		return x.ChallengeeName
	}
	return ""
}

func (x *ChallengeMsg) GetChallengeeCountry() string {
	if x != nil {
		return x.ChallengeeCountry
	}
	return ""
}

func (x *ChallengeMsg) GetChallengeeElo() float64 {
	if x != nil {
		return x.ChallengeeElo
	}
	return 0
}

func (x *ChallengeMsg) GetTimeControl() uint32 {
	if x != nil {
		return x.TimeControl
	}
	return 0
}

func (x *ChallengeMsg) GetStartColor() uint32 {
	if x != nil {
		return x.StartColor
	}
	return 0
}

func (x *ChallengeMsg) GetMadeOn() int64 {
	if x != nil {
		return x.MadeOn
	}
	return 0
}

var File_pb_messages_proto protoreflect.FileDescriptor

const file_pb_messages_proto_rawDesc = "" +
	"\n" +
	"\x11pb/messages.proto\x12\bmessages\"w\n" +
	"\vPlayerState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x10\n" +
	"\x03elo\x18\x04 \x01(\x01R\x03elo\x12\x18\n" +
	"\aisGuest\x18\x05 \x01(\bR\aisGuest\"\x89\x01\n" +
	"\tPieceMove\x12\x14\n" +
	"\x05piece\x18\x01 \x01(\x05R\x05piece\x12\x1a\n" +
	"\bfromFile\x18\x02 \x01(\x05R\bfromFile\x12\x1a\n" +
	"\bfromRank\x18\x03 \x01(\x05R\bfromRank\x12\x16\n" +
	"\x06toFile\x18\x04 \x01(\x05R\x06toFile\x12\x16\n" +
	"\x06toRank\x18\x05 \x01(\x05R\x06toRank\"p\n" +
	"\n" +
	"PieceMoves\x12\x14\n" +
	"\x05piece\x18\x01 \x01(\x05R\x05piece\x12\x1a\n" +
	"\bfromFile\x18\x02 \x01(\x05R\bfromFile\x12\x1a\n" +
	"\bfromRank\x18\x03 \x01(\x05R\bfromRank\x12\x14\n" +
	"\x05moves\x18\x04 \x03(\x03R\x05moves\"#\n" +
	"\tBoardFile\x12\x16\n" +
	"\x06pieces\x18\x01 \x03(\rR\x06pieces\"Y\n" +
	"\n" +
	"ChessBoard\x12\"\n" +
	"\ris_white_turn\x18\x01 \x01(\bR\visWhiteTurn\x12'\n" +
	"\x04file\x18\x02 \x03(\v2\x13.messages.BoardFileR\x04file\"\x81\x02\n" +
	"\tChessGame\x12*\n" +
	"\x05board\x18\x01 \x01(\v2\x14.messages.ChessBoardR\x05board\x125\n" +
	"\vwhite_moves\x18\x02 \x03(\v2\x14.messages.PieceMovesR\n" +
	"whiteMoves\x125\n" +
	"\vblack_moves\x18\x03 \x03(\v2\x14.messages.PieceMovesR\n" +
	"blackMoves\x12,\n" +
	"\x12taken_white_pieces\x18\x04 \x03(\x05R\x10takenWhitePieces\x12,\n" +
	"\x12taken_black_pieces\x18\x05 \x03(\x05R\x10takenBlackPieces\"\xe0\x02\n" +
	"\n" +
	"ChessState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04game\x18\x02 \x01(\v2\x13.messages.ChessGameR\x04game\x120\n" +
	"\tmove_list\x18\x03 \x03(\v2\x13.messages.PieceMoveR\bmoveList\x128\n" +
	"\fwhite_player\x18\x04 \x01(\v2\x15.messages.PlayerStateR\vwhitePlayer\x128\n" +
	"\fblack_player\x18\x05 \x01(\v2\x15.messages.PlayerStateR\vblackPlayer\x12\x19\n" +
	"\bis_ended\x18\x06 \x01(\bR\aisEnded\x12\x1f\n" +
	"\vfirst_color\x18\a \x01(\rR\n" +
	"firstColor\x12!\n" +
	"\ftime_control\x18\b \x01(\rR\vtimeControl\x12\x14\n" +
	"\x05touch\x18\t \x01(\x03R\x05touch\"\x0e\n" +
	"\fForfeitInput\"4\n" +
	"\tMoveInput\x12'\n" +
	"\x04move\x18\x01 \x01(\v2\x13.messages.PieceMoveR\x04move\"%\n" +
	"\tChatInput\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x9e\x01\n" +
	"\tGameInput\x122\n" +
	"\aforfeit\x18\x01 \x01(\v2\x16.messages.ForfeitInputH\x00R\aforfeit\x12)\n" +
	"\x04move\x18\x02 \x01(\v2\x13.messages.MoveInputH\x00R\x04move\x12)\n" +
	"\x04chat\x18\x03 \x01(\v2\x13.messages.ChatInputH\x00R\x04chatB\a\n" +
	"\x05value\"'\n" +
	"\vErrorOutput\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"c\n" +
	"\n" +
	"InitOutput\x12*\n" +
	"\x05state\x18\x01 \x01(\v2\x14.messages.ChessStateR\x05state\x12)\n" +
	"\x04self\x18\x02 \x01(\v2\x15.messages.PlayerStateR\x04self\"\x83\x01\n" +
	"\rPlayersOutput\x128\n" +
	"\fwhite_player\x18\x01 \x01(\v2\x15.messages.PlayerStateR\vwhitePlayer\x128\n" +
	"\fblack_player\x18\x02 \x01(\v2\x15.messages.PlayerStateR\vblackPlayer\"h\n" +
	"\n" +
	"MoveOutput\x121\n" +
	"\tpieceMove\x18\x01 \x01(\v2\x13.messages.PieceMoveR\tpieceMove\x12'\n" +
	"\x04game\x18\x02 \x01(\v2\x13.messages.ChessGameR\x04game\"U\n" +
	"\n" +
	"ChatOutput\x12-\n" +
	"\x06player\x18\x01 \x01(\v2\x15.messages.PlayerStateR\x06player\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0f\n" +
	"\rForfeitOutput\"F\n" +
	"\fGameOutputID\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"\xea\x02\n" +
	"\n" +
	"GameOutput\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12-\n" +
	"\x05error\x18\x03 \x01(\v2\x15.messages.ErrorOutputH\x00R\x05error\x12*\n" +
	"\x04init\x18\x04 \x01(\v2\x14.messages.InitOutputH\x00R\x04init\x123\n" +
	"\aplayers\x18\x05 \x01(\v2\x17.messages.PlayersOutputH\x00R\aplayers\x12*\n" +
	"\x04move\x18\x06 \x01(\v2\x14.messages.MoveOutputH\x00R\x04move\x12*\n" +
	"\x04chat\x18\a \x01(\v2\x14.messages.ChatOutputH\x00R\x04chat\x123\n" +
	"\aforfeit\x18\b \x01(\v2\x17.messages.ForfeitOutputH\x00R\aforfeitB\a\n" +
	"\x05value\"c\n" +
	"\aUserMsg\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x126\n" +
	"\tchallenge\x18\x02 \x01(\v2\x16.messages.ChallengeMsgH\x00R\tchallengeB\a\n" +
	"\x05value\"\xb3\x03\n" +
	"\fChallengeMsg\x12#\n" +
	"\rchallenger_id\x18\x01 \x01(\x03R\fchallengerId\x12'\n" +
	"\x0fchallenger_name\x18\x02 \x01(\tR\x0echallengerName\x12-\n" +
	"\x12challenger_country\x18\x03 \x01(\tR\x11challengerCountry\x12%\n" +
	"\x0echallenger_elo\x18\x04 \x01(\x01R\rchallengerElo\x12#\n" +
	"\rchallengee_id\x18\x05 \x01(\x03R\fchallengeeId\x12'\n" +
	"\x0fchallengee_name\x18\x06 \x01(\tR\x0echallengeeName\x12-\n" +
	"\x12challengee_country\x18\a \x01(\tR\x11challengeeCountry\x12%\n" +
	"\x0echallengee_elo\x18\b \x01(\x01R\rchallengeeElo\x12!\n" +
	"\ftime_control\x18\t \x01(\rR\vtimeControl\x12\x1f\n" +
	"\vstart_color\x18\n" +
	" \x01(\rR\n" +
	"startColor\x12\x17\n" +
	"\amade_on\x18\v \x01(\x03R\x06madeOnB\x12Z\x10hexchess-data/pbb\x06proto3"

var (
	file_pb_messages_proto_rawDescOnce sync.Once
	file_pb_messages_proto_rawDescData []byte
)

func file_pb_messages_proto_rawDescGZIP() []byte {
	file_pb_messages_proto_rawDescOnce.Do(func() {
		file_pb_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_messages_proto_rawDesc), len(file_pb_messages_proto_rawDesc)))
	})
	return file_pb_messages_proto_rawDescData
}

var file_pb_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_pb_messages_proto_goTypes = []any{
	(*PlayerState)(nil),   // 0: messages.PlayerState
	(*PieceMove)(nil),     // 1: messages.PieceMove
	(*PieceMoves)(nil),    // 2: messages.PieceMoves
	(*BoardFile)(nil),     // 3: messages.BoardFile
	(*ChessBoard)(nil),    // 4: messages.ChessBoard
	(*ChessGame)(nil),     // 5: messages.ChessGame
	(*ChessState)(nil),    // 6: messages.ChessState
	(*ForfeitInput)(nil),  // 7: messages.ForfeitInput
	(*MoveInput)(nil),     // 8: messages.MoveInput
	(*ChatInput)(nil),     // 9: messages.ChatInput
	(*GameInput)(nil),     // 10: messages.GameInput
	(*ErrorOutput)(nil),   // 11: messages.ErrorOutput
	(*InitOutput)(nil),    // 12: messages.InitOutput
	(*PlayersOutput)(nil), // 13: messages.PlayersOutput
	(*MoveOutput)(nil),    // 14: messages.MoveOutput
	(*ChatOutput)(nil),    // 15: messages.ChatOutput
	(*ForfeitOutput)(nil), // 16: messages.ForfeitOutput
	(*GameOutputID)(nil),  // 17: messages.GameOutputID
	(*GameOutput)(nil),    // 18: messages.GameOutput
	(*UserMsg)(nil),       // 19: messages.UserMsg
	(*ChallengeMsg)(nil),  // 20: messages.ChallengeMsg
}
var file_pb_messages_proto_depIdxs = []int32{
	3,  // 0: messages.ChessBoard.file:type_name -> messages.BoardFile
	4,  // 1: messages.ChessGame.board:type_name -> messages.ChessBoard
	2,  // 2: messages.ChessGame.white_moves:type_name -> messages.PieceMoves
	2,  // 3: messages.ChessGame.black_moves:type_name -> messages.PieceMoves
	5,  // 4: messages.ChessState.game:type_name -> messages.ChessGame
	1,  // 5: messages.ChessState.move_list:type_name -> messages.PieceMove
	0,  // 6: messages.ChessState.white_player:type_name -> messages.PlayerState
	0,  // 7: messages.ChessState.black_player:type_name -> messages.PlayerState
	1,  // 8: messages.MoveInput.move:type_name -> messages.PieceMove
	7,  // 9: messages.GameInput.forfeit:type_name -> messages.ForfeitInput
	8,  // 10: messages.GameInput.move:type_name -> messages.MoveInput
	9,  // 11: messages.GameInput.chat:type_name -> messages.ChatInput
	6,  // 12: messages.InitOutput.state:type_name -> messages.ChessState
	0,  // 13: messages.InitOutput.self:type_name -> messages.PlayerState
	0,  // 14: messages.PlayersOutput.white_player:type_name -> messages.PlayerState
	0,  // 15: messages.PlayersOutput.black_player:type_name -> messages.PlayerState
	1,  // 16: messages.MoveOutput.pieceMove:type_name -> messages.PieceMove
	5,  // 17: messages.MoveOutput.game:type_name -> messages.ChessGame
	0,  // 18: messages.ChatOutput.player:type_name -> messages.PlayerState
	11, // 19: messages.GameOutput.error:type_name -> messages.ErrorOutput
	12, // 20: messages.GameOutput.init:type_name -> messages.InitOutput
	13, // 21: messages.GameOutput.players:type_name -> messages.PlayersOutput
	14, // 22: messages.GameOutput.move:type_name -> messages.MoveOutput
	15, // 23: messages.GameOutput.chat:type_name -> messages.ChatOutput
	16, // 24: messages.GameOutput.forfeit:type_name -> messages.ForfeitOutput
	20, // 25: messages.UserMsg.challenge:type_name -> messages.ChallengeMsg
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_pb_messages_proto_init() }
func file_pb_messages_proto_init() {
	if File_pb_messages_proto != nil {
		return
	}
	file_pb_messages_proto_msgTypes[10].OneofWrappers = []any{
		(*GameInput_Forfeit)(nil),
		(*GameInput_Move)(nil),
		(*GameInput_Chat)(nil),
	}
	file_pb_messages_proto_msgTypes[18].OneofWrappers = []any{
		(*GameOutput_Error)(nil),
		(*GameOutput_Init)(nil),
		(*GameOutput_Players)(nil),
		(*GameOutput_Move)(nil),
		(*GameOutput_Chat)(nil),
		(*GameOutput_Forfeit)(nil),
	}
	file_pb_messages_proto_msgTypes[19].OneofWrappers = []any{
		(*UserMsg_Challenge)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_messages_proto_rawDesc), len(file_pb_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_messages_proto_goTypes,
		DependencyIndexes: file_pb_messages_proto_depIdxs,
		MessageInfos:      file_pb_messages_proto_msgTypes,
	}.Build()
	File_pb_messages_proto = out.File
	file_pb_messages_proto_goTypes = nil
	file_pb_messages_proto_depIdxs = nil
}
