// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Elo           float64                `protobuf:"fixed64,4,opt,name=elo,proto3" json:"elo,omitempty"`
	IsGuest       bool                   `protobuf:"varint,5,opt,name=isGuest,proto3" json:"isGuest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerState) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerState) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *PlayerState) GetElo() float64 {
	if x != nil {
		return x.Elo
	}
	return 0
}

func (x *PlayerState) GetIsGuest() bool {
	if x != nil {
		return x.IsGuest
	}
	return false
}

type PieceMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piece         int32                  `protobuf:"varint,1,opt,name=piece,proto3" json:"piece,omitempty"`
	FromFile      int32                  `protobuf:"varint,2,opt,name=fromFile,proto3" json:"fromFile,omitempty"`
	FromRank      int32                  `protobuf:"varint,3,opt,name=fromRank,proto3" json:"fromRank,omitempty"`
	ToFile        int32                  `protobuf:"varint,4,opt,name=toFile,proto3" json:"toFile,omitempty"`
	ToRank        int32                  `protobuf:"varint,5,opt,name=toRank,proto3" json:"toRank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PieceMove) Reset() {
	*x = PieceMove{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PieceMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PieceMove) ProtoMessage() {}

func (x *PieceMove) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PieceMove.ProtoReflect.Descriptor instead.
func (*PieceMove) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *PieceMove) GetPiece() int32 {
	if x != nil {
		return x.Piece
	}
	return 0
}

func (x *PieceMove) GetFromFile() int32 {
	if x != nil {
		return x.FromFile
	}
	return 0
}

func (x *PieceMove) GetFromRank() int32 {
	if x != nil {
		return x.FromRank
	}
	return 0
}

func (x *PieceMove) GetToFile() int32 {
	if x != nil {
		return x.ToFile
	}
	return 0
}

func (x *PieceMove) GetToRank() int32 {
	if x != nil {
		return x.ToRank
	}
	return 0
}

type PieceMoves struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piece         int32                  `protobuf:"varint,1,opt,name=piece,proto3" json:"piece,omitempty"`
	FromFile      int32                  `protobuf:"varint,2,opt,name=fromFile,proto3" json:"fromFile,omitempty"`
	FromRank      int32                  `protobuf:"varint,3,opt,name=fromRank,proto3" json:"fromRank,omitempty"`
	Moves         []int64                `protobuf:"varint,4,rep,packed,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PieceMoves) Reset() {
	*x = PieceMoves{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PieceMoves) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PieceMoves) ProtoMessage() {}

func (x *PieceMoves) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PieceMoves.ProtoReflect.Descriptor instead.
func (*PieceMoves) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *PieceMoves) GetPiece() int32 {
	if x != nil {
		return x.Piece
	}
	return 0
}

func (x *PieceMoves) GetFromFile() int32 {
	if x != nil {
		return x.FromFile
	}
	return 0
}

func (x *PieceMoves) GetFromRank() int32 {
	if x != nil {
		return x.FromRank
	}
	return 0
}

func (x *PieceMoves) GetMoves() []int64 {
	if x != nil {
		return x.Moves
	}
	return nil
}

type BoardFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pieces        []uint32               `protobuf:"varint,1,rep,packed,name=pieces,proto3" json:"pieces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardFile) Reset() {
	*x = BoardFile{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardFile) ProtoMessage() {}

func (x *BoardFile) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardFile.ProtoReflect.Descriptor instead.
func (*BoardFile) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *BoardFile) GetPieces() []uint32 {
	if x != nil {
		return x.Pieces
	}
	return nil
}

type ChessBoard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsWhiteTurn   bool                   `protobuf:"varint,1,opt,name=is_white_turn,json=isWhiteTurn,proto3" json:"is_white_turn,omitempty"`
	File          []*BoardFile           `protobuf:"bytes,2,rep,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChessBoard) Reset() {
	*x = ChessBoard{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChessBoard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChessBoard) ProtoMessage() {}

func (x *ChessBoard) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChessBoard.ProtoReflect.Descriptor instead.
func (*ChessBoard) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ChessBoard) GetIsWhiteTurn() bool {
	if x != nil {
		return x.IsWhiteTurn
	}
	return false
}

func (x *ChessBoard) GetFile() []*BoardFile {
	if x != nil {
		return x.File
	}
	return nil
}

type HistMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piece         int32                  `protobuf:"varint,1,opt,name=piece,proto3" json:"piece,omitempty"`
	FromFile      int32                  `protobuf:"varint,2,opt,name=fromFile,proto3" json:"fromFile,omitempty"`
	FromRank      int32                  `protobuf:"varint,3,opt,name=fromRank,proto3" json:"fromRank,omitempty"`
	ToFile        int32                  `protobuf:"varint,4,opt,name=toFile,proto3" json:"toFile,omitempty"`
	ToRank        int32                  `protobuf:"varint,5,opt,name=toRank,proto3" json:"toRank,omitempty"`
	CollFile      bool                   `protobuf:"varint,6,opt,name=collFile,proto3" json:"collFile,omitempty"`
	CollRank      bool                   `protobuf:"varint,7,opt,name=collRank,proto3" json:"collRank,omitempty"`
	IsTake        bool                   `protobuf:"varint,8,opt,name=isTake,proto3" json:"isTake,omitempty"`
	IsCheck       bool                   `protobuf:"varint,9,opt,name=isCheck,proto3" json:"isCheck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistMove) Reset() {
	*x = HistMove{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistMove) ProtoMessage() {}

func (x *HistMove) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistMove.ProtoReflect.Descriptor instead.
func (*HistMove) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *HistMove) GetPiece() int32 {
	if x != nil {
		return x.Piece
	}
	return 0
}

func (x *HistMove) GetFromFile() int32 {
	if x != nil {
		return x.FromFile
	}
	return 0
}

func (x *HistMove) GetFromRank() int32 {
	if x != nil {
		return x.FromRank
	}
	return 0
}

func (x *HistMove) GetToFile() int32 {
	if x != nil {
		return x.ToFile
	}
	return 0
}

func (x *HistMove) GetToRank() int32 {
	if x != nil {
		return x.ToRank
	}
	return 0
}

func (x *HistMove) GetCollFile() bool {
	if x != nil {
		return x.CollFile
	}
	return false
}

func (x *HistMove) GetCollRank() bool {
	if x != nil {
		return x.CollRank
	}
	return false
}

func (x *HistMove) GetIsTake() bool {
	if x != nil {
		return x.IsTake
	}
	return false
}

func (x *HistMove) GetIsCheck() bool {
	if x != nil {
		return x.IsCheck
	}
	return false
}

type ChessGame struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Board            *ChessBoard            `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	WhiteMoves       []*PieceMoves          `protobuf:"bytes,2,rep,name=white_moves,json=whiteMoves,proto3" json:"white_moves,omitempty"`
	BlackMoves       []*PieceMoves          `protobuf:"bytes,3,rep,name=black_moves,json=blackMoves,proto3" json:"black_moves,omitempty"`
	TakenWhitePieces []int32                `protobuf:"varint,4,rep,packed,name=taken_white_pieces,json=takenWhitePieces,proto3" json:"taken_white_pieces,omitempty"`
	TakenBlackPieces []int32                `protobuf:"varint,5,rep,packed,name=taken_black_pieces,json=takenBlackPieces,proto3" json:"taken_black_pieces,omitempty"`
	Moves            []*HistMove            `protobuf:"bytes,6,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChessGame) Reset() {
	*x = ChessGame{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChessGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChessGame) ProtoMessage() {}

func (x *ChessGame) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChessGame.ProtoReflect.Descriptor instead.
func (*ChessGame) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ChessGame) GetBoard() *ChessBoard {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *ChessGame) GetWhiteMoves() []*PieceMoves {
	if x != nil {
		return x.WhiteMoves
	}
	return nil
}

func (x *ChessGame) GetBlackMoves() []*PieceMoves {
	if x != nil {
		return x.BlackMoves
	}
	return nil
}

func (x *ChessGame) GetTakenWhitePieces() []int32 {
	if x != nil {
		return x.TakenWhitePieces
	}
	return nil
}

func (x *ChessGame) GetTakenBlackPieces() []int32 {
	if x != nil {
		return x.TakenBlackPieces
	}
	return nil
}

func (x *ChessGame) GetMoves() []*HistMove {
	if x != nil {
		return x.Moves
	}
	return nil
}

type ChessState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Game          *ChessGame             `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	WhitePlayer   *PlayerState           `protobuf:"bytes,4,opt,name=white_player,json=whitePlayer,proto3" json:"white_player,omitempty"`
	BlackPlayer   *PlayerState           `protobuf:"bytes,5,opt,name=black_player,json=blackPlayer,proto3" json:"black_player,omitempty"`
	IsEnded       bool                   `protobuf:"varint,6,opt,name=is_ended,json=isEnded,proto3" json:"is_ended,omitempty"`
	FirstColor    string                 `protobuf:"bytes,7,opt,name=first_color,json=firstColor,proto3" json:"first_color,omitempty"`
	Mode          string                 `protobuf:"bytes,8,opt,name=mode,proto3" json:"mode,omitempty"`
	Touch         int64                  `protobuf:"varint,9,opt,name=touch,proto3" json:"touch,omitempty"`
	InitialBoard  *ChessBoard            `protobuf:"bytes,10,opt,name=initial_board,json=initialBoard,proto3" json:"initial_board,omitempty"`
	UndoId        int64                  `protobuf:"varint,11,opt,name=undo_id,json=undoId,proto3" json:"undo_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChessState) Reset() {
	*x = ChessState{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChessState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChessState) ProtoMessage() {}

func (x *ChessState) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChessState.ProtoReflect.Descriptor instead.
func (*ChessState) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *ChessState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChessState) GetGame() *ChessGame {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *ChessState) GetWhitePlayer() *PlayerState {
	if x != nil {
		return x.WhitePlayer
	}
	return nil
}

func (x *ChessState) GetBlackPlayer() *PlayerState {
	if x != nil {
		return x.BlackPlayer
	}
	return nil
}

func (x *ChessState) GetIsEnded() bool {
	if x != nil {
		return x.IsEnded
	}
	return false
}

func (x *ChessState) GetFirstColor() string {
	if x != nil {
		return x.FirstColor
	}
	return ""
}

func (x *ChessState) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ChessState) GetTouch() int64 {
	if x != nil {
		return x.Touch
	}
	return 0
}

func (x *ChessState) GetInitialBoard() *ChessBoard {
	if x != nil {
		return x.InitialBoard
	}
	return nil
}

func (x *ChessState) GetUndoId() int64 {
	if x != nil {
		return x.UndoId
	}
	return 0
}

type ForfeitInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForfeitInput) Reset() {
	*x = ForfeitInput{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForfeitInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForfeitInput) ProtoMessage() {}

func (x *ForfeitInput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForfeitInput.ProtoReflect.Descriptor instead.
func (*ForfeitInput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Promotion     int32                  `protobuf:"varint,1,opt,name=promotion,proto3" json:"promotion,omitempty"`
	FromFile      int32                  `protobuf:"varint,2,opt,name=fromFile,proto3" json:"fromFile,omitempty"`
	FromRank      int32                  `protobuf:"varint,3,opt,name=fromRank,proto3" json:"fromRank,omitempty"`
	ToFile        int32                  `protobuf:"varint,4,opt,name=toFile,proto3" json:"toFile,omitempty"`
	ToRank        int32                  `protobuf:"varint,5,opt,name=toRank,proto3" json:"toRank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *Move) GetPromotion() int32 {
	if x != nil {
		return x.Promotion
	}
	return 0
}

func (x *Move) GetFromFile() int32 {
	if x != nil {
		return x.FromFile
	}
	return 0
}

func (x *Move) GetFromRank() int32 {
	if x != nil {
		return x.FromRank
	}
	return 0
}

func (x *Move) GetToFile() int32 {
	if x != nil {
		return x.ToFile
	}
	return 0
}

func (x *Move) GetToRank() int32 {
	if x != nil {
		return x.ToRank
	}
	return 0
}

type MoveInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Move          *Move                  `protobuf:"bytes,1,opt,name=move,proto3" json:"move,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveInput) Reset() {
	*x = MoveInput{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveInput) ProtoMessage() {}

func (x *MoveInput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveInput.ProtoReflect.Descriptor instead.
func (*MoveInput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *MoveInput) GetMove() *Move {
	if x != nil {
		return x.Move
	}
	return nil
}

type ChatInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatInput) Reset() {
	*x = ChatInput{}
	mi := &file_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatInput) ProtoMessage() {}

func (x *ChatInput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatInput.ProtoReflect.Descriptor instead.
func (*ChatInput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ChatInput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GameInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*GameInput_Forfeit
	//	*GameInput_Move
	//	*GameInput_Chat
	//	*GameInput_Undo
	Value         isGameInput_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameInput) Reset() {
	*x = GameInput{}
	mi := &file_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInput) ProtoMessage() {}

func (x *GameInput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInput.ProtoReflect.Descriptor instead.
func (*GameInput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *GameInput) GetValue() isGameInput_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GameInput) GetForfeit() *ForfeitInput {
	if x != nil {
		if x, ok := x.Value.(*GameInput_Forfeit); ok {
			return x.Forfeit
		}
	}
	return nil
}

func (x *GameInput) GetMove() *MoveInput {
	if x != nil {
		if x, ok := x.Value.(*GameInput_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *GameInput) GetChat() *ChatInput {
	if x != nil {
		if x, ok := x.Value.(*GameInput_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *GameInput) GetUndo() *UndoInput {
	if x != nil {
		if x, ok := x.Value.(*GameInput_Undo); ok {
			return x.Undo
		}
	}
	return nil
}

type isGameInput_Value interface {
	isGameInput_Value()
}

type GameInput_Forfeit struct {
	Forfeit *ForfeitInput `protobuf:"bytes,1,opt,name=forfeit,proto3,oneof"`
}

type GameInput_Move struct {
	Move *MoveInput `protobuf:"bytes,2,opt,name=move,proto3,oneof"`
}

type GameInput_Chat struct {
	Chat *ChatInput `protobuf:"bytes,3,opt,name=chat,proto3,oneof"`
}

type GameInput_Undo struct {
	Undo *UndoInput `protobuf:"bytes,4,opt,name=undo,proto3,oneof"`
}

func (*GameInput_Forfeit) isGameInput_Value() {}

func (*GameInput_Move) isGameInput_Value() {}

func (*GameInput_Chat) isGameInput_Value() {}

func (*GameInput_Undo) isGameInput_Value() {}

type UndoInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndoInput) Reset() {
	*x = UndoInput{}
	mi := &file_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndoInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoInput) ProtoMessage() {}

func (x *UndoInput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoInput.ProtoReflect.Descriptor instead.
func (*UndoInput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{13}
}

func (x *UndoInput) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type ErrorOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorOutput) Reset() {
	*x = ErrorOutput{}
	mi := &file_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorOutput) ProtoMessage() {}

func (x *ErrorOutput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorOutput.ProtoReflect.Descriptor instead.
func (*ErrorOutput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{14}
}

func (x *ErrorOutput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InitOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *ChessState            `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Self          *PlayerState           `protobuf:"bytes,2,opt,name=self,proto3" json:"self,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitOutput) Reset() {
	*x = InitOutput{}
	mi := &file_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitOutput) ProtoMessage() {}

func (x *InitOutput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitOutput.ProtoReflect.Descriptor instead.
func (*InitOutput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{15}
}

func (x *InitOutput) GetState() *ChessState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *InitOutput) GetSelf() *PlayerState {
	if x != nil {
		return x.Self
	}
	return nil
}

type PlayersOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WhitePlayer   *PlayerState           `protobuf:"bytes,1,opt,name=white_player,json=whitePlayer,proto3" json:"white_player,omitempty"`
	BlackPlayer   *PlayerState           `protobuf:"bytes,2,opt,name=black_player,json=blackPlayer,proto3" json:"black_player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayersOutput) Reset() {
	*x = PlayersOutput{}
	mi := &file_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayersOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayersOutput) ProtoMessage() {}

func (x *PlayersOutput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayersOutput.ProtoReflect.Descriptor instead.
func (*PlayersOutput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{16}
}

func (x *PlayersOutput) GetWhitePlayer() *PlayerState {
	if x != nil {
		return x.WhitePlayer
	}
	return nil
}

func (x *PlayersOutput) GetBlackPlayer() *PlayerState {
	if x != nil {
		return x.BlackPlayer
	}
	return nil
}

type MoveOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Move          *HistMove              `protobuf:"bytes,1,opt,name=move,proto3" json:"move,omitempty"`
	Game          *ChessGame             `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveOutput) Reset() {
	*x = MoveOutput{}
	mi := &file_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveOutput) ProtoMessage() {}

func (x *MoveOutput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveOutput.ProtoReflect.Descriptor instead.
func (*MoveOutput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{17}
}

func (x *MoveOutput) GetMove() *HistMove {
	if x != nil {
		return x.Move
	}
	return nil
}

func (x *MoveOutput) GetGame() *ChessGame {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *MoveOutput) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ChatOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerState           `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatOutput) Reset() {
	*x = ChatOutput{}
	mi := &file_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatOutput) ProtoMessage() {}

func (x *ChatOutput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatOutput.ProtoReflect.Descriptor instead.
func (*ChatOutput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{18}
}

func (x *ChatOutput) GetPlayer() *PlayerState {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *ChatOutput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ForfeitOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplayId      int64                  `protobuf:"varint,1,opt,name=replay_id,json=replayId,proto3" json:"replay_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForfeitOutput) Reset() {
	*x = ForfeitOutput{}
	mi := &file_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForfeitOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForfeitOutput) ProtoMessage() {}

func (x *ForfeitOutput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForfeitOutput.ProtoReflect.Descriptor instead.
func (*ForfeitOutput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{19}
}

func (x *ForfeitOutput) GetReplayId() int64 {
	if x != nil {
		return x.ReplayId
	}
	return 0
}

type UndoOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	UndoId        int64                  `protobuf:"varint,2,opt,name=undo_id,json=undoId,proto3" json:"undo_id,omitempty"`
	Game          *ChessGame             `protobuf:"bytes,3,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndoOutput) Reset() {
	*x = UndoOutput{}
	mi := &file_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndoOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoOutput) ProtoMessage() {}

func (x *UndoOutput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoOutput.ProtoReflect.Descriptor instead.
func (*UndoOutput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{20}
}

func (x *UndoOutput) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *UndoOutput) GetUndoId() int64 {
	if x != nil {
		return x.UndoId
	}
	return 0
}

func (x *UndoOutput) GetGame() *ChessGame {
	if x != nil {
		return x.Game
	}
	return nil
}

type GameOutputID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameOutputID) Reset() {
	*x = GameOutputID{}
	mi := &file_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameOutputID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOutputID) ProtoMessage() {}

func (x *GameOutputID) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOutputID.ProtoReflect.Descriptor instead.
func (*GameOutputID) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{21}
}

func (x *GameOutputID) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameOutputID) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type GameOutput struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	GameId    string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	MessageId string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*GameOutput_Error
	//	*GameOutput_Init
	//	*GameOutput_Players
	//	*GameOutput_Move
	//	*GameOutput_Chat
	//	*GameOutput_Forfeit
	//	*GameOutput_Undo
	Value         isGameOutput_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameOutput) Reset() {
	*x = GameOutput{}
	mi := &file_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOutput) ProtoMessage() {}

func (x *GameOutput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOutput.ProtoReflect.Descriptor instead.
func (*GameOutput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{22}
}

func (x *GameOutput) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameOutput) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GameOutput) GetValue() isGameOutput_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GameOutput) GetError() *ErrorOutput {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *GameOutput) GetInit() *InitOutput {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *GameOutput) GetPlayers() *PlayersOutput {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Players); ok {
			return x.Players
		}
	}
	return nil
}

func (x *GameOutput) GetMove() *MoveOutput {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *GameOutput) GetChat() *ChatOutput {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *GameOutput) GetForfeit() *ForfeitOutput {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Forfeit); ok {
			return x.Forfeit
		}
	}
	return nil
}

func (x *GameOutput) GetUndo() *UndoOutput {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Undo); ok {
			return x.Undo
		}
	}
	return nil
}

type isGameOutput_Value interface {
	isGameOutput_Value()
}

type GameOutput_Error struct {
	Error *ErrorOutput `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type GameOutput_Init struct {
	Init *InitOutput `protobuf:"bytes,4,opt,name=init,proto3,oneof"`
}

type GameOutput_Players struct {
	Players *PlayersOutput `protobuf:"bytes,5,opt,name=players,proto3,oneof"`
}

type GameOutput_Move struct {
	Move *MoveOutput `protobuf:"bytes,6,opt,name=move,proto3,oneof"`
}

type GameOutput_Chat struct {
	Chat *ChatOutput `protobuf:"bytes,7,opt,name=chat,proto3,oneof"`
}

type GameOutput_Forfeit struct {
	Forfeit *ForfeitOutput `protobuf:"bytes,8,opt,name=forfeit,proto3,oneof"`
}

type GameOutput_Undo struct {
	Undo *UndoOutput `protobuf:"bytes,9,opt,name=undo,proto3,oneof"`
}

func (*GameOutput_Error) isGameOutput_Value() {}

func (*GameOutput_Init) isGameOutput_Value() {}

func (*GameOutput_Players) isGameOutput_Value() {}

func (*GameOutput_Move) isGameOutput_Value() {}

func (*GameOutput_Chat) isGameOutput_Value() {}

func (*GameOutput_Forfeit) isGameOutput_Value() {}

func (*GameOutput_Undo) isGameOutput_Value() {}

type HistMoves struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moves         []*HistMove            `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistMoves) Reset() {
	*x = HistMoves{}
	mi := &file_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistMoves) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistMoves) ProtoMessage() {}

func (x *HistMoves) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistMoves.ProtoReflect.Descriptor instead.
func (*HistMoves) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{23}
}

func (x *HistMoves) GetMoves() []*HistMove {
	if x != nil {
		return x.Moves
	}
	return nil
}

type MoveHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitialGame   *ChessGame             `protobuf:"bytes,1,opt,name=initial_game,json=initialGame,proto3" json:"initial_game,omitempty"`
	Steps         []*MoveStep            `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveHistory) Reset() {
	*x = MoveHistory{}
	mi := &file_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveHistory) ProtoMessage() {}

func (x *MoveHistory) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveHistory.ProtoReflect.Descriptor instead.
func (*MoveHistory) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{24}
}

func (x *MoveHistory) GetInitialGame() *ChessGame {
	if x != nil {
		return x.InitialGame
	}
	return nil
}

func (x *MoveHistory) GetSteps() []*MoveStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type MoveStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Move          *HistMove              `protobuf:"bytes,1,opt,name=move,proto3" json:"move,omitempty"`
	Game          *ChessGame             `protobuf:"bytes,3,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveStep) Reset() {
	*x = MoveStep{}
	mi := &file_messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveStep) ProtoMessage() {}

func (x *MoveStep) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveStep.ProtoReflect.Descriptor instead.
func (*MoveStep) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{25}
}

func (x *MoveStep) GetMove() *HistMove {
	if x != nil {
		return x.Move
	}
	return nil
}

func (x *MoveStep) GetGame() *ChessGame {
	if x != nil {
		return x.Game
	}
	return nil
}

type MoveReplay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitialGame   *ChessGame             `protobuf:"bytes,1,opt,name=initial_game,json=initialGame,proto3" json:"initial_game,omitempty"`
	Steps         []*NotMoveStep         `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveReplay) Reset() {
	*x = MoveReplay{}
	mi := &file_messages_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveReplay) ProtoMessage() {}

func (x *MoveReplay) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveReplay.ProtoReflect.Descriptor instead.
func (*MoveReplay) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{26}
}

func (x *MoveReplay) GetInitialGame() *ChessGame {
	if x != nil {
		return x.InitialGame
	}
	return nil
}

func (x *MoveReplay) GetSteps() []*NotMoveStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type NotMoveStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotMove       string                 `protobuf:"bytes,1,opt,name=notMove,proto3" json:"notMove,omitempty"`
	Pm            *PieceMove             `protobuf:"bytes,2,opt,name=pm,proto3" json:"pm,omitempty"`
	Game          *ChessGame             `protobuf:"bytes,3,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotMoveStep) Reset() {
	*x = NotMoveStep{}
	mi := &file_messages_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotMoveStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotMoveStep) ProtoMessage() {}

func (x *NotMoveStep) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotMoveStep.ProtoReflect.Descriptor instead.
func (*NotMoveStep) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{27}
}

func (x *NotMoveStep) GetNotMove() string {
	if x != nil {
		return x.NotMove
	}
	return ""
}

func (x *NotMoveStep) GetPm() *PieceMove {
	if x != nil {
		return x.Pm
	}
	return nil
}

func (x *NotMoveStep) GetGame() *ChessGame {
	if x != nil {
		return x.Game
	}
	return nil
}

type MakeMoveInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Move          *Move                  `protobuf:"bytes,1,opt,name=move,proto3" json:"move,omitempty"`
	Game          *ChessGame             `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMoveInput) Reset() {
	*x = MakeMoveInput{}
	mi := &file_messages_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMoveInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveInput) ProtoMessage() {}

func (x *MakeMoveInput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveInput.ProtoReflect.Descriptor instead.
func (*MakeMoveInput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{28}
}

func (x *MakeMoveInput) GetMove() *Move {
	if x != nil {
		return x.Move
	}
	return nil
}

func (x *MakeMoveInput) GetGame() *ChessGame {
	if x != nil {
		return x.Game
	}
	return nil
}

type UserMsg struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*UserMsg_Challenge
	Value         isUserMsg_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMsg) Reset() {
	*x = UserMsg{}
	mi := &file_messages_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMsg) ProtoMessage() {}

func (x *UserMsg) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMsg.ProtoReflect.Descriptor instead.
func (*UserMsg) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{29}
}

func (x *UserMsg) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserMsg) GetValue() isUserMsg_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *UserMsg) GetChallenge() *ChallengeMsg {
	if x != nil {
		if x, ok := x.Value.(*UserMsg_Challenge); ok {
			return x.Challenge
		}
	}
	return nil
}

type isUserMsg_Value interface {
	isUserMsg_Value()
}

type UserMsg_Challenge struct {
	Challenge *ChallengeMsg `protobuf:"bytes,2,opt,name=challenge,proto3,oneof"`
}

func (*UserMsg_Challenge) isUserMsg_Value() {}

type ChallengeMsg struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChallengerId      int64                  `protobuf:"varint,1,opt,name=challenger_id,json=challengerId,proto3" json:"challenger_id,omitempty"`
	ChallengerName    string                 `protobuf:"bytes,2,opt,name=challenger_name,json=challengerName,proto3" json:"challenger_name,omitempty"`
	ChallengerCountry string                 `protobuf:"bytes,3,opt,name=challenger_country,json=challengerCountry,proto3" json:"challenger_country,omitempty"`
	ChallengerElo     float64                `protobuf:"fixed64,4,opt,name=challenger_elo,json=challengerElo,proto3" json:"challenger_elo,omitempty"`
	ChallengeeId      int64                  `protobuf:"varint,5,opt,name=challengee_id,json=challengeeId,proto3" json:"challengee_id,omitempty"`
	ChallengeeName    string                 `protobuf:"bytes,6,opt,name=challengee_name,json=challengeeName,proto3" json:"challengee_name,omitempty"`
	ChallengeeCountry string                 `protobuf:"bytes,7,opt,name=challengee_country,json=challengeeCountry,proto3" json:"challengee_country,omitempty"`
	ChallengeeElo     float64                `protobuf:"fixed64,8,opt,name=challengee_elo,json=challengeeElo,proto3" json:"challengee_elo,omitempty"`
	Mode              string                 `protobuf:"bytes,9,opt,name=mode,proto3" json:"mode,omitempty"`
	StartColor        string                 `protobuf:"bytes,10,opt,name=start_color,json=startColor,proto3" json:"start_color,omitempty"`
	MadeOn            string                 `protobuf:"bytes,11,opt,name=made_on,json=madeOn,proto3" json:"made_on,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChallengeMsg) Reset() {
	*x = ChallengeMsg{}
	mi := &file_messages_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeMsg) ProtoMessage() {}

func (x *ChallengeMsg) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeMsg.ProtoReflect.Descriptor instead.
func (*ChallengeMsg) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{30}
}

func (x *ChallengeMsg) GetChallengerId() int64 {
	if x != nil {
		return x.ChallengerId
	}
	return 0
}

func (x *ChallengeMsg) GetChallengerName() string {
	if x != nil {
		return x.ChallengerName
	}
	return ""
}

func (x *ChallengeMsg) GetChallengerCountry() string {
	if x != nil {
		return x.ChallengerCountry
	}
	return ""
}

func (x *ChallengeMsg) GetChallengerElo() float64 {
	if x != nil {
		return x.ChallengerElo
	}
	return 0
}

func (x *ChallengeMsg) GetChallengeeId() int64 {
	if x != nil {
		return x.ChallengeeId
	}
	return 0
}

func (x *ChallengeMsg) GetChallengeeName() string {
	if x != nil {
		return x.ChallengeeName
	}
	return ""
}

func (x *ChallengeMsg) GetChallengeeCountry() string {
	if x != nil {
		return x.ChallengeeCountry
	}
	return ""
}

func (x *ChallengeMsg) GetChallengeeElo() float64 {
	if x != nil {
		return x.ChallengeeElo
	}
	return 0
}

func (x *ChallengeMsg) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ChallengeMsg) GetStartColor() string {
	if x != nil {
		return x.StartColor
	}
	return ""
}

func (x *ChallengeMsg) GetMadeOn() string {
	if x != nil {
		return x.MadeOn
	}
	return ""
}

type EloHistoryBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Elo           float64                `protobuf:"fixed64,2,opt,name=elo,proto3" json:"elo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EloHistoryBucket) Reset() {
	*x = EloHistoryBucket{}
	mi := &file_messages_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EloHistoryBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EloHistoryBucket) ProtoMessage() {}

func (x *EloHistoryBucket) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EloHistoryBucket.ProtoReflect.Descriptor instead.
func (*EloHistoryBucket) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{31}
}

func (x *EloHistoryBucket) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *EloHistoryBucket) GetElo() float64 {
	if x != nil {
		return x.Elo
	}
	return 0
}

type EloHistoryBuckets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buckets       []*EloHistoryBucket    `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EloHistoryBuckets) Reset() {
	*x = EloHistoryBuckets{}
	mi := &file_messages_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EloHistoryBuckets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EloHistoryBuckets) ProtoMessage() {}

func (x *EloHistoryBuckets) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EloHistoryBuckets.ProtoReflect.Descriptor instead.
func (*EloHistoryBuckets) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{32}
}

func (x *EloHistoryBuckets) GetBuckets() []*EloHistoryBucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\bmessages\"w\n" +
	"\vPlayerState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x10\n" +
	"\x03elo\x18\x04 \x01(\x01R\x03elo\x12\x18\n" +
	"\aisGuest\x18\x05 \x01(\bR\aisGuest\"\x89\x01\n" +
	"\tPieceMove\x12\x14\n" +
	"\x05piece\x18\x01 \x01(\x05R\x05piece\x12\x1a\n" +
	"\bfromFile\x18\x02 \x01(\x05R\bfromFile\x12\x1a\n" +
	"\bfromRank\x18\x03 \x01(\x05R\bfromRank\x12\x16\n" +
	"\x06toFile\x18\x04 \x01(\x05R\x06toFile\x12\x16\n" +
	"\x06toRank\x18\x05 \x01(\x05R\x06toRank\"p\n" +
	"\n" +
	"PieceMoves\x12\x14\n" +
	"\x05piece\x18\x01 \x01(\x05R\x05piece\x12\x1a\n" +
	"\bfromFile\x18\x02 \x01(\x05R\bfromFile\x12\x1a\n" +
	"\bfromRank\x18\x03 \x01(\x05R\bfromRank\x12\x14\n" +
	"\x05moves\x18\x04 \x03(\x03R\x05moves\"#\n" +
	"\tBoardFile\x12\x16\n" +
	"\x06pieces\x18\x01 \x03(\rR\x06pieces\"Y\n" +
	"\n" +
	"ChessBoard\x12\"\n" +
	"\ris_white_turn\x18\x01 \x01(\bR\visWhiteTurn\x12'\n" +
	"\x04file\x18\x02 \x03(\v2\x13.messages.BoardFileR\x04file\"\xf2\x01\n" +
	"\bHistMove\x12\x14\n" +
	"\x05piece\x18\x01 \x01(\x05R\x05piece\x12\x1a\n" +
	"\bfromFile\x18\x02 \x01(\x05R\bfromFile\x12\x1a\n" +
	"\bfromRank\x18\x03 \x01(\x05R\bfromRank\x12\x16\n" +
	"\x06toFile\x18\x04 \x01(\x05R\x06toFile\x12\x16\n" +
	"\x06toRank\x18\x05 \x01(\x05R\x06toRank\x12\x1a\n" +
	"\bcollFile\x18\x06 \x01(\bR\bcollFile\x12\x1a\n" +
	"\bcollRank\x18\a \x01(\bR\bcollRank\x12\x16\n" +
	"\x06isTake\x18\b \x01(\bR\x06isTake\x12\x18\n" +
	"\aisCheck\x18\t \x01(\bR\aisCheck\"\xab\x02\n" +
	"\tChessGame\x12*\n" +
	"\x05board\x18\x01 \x01(\v2\x14.messages.ChessBoardR\x05board\x125\n" +
	"\vwhite_moves\x18\x02 \x03(\v2\x14.messages.PieceMovesR\n" +
	"whiteMoves\x125\n" +
	"\vblack_moves\x18\x03 \x03(\v2\x14.messages.PieceMovesR\n" +
	"blackMoves\x12,\n" +
	"\x12taken_white_pieces\x18\x04 \x03(\x05R\x10takenWhitePieces\x12,\n" +
	"\x12taken_black_pieces\x18\x05 \x03(\x05R\x10takenBlackPieces\x12(\n" +
	"\x05moves\x18\x06 \x03(\v2\x12.messages.HistMoveR\x05moves\"\xf3\x02\n" +
	"\n" +
	"ChessState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04game\x18\x02 \x01(\v2\x13.messages.ChessGameR\x04game\x128\n" +
	"\fwhite_player\x18\x04 \x01(\v2\x15.messages.PlayerStateR\vwhitePlayer\x128\n" +
	"\fblack_player\x18\x05 \x01(\v2\x15.messages.PlayerStateR\vblackPlayer\x12\x19\n" +
	"\bis_ended\x18\x06 \x01(\bR\aisEnded\x12\x1f\n" +
	"\vfirst_color\x18\a \x01(\tR\n" +
	"firstColor\x12\x12\n" +
	"\x04mode\x18\b \x01(\tR\x04mode\x12\x14\n" +
	"\x05touch\x18\t \x01(\x03R\x05touch\x129\n" +
	"\rinitial_board\x18\n" +
	" \x01(\v2\x14.messages.ChessBoardR\finitialBoard\x12\x17\n" +
	"\aundo_id\x18\v \x01(\x03R\x06undoId\"\x0e\n" +
	"\fForfeitInput\"\x8c\x01\n" +
	"\x04Move\x12\x1c\n" +
	"\tpromotion\x18\x01 \x01(\x05R\tpromotion\x12\x1a\n" +
	"\bfromFile\x18\x02 \x01(\x05R\bfromFile\x12\x1a\n" +
	"\bfromRank\x18\x03 \x01(\x05R\bfromRank\x12\x16\n" +
	"\x06toFile\x18\x04 \x01(\x05R\x06toFile\x12\x16\n" +
	"\x06toRank\x18\x05 \x01(\x05R\x06toRank\"/\n" +
	"\tMoveInput\x12\"\n" +
	"\x04move\x18\x01 \x01(\v2\x0e.messages.MoveR\x04move\"%\n" +
	"\tChatInput\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xc9\x01\n" +
	"\tGameInput\x122\n" +
	"\aforfeit\x18\x01 \x01(\v2\x16.messages.ForfeitInputH\x00R\aforfeit\x12)\n" +
	"\x04move\x18\x02 \x01(\v2\x13.messages.MoveInputH\x00R\x04move\x12)\n" +
	"\x04chat\x18\x03 \x01(\v2\x13.messages.ChatInputH\x00R\x04chat\x12)\n" +
	"\x04undo\x18\x04 \x01(\v2\x13.messages.UndoInputH\x00R\x04undoB\a\n" +
	"\x05value\"\x1f\n" +
	"\tUndoInput\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\"'\n" +
	"\vErrorOutput\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"c\n" +
	"\n" +
	"InitOutput\x12*\n" +
	"\x05state\x18\x01 \x01(\v2\x14.messages.ChessStateR\x05state\x12)\n" +
	"\x04self\x18\x02 \x01(\v2\x15.messages.PlayerStateR\x04self\"\x83\x01\n" +
	"\rPlayersOutput\x128\n" +
	"\fwhite_player\x18\x01 \x01(\v2\x15.messages.PlayerStateR\vwhitePlayer\x128\n" +
	"\fblack_player\x18\x02 \x01(\v2\x15.messages.PlayerStateR\vblackPlayer\"|\n" +
	"\n" +
	"MoveOutput\x12&\n" +
	"\x04move\x18\x01 \x01(\v2\x12.messages.HistMoveR\x04move\x12'\n" +
	"\x04game\x18\x02 \x01(\v2\x13.messages.ChessGameR\x04game\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\"U\n" +
	"\n" +
	"ChatOutput\x12-\n" +
	"\x06player\x18\x01 \x01(\v2\x15.messages.PlayerStateR\x06player\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\rForfeitOutput\x12\x1b\n" +
	"\treplay_id\x18\x01 \x01(\x03R\breplayId\"b\n" +
	"\n" +
	"UndoOutput\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x17\n" +
	"\aundo_id\x18\x02 \x01(\x03R\x06undoId\x12'\n" +
	"\x04game\x18\x03 \x01(\v2\x13.messages.ChessGameR\x04game\"F\n" +
	"\fGameOutputID\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"\x96\x03\n" +
	"\n" +
	"GameOutput\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12-\n" +
	"\x05error\x18\x03 \x01(\v2\x15.messages.ErrorOutputH\x00R\x05error\x12*\n" +
	"\x04init\x18\x04 \x01(\v2\x14.messages.InitOutputH\x00R\x04init\x123\n" +
	"\aplayers\x18\x05 \x01(\v2\x17.messages.PlayersOutputH\x00R\aplayers\x12*\n" +
	"\x04move\x18\x06 \x01(\v2\x14.messages.MoveOutputH\x00R\x04move\x12*\n" +
	"\x04chat\x18\a \x01(\v2\x14.messages.ChatOutputH\x00R\x04chat\x123\n" +
	"\aforfeit\x18\b \x01(\v2\x17.messages.ForfeitOutputH\x00R\aforfeit\x12*\n" +
	"\x04undo\x18\t \x01(\v2\x14.messages.UndoOutputH\x00R\x04undoB\a\n" +
	"\x05value\"5\n" +
	"\tHistMoves\x12(\n" +
	"\x05moves\x18\x01 \x03(\v2\x12.messages.HistMoveR\x05moves\"o\n" +
	"\vMoveHistory\x126\n" +
	"\finitial_game\x18\x01 \x01(\v2\x13.messages.ChessGameR\vinitialGame\x12(\n" +
	"\x05steps\x18\x02 \x03(\v2\x12.messages.MoveStepR\x05steps\"[\n" +
	"\bMoveStep\x12&\n" +
	"\x04move\x18\x01 \x01(\v2\x12.messages.HistMoveR\x04move\x12'\n" +
	"\x04game\x18\x03 \x01(\v2\x13.messages.ChessGameR\x04game\"q\n" +
	"\n" +
	"MoveReplay\x126\n" +
	"\finitial_game\x18\x01 \x01(\v2\x13.messages.ChessGameR\vinitialGame\x12+\n" +
	"\x05steps\x18\x02 \x03(\v2\x15.messages.NotMoveStepR\x05steps\"u\n" +
	"\vNotMoveStep\x12\x18\n" +
	"\anotMove\x18\x01 \x01(\tR\anotMove\x12#\n" +
	"\x02pm\x18\x02 \x01(\v2\x13.messages.PieceMoveR\x02pm\x12'\n" +
	"\x04game\x18\x03 \x01(\v2\x13.messages.ChessGameR\x04game\"\\\n" +
	"\rMakeMoveInput\x12\"\n" +
	"\x04move\x18\x01 \x01(\v2\x0e.messages.MoveR\x04move\x12'\n" +
	"\x04game\x18\x02 \x01(\v2\x13.messages.ChessGameR\x04game\"c\n" +
	"\aUserMsg\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x126\n" +
	"\tchallenge\x18\x02 \x01(\v2\x16.messages.ChallengeMsgH\x00R\tchallengeB\a\n" +
	"\x05value\"\xa4\x03\n" +
	"\fChallengeMsg\x12#\n" +
	"\rchallenger_id\x18\x01 \x01(\x03R\fchallengerId\x12'\n" +
	"\x0fchallenger_name\x18\x02 \x01(\tR\x0echallengerName\x12-\n" +
	"\x12challenger_country\x18\x03 \x01(\tR\x11challengerCountry\x12%\n" +
	"\x0echallenger_elo\x18\x04 \x01(\x01R\rchallengerElo\x12#\n" +
	"\rchallengee_id\x18\x05 \x01(\x03R\fchallengeeId\x12'\n" +
	"\x0fchallengee_name\x18\x06 \x01(\tR\x0echallengeeName\x12-\n" +
	"\x12challengee_country\x18\a \x01(\tR\x11challengeeCountry\x12%\n" +
	"\x0echallengee_elo\x18\b \x01(\x01R\rchallengeeElo\x12\x12\n" +
	"\x04mode\x18\t \x01(\tR\x04mode\x12\x1f\n" +
	"\vstart_color\x18\n" +
	" \x01(\tR\n" +
	"startColor\x12\x17\n" +
	"\amade_on\x18\v \x01(\tR\x06madeOn\"B\n" +
	"\x10EloHistoryBucket\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x10\n" +
	"\x03elo\x18\x02 \x01(\x01R\x03elo\"I\n" +
	"\x11EloHistoryBuckets\x124\n" +
	"\abuckets\x18\x01 \x03(\v2\x1a.messages.EloHistoryBucketR\abucketsB\x11Z\x0fhexchess-svc/pbb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_messages_proto_goTypes = []any{
	(*PlayerState)(nil),       // 0: messages.PlayerState
	(*PieceMove)(nil),         // 1: messages.PieceMove
	(*PieceMoves)(nil),        // 2: messages.PieceMoves
	(*BoardFile)(nil),         // 3: messages.BoardFile
	(*ChessBoard)(nil),        // 4: messages.ChessBoard
	(*HistMove)(nil),          // 5: messages.HistMove
	(*ChessGame)(nil),         // 6: messages.ChessGame
	(*ChessState)(nil),        // 7: messages.ChessState
	(*ForfeitInput)(nil),      // 8: messages.ForfeitInput
	(*Move)(nil),              // 9: messages.Move
	(*MoveInput)(nil),         // 10: messages.MoveInput
	(*ChatInput)(nil),         // 11: messages.ChatInput
	(*GameInput)(nil),         // 12: messages.GameInput
	(*UndoInput)(nil),         // 13: messages.UndoInput
	(*ErrorOutput)(nil),       // 14: messages.ErrorOutput
	(*InitOutput)(nil),        // 15: messages.InitOutput
	(*PlayersOutput)(nil),     // 16: messages.PlayersOutput
	(*MoveOutput)(nil),        // 17: messages.MoveOutput
	(*ChatOutput)(nil),        // 18: messages.ChatOutput
	(*ForfeitOutput)(nil),     // 19: messages.ForfeitOutput
	(*UndoOutput)(nil),        // 20: messages.UndoOutput
	(*GameOutputID)(nil),      // 21: messages.GameOutputID
	(*GameOutput)(nil),        // 22: messages.GameOutput
	(*HistMoves)(nil),         // 23: messages.HistMoves
	(*MoveHistory)(nil),       // 24: messages.MoveHistory
	(*MoveStep)(nil),          // 25: messages.MoveStep
	(*MoveReplay)(nil),        // 26: messages.MoveReplay
	(*NotMoveStep)(nil),       // 27: messages.NotMoveStep
	(*MakeMoveInput)(nil),     // 28: messages.MakeMoveInput
	(*UserMsg)(nil),           // 29: messages.UserMsg
	(*ChallengeMsg)(nil),      // 30: messages.ChallengeMsg
	(*EloHistoryBucket)(nil),  // 31: messages.EloHistoryBucket
	(*EloHistoryBuckets)(nil), // 32: messages.EloHistoryBuckets
}
var file_messages_proto_depIdxs = []int32{
	3,  // 0: messages.ChessBoard.file:type_name -> messages.BoardFile
	4,  // 1: messages.ChessGame.board:type_name -> messages.ChessBoard
	2,  // 2: messages.ChessGame.white_moves:type_name -> messages.PieceMoves
	2,  // 3: messages.ChessGame.black_moves:type_name -> messages.PieceMoves
	5,  // 4: messages.ChessGame.moves:type_name -> messages.HistMove
	6,  // 5: messages.ChessState.game:type_name -> messages.ChessGame
	0,  // 6: messages.ChessState.white_player:type_name -> messages.PlayerState
	0,  // 7: messages.ChessState.black_player:type_name -> messages.PlayerState
	4,  // 8: messages.ChessState.initial_board:type_name -> messages.ChessBoard
	9,  // 9: messages.MoveInput.move:type_name -> messages.Move
	8,  // 10: messages.GameInput.forfeit:type_name -> messages.ForfeitInput
	10, // 11: messages.GameInput.move:type_name -> messages.MoveInput
	11, // 12: messages.GameInput.chat:type_name -> messages.ChatInput
	13, // 13: messages.GameInput.undo:type_name -> messages.UndoInput
	7,  // 14: messages.InitOutput.state:type_name -> messages.ChessState
	0,  // 15: messages.InitOutput.self:type_name -> messages.PlayerState
	0,  // 16: messages.PlayersOutput.white_player:type_name -> messages.PlayerState
	0,  // 17: messages.PlayersOutput.black_player:type_name -> messages.PlayerState
	5,  // 18: messages.MoveOutput.move:type_name -> messages.HistMove
	6,  // 19: messages.MoveOutput.game:type_name -> messages.ChessGame
	0,  // 20: messages.ChatOutput.player:type_name -> messages.PlayerState
	6,  // 21: messages.UndoOutput.game:type_name -> messages.ChessGame
	14, // 22: messages.GameOutput.error:type_name -> messages.ErrorOutput
	15, // 23: messages.GameOutput.init:type_name -> messages.InitOutput
	16, // 24: messages.GameOutput.players:type_name -> messages.PlayersOutput
	17, // 25: messages.GameOutput.move:type_name -> messages.MoveOutput
	18, // 26: messages.GameOutput.chat:type_name -> messages.ChatOutput
	19, // 27: messages.GameOutput.forfeit:type_name -> messages.ForfeitOutput
	20, // 28: messages.GameOutput.undo:type_name -> messages.UndoOutput
	5,  // 29: messages.HistMoves.moves:type_name -> messages.HistMove
	6,  // 30: messages.MoveHistory.initial_game:type_name -> messages.ChessGame
	25, // 31: messages.MoveHistory.steps:type_name -> messages.MoveStep
	5,  // 32: messages.MoveStep.move:type_name -> messages.HistMove
	6,  // 33: messages.MoveStep.game:type_name -> messages.ChessGame
	6,  // 34: messages.MoveReplay.initial_game:type_name -> messages.ChessGame
	27, // 35: messages.MoveReplay.steps:type_name -> messages.NotMoveStep
	1,  // 36: messages.NotMoveStep.pm:type_name -> messages.PieceMove
	6,  // 37: messages.NotMoveStep.game:type_name -> messages.ChessGame
	9,  // 38: messages.MakeMoveInput.move:type_name -> messages.Move
	6,  // 39: messages.MakeMoveInput.game:type_name -> messages.ChessGame
	30, // 40: messages.UserMsg.challenge:type_name -> messages.ChallengeMsg
	31, // 41: messages.EloHistoryBuckets.buckets:type_name -> messages.EloHistoryBucket
	42, // [42:42] is the sub-list for method output_type
	42, // [42:42] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[12].OneofWrappers = []any{
		(*GameInput_Forfeit)(nil),
		(*GameInput_Move)(nil),
		(*GameInput_Chat)(nil),
		(*GameInput_Undo)(nil),
	}
	file_messages_proto_msgTypes[22].OneofWrappers = []any{
		(*GameOutput_Error)(nil),
		(*GameOutput_Init)(nil),
		(*GameOutput_Players)(nil),
		(*GameOutput_Move)(nil),
		(*GameOutput_Chat)(nil),
		(*GameOutput_Forfeit)(nil),
		(*GameOutput_Undo)(nil),
	}
	file_messages_proto_msgTypes[29].OneofWrappers = []any{
		(*UserMsg_Challenge)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
