syntax = "proto3";
option go_package = "hexchess-data/pb";

package messages;

message PlayerState {
  int64 id = 1;
  string name = 2;
  string country = 3;
  double elo = 4;
  bool isGuest = 5;
}

message PieceMove {
  int32 piece = 1;
  int32 fromFile = 2;
  int32 fromRank = 3;
  int32 toFile = 4;
  int32 toRank = 5;
}

message PieceMoves {
  int32 fromFile = 1;
  int32 fromRank = 2;
  repeated int64 moves = 3;
}

message BoardFile {
  repeated uint32 pieces = 1;
}

message ChessBoard {
  bool is_white_turn = 1;
  repeated BoardFile file = 2;
}

message ChessGame {
  ChessBoard board = 1;
  repeated PieceMoves white_moves = 2;
  repeated PieceMoves black_moves = 3;
  repeated int32 taken_white_pieces = 4;
  repeated int32 taken_black_pieces = 5;
}

message ChessState {
  string id = 1;
  ChessGame game = 2;
  repeated PieceMove move_list = 3;
  PlayerState white_player = 4;
  PlayerState black_player = 5;
  bool is_ended = 6;
  uint32 first_color = 7;
  uint32 time_control = 8;
  int64 touch = 9;
}

message ForfeitInput {}

message MoveInput {
  PieceMove move = 1;
}

message ChatInput {
  string message = 1;
}

message GameInput {
  oneof value {
    ForfeitInput forfeit = 1;
    MoveInput move = 2;
    ChatInput chat = 3;
  }
}

message ErrorOutput {
  string message = 1;
}

message InitOutput {
  ChessState state = 1;
  PlayerState self = 2;
}

message PlayersOutput {
  PlayerState white_player = 1;
  PlayerState black_player = 2;
}

message MoveOutput {
  PieceMove pieceMove = 1;
  ChessGame game = 2;
}

message ChatOutput {
  PlayerState player = 1;
  string message = 2;
}

message ForfeitOutput {}

message GameOutputID {
  string game_id = 1;
  string message_id = 2;
}

message GameOutput {
  string game_id = 1;
  string message_id = 2;
  oneof value {
    ErrorOutput error = 3;
    InitOutput init = 4;
    PlayersOutput players = 5;
    MoveOutput move = 6;
    ChatOutput chat = 7;
    ForfeitOutput forfeit = 8;
  }
}

message UserMsg {
  string user_id = 1;
  oneof value {
    ChallengeMsg challenge = 2;
  }
}

message ChallengeMsg {
  int64 challenger_id = 1;
  string challenger_name = 2;
  string challenger_country = 3;
  double challenger_elo = 4;
  int64 challengee_id = 5;
  string challengee_name = 6;
  string challengee_country = 7;
  double challengee_elo = 8;
  uint32 time_control = 9;
  uint32 start_color = 10;
  int64 made_on = 11;
}
