syntax = "proto3";
option go_package = "hexchess-dal/pb";

package messages;

message PlayerState {
  int64 id = 1;
  string name = 2;
  string country = 3;
  float elo = 4;
  bool isGuest = 5;
}

message PieceMove {
  int32 piece = 1;
  int32 fromFile = 2;
  int32 fromRank = 3;
  int32 toFile = 4;
  int32 toRank = 5;
}

message PieceMoves {
  int32 fromFile = 1;
  int32 fromRank = 2;
  repeated int64 moves = 3;
}

message BoardFile {
  repeated uint32 pieces = 1;
}

message ChessBoard {
  bool is_white_turn = 1;
  repeated BoardFile file = 2;
}

message ChessGame {
  ChessBoard board = 1;
  repeated PieceMoves white_moves = 2;
  repeated PieceMoves black_moves = 3;
  repeated int32 taken_white_pieces = 4;
  repeated int32 taken_black_pieces = 5;
}

message ChessState {
  string id = 1;
  ChessGame game = 2;
  repeated PieceMove move_list = 3;
  PlayerState white_player = 4;
  PlayerState black_player = 5;
  bool is_ended = 6;
  uint32 first_color = 7;
  uint32 time_control = 8;
  int64 touch = 9;
}

message Error {
  string message = 1;
}

message Init {
  ChessState state = 1;
  PlayerState self = 2;
}

message Players {
  PlayerState whitePlayer = 1;
  PlayerState blackPlayer = 2;
}

message Move {
  PieceMove pieceMove = 1;
  ChessGame game = 2;
}

message Chat {
  PlayerState player = 2;
  string message = 3;
}

message Forfeit {}

message GameOutputID {
  string game_id = 1;
}

message GameOutput {
  string game_id = 1;
  oneof value {
    Error error = 2;
    Init init = 3;
    Players players = 4;
    Move move = 5;
    Chat chat = 6;
    Forfeit forfeit = 7;
  }
}