// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pb/messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Elo           float32                `protobuf:"fixed32,4,opt,name=elo,proto3" json:"elo,omitempty"`
	IsGuest       bool                   `protobuf:"varint,5,opt,name=isGuest,proto3" json:"isGuest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_pb_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerState) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerState) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *PlayerState) GetElo() float32 {
	if x != nil {
		return x.Elo
	}
	return 0
}

func (x *PlayerState) GetIsGuest() bool {
	if x != nil {
		return x.IsGuest
	}
	return false
}

type PieceMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piece         int32                  `protobuf:"varint,1,opt,name=piece,proto3" json:"piece,omitempty"`
	FromFile      int32                  `protobuf:"varint,2,opt,name=fromFile,proto3" json:"fromFile,omitempty"`
	FromRank      int32                  `protobuf:"varint,3,opt,name=fromRank,proto3" json:"fromRank,omitempty"`
	ToFile        int32                  `protobuf:"varint,4,opt,name=toFile,proto3" json:"toFile,omitempty"`
	ToRank        int32                  `protobuf:"varint,5,opt,name=toRank,proto3" json:"toRank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PieceMove) Reset() {
	*x = PieceMove{}
	mi := &file_pb_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PieceMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PieceMove) ProtoMessage() {}

func (x *PieceMove) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PieceMove.ProtoReflect.Descriptor instead.
func (*PieceMove) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{1}
}

func (x *PieceMove) GetPiece() int32 {
	if x != nil {
		return x.Piece
	}
	return 0
}

func (x *PieceMove) GetFromFile() int32 {
	if x != nil {
		return x.FromFile
	}
	return 0
}

func (x *PieceMove) GetFromRank() int32 {
	if x != nil {
		return x.FromRank
	}
	return 0
}

func (x *PieceMove) GetToFile() int32 {
	if x != nil {
		return x.ToFile
	}
	return 0
}

func (x *PieceMove) GetToRank() int32 {
	if x != nil {
		return x.ToRank
	}
	return 0
}

type PieceMoves struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromFile      int32                  `protobuf:"varint,1,opt,name=fromFile,proto3" json:"fromFile,omitempty"`
	FromRank      int32                  `protobuf:"varint,2,opt,name=fromRank,proto3" json:"fromRank,omitempty"`
	Moves         []int64                `protobuf:"varint,3,rep,packed,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PieceMoves) Reset() {
	*x = PieceMoves{}
	mi := &file_pb_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PieceMoves) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PieceMoves) ProtoMessage() {}

func (x *PieceMoves) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PieceMoves.ProtoReflect.Descriptor instead.
func (*PieceMoves) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{2}
}

func (x *PieceMoves) GetFromFile() int32 {
	if x != nil {
		return x.FromFile
	}
	return 0
}

func (x *PieceMoves) GetFromRank() int32 {
	if x != nil {
		return x.FromRank
	}
	return 0
}

func (x *PieceMoves) GetMoves() []int64 {
	if x != nil {
		return x.Moves
	}
	return nil
}

type BoardFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pieces        []uint32               `protobuf:"varint,1,rep,packed,name=pieces,proto3" json:"pieces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardFile) Reset() {
	*x = BoardFile{}
	mi := &file_pb_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardFile) ProtoMessage() {}

func (x *BoardFile) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardFile.ProtoReflect.Descriptor instead.
func (*BoardFile) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{3}
}

func (x *BoardFile) GetPieces() []uint32 {
	if x != nil {
		return x.Pieces
	}
	return nil
}

type ChessBoard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsWhiteTurn   bool                   `protobuf:"varint,1,opt,name=is_white_turn,json=isWhiteTurn,proto3" json:"is_white_turn,omitempty"`
	File          []*BoardFile           `protobuf:"bytes,2,rep,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChessBoard) Reset() {
	*x = ChessBoard{}
	mi := &file_pb_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChessBoard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChessBoard) ProtoMessage() {}

func (x *ChessBoard) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChessBoard.ProtoReflect.Descriptor instead.
func (*ChessBoard) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ChessBoard) GetIsWhiteTurn() bool {
	if x != nil {
		return x.IsWhiteTurn
	}
	return false
}

func (x *ChessBoard) GetFile() []*BoardFile {
	if x != nil {
		return x.File
	}
	return nil
}

type ChessGame struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Board            *ChessBoard            `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	WhiteMoves       []*PieceMoves          `protobuf:"bytes,2,rep,name=white_moves,json=whiteMoves,proto3" json:"white_moves,omitempty"`
	BlackMoves       []*PieceMoves          `protobuf:"bytes,3,rep,name=black_moves,json=blackMoves,proto3" json:"black_moves,omitempty"`
	TakenWhitePieces []int32                `protobuf:"varint,4,rep,packed,name=taken_white_pieces,json=takenWhitePieces,proto3" json:"taken_white_pieces,omitempty"`
	TakenBlackPieces []int32                `protobuf:"varint,5,rep,packed,name=taken_black_pieces,json=takenBlackPieces,proto3" json:"taken_black_pieces,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChessGame) Reset() {
	*x = ChessGame{}
	mi := &file_pb_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChessGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChessGame) ProtoMessage() {}

func (x *ChessGame) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChessGame.ProtoReflect.Descriptor instead.
func (*ChessGame) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ChessGame) GetBoard() *ChessBoard {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *ChessGame) GetWhiteMoves() []*PieceMoves {
	if x != nil {
		return x.WhiteMoves
	}
	return nil
}

func (x *ChessGame) GetBlackMoves() []*PieceMoves {
	if x != nil {
		return x.BlackMoves
	}
	return nil
}

func (x *ChessGame) GetTakenWhitePieces() []int32 {
	if x != nil {
		return x.TakenWhitePieces
	}
	return nil
}

func (x *ChessGame) GetTakenBlackPieces() []int32 {
	if x != nil {
		return x.TakenBlackPieces
	}
	return nil
}

type ChessState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Game          *ChessGame             `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	MoveList      []*PieceMove           `protobuf:"bytes,3,rep,name=move_list,json=moveList,proto3" json:"move_list,omitempty"`
	WhitePlayer   *PlayerState           `protobuf:"bytes,4,opt,name=white_player,json=whitePlayer,proto3" json:"white_player,omitempty"`
	BlackPlayer   *PlayerState           `protobuf:"bytes,5,opt,name=black_player,json=blackPlayer,proto3" json:"black_player,omitempty"`
	IsEnded       bool                   `protobuf:"varint,6,opt,name=is_ended,json=isEnded,proto3" json:"is_ended,omitempty"`
	FirstColor    uint32                 `protobuf:"varint,7,opt,name=first_color,json=firstColor,proto3" json:"first_color,omitempty"`
	TimeControl   uint32                 `protobuf:"varint,8,opt,name=time_control,json=timeControl,proto3" json:"time_control,omitempty"`
	Touch         int64                  `protobuf:"varint,9,opt,name=touch,proto3" json:"touch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChessState) Reset() {
	*x = ChessState{}
	mi := &file_pb_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChessState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChessState) ProtoMessage() {}

func (x *ChessState) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChessState.ProtoReflect.Descriptor instead.
func (*ChessState) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ChessState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChessState) GetGame() *ChessGame {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *ChessState) GetMoveList() []*PieceMove {
	if x != nil {
		return x.MoveList
	}
	return nil
}

func (x *ChessState) GetWhitePlayer() *PlayerState {
	if x != nil {
		return x.WhitePlayer
	}
	return nil
}

func (x *ChessState) GetBlackPlayer() *PlayerState {
	if x != nil {
		return x.BlackPlayer
	}
	return nil
}

func (x *ChessState) GetIsEnded() bool {
	if x != nil {
		return x.IsEnded
	}
	return false
}

func (x *ChessState) GetFirstColor() uint32 {
	if x != nil {
		return x.FirstColor
	}
	return 0
}

func (x *ChessState) GetTimeControl() uint32 {
	if x != nil {
		return x.TimeControl
	}
	return 0
}

func (x *ChessState) GetTouch() int64 {
	if x != nil {
		return x.Touch
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_pb_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{7}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Init struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *ChessState            `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Self          *PlayerState           `protobuf:"bytes,2,opt,name=self,proto3" json:"self,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Init) Reset() {
	*x = Init{}
	mi := &file_pb_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Init) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Init) ProtoMessage() {}

func (x *Init) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Init.ProtoReflect.Descriptor instead.
func (*Init) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{8}
}

func (x *Init) GetState() *ChessState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *Init) GetSelf() *PlayerState {
	if x != nil {
		return x.Self
	}
	return nil
}

type Players struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WhitePlayer   *PlayerState           `protobuf:"bytes,1,opt,name=whitePlayer,proto3" json:"whitePlayer,omitempty"`
	BlackPlayer   *PlayerState           `protobuf:"bytes,2,opt,name=blackPlayer,proto3" json:"blackPlayer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Players) Reset() {
	*x = Players{}
	mi := &file_pb_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Players) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Players) ProtoMessage() {}

func (x *Players) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Players.ProtoReflect.Descriptor instead.
func (*Players) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{9}
}

func (x *Players) GetWhitePlayer() *PlayerState {
	if x != nil {
		return x.WhitePlayer
	}
	return nil
}

func (x *Players) GetBlackPlayer() *PlayerState {
	if x != nil {
		return x.BlackPlayer
	}
	return nil
}

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PieceMove     *PieceMove             `protobuf:"bytes,1,opt,name=pieceMove,proto3" json:"pieceMove,omitempty"`
	Game          *ChessGame             `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_pb_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{10}
}

func (x *Move) GetPieceMove() *PieceMove {
	if x != nil {
		return x.PieceMove
	}
	return nil
}

func (x *Move) GetGame() *ChessGame {
	if x != nil {
		return x.Game
	}
	return nil
}

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerState           `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_pb_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{11}
}

func (x *Chat) GetPlayer() *PlayerState {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *Chat) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Forfeit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Forfeit) Reset() {
	*x = Forfeit{}
	mi := &file_pb_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Forfeit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forfeit) ProtoMessage() {}

func (x *Forfeit) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forfeit.ProtoReflect.Descriptor instead.
func (*Forfeit) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{12}
}

type GameOutputID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameOutputID) Reset() {
	*x = GameOutputID{}
	mi := &file_pb_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameOutputID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOutputID) ProtoMessage() {}

func (x *GameOutputID) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOutputID.ProtoReflect.Descriptor instead.
func (*GameOutputID) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{13}
}

func (x *GameOutputID) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GameOutput struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	GameId string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*GameOutput_Error
	//	*GameOutput_Init
	//	*GameOutput_Players
	//	*GameOutput_Move
	//	*GameOutput_Chat
	//	*GameOutput_Forfeit
	Value         isGameOutput_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameOutput) Reset() {
	*x = GameOutput{}
	mi := &file_pb_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOutput) ProtoMessage() {}

func (x *GameOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOutput.ProtoReflect.Descriptor instead.
func (*GameOutput) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{14}
}

func (x *GameOutput) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameOutput) GetValue() isGameOutput_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GameOutput) GetError() *Error {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *GameOutput) GetInit() *Init {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *GameOutput) GetPlayers() *Players {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Players); ok {
			return x.Players
		}
	}
	return nil
}

func (x *GameOutput) GetMove() *Move {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *GameOutput) GetChat() *Chat {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *GameOutput) GetForfeit() *Forfeit {
	if x != nil {
		if x, ok := x.Value.(*GameOutput_Forfeit); ok {
			return x.Forfeit
		}
	}
	return nil
}

type isGameOutput_Value interface {
	isGameOutput_Value()
}

type GameOutput_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type GameOutput_Init struct {
	Init *Init `protobuf:"bytes,3,opt,name=init,proto3,oneof"`
}

type GameOutput_Players struct {
	Players *Players `protobuf:"bytes,4,opt,name=players,proto3,oneof"`
}

type GameOutput_Move struct {
	Move *Move `protobuf:"bytes,5,opt,name=move,proto3,oneof"`
}

type GameOutput_Chat struct {
	Chat *Chat `protobuf:"bytes,6,opt,name=chat,proto3,oneof"`
}

type GameOutput_Forfeit struct {
	Forfeit *Forfeit `protobuf:"bytes,7,opt,name=forfeit,proto3,oneof"`
}

func (*GameOutput_Error) isGameOutput_Value() {}

func (*GameOutput_Init) isGameOutput_Value() {}

func (*GameOutput_Players) isGameOutput_Value() {}

func (*GameOutput_Move) isGameOutput_Value() {}

func (*GameOutput_Chat) isGameOutput_Value() {}

func (*GameOutput_Forfeit) isGameOutput_Value() {}

var File_pb_messages_proto protoreflect.FileDescriptor

const file_pb_messages_proto_rawDesc = "" +
	"\n" +
	"\x11pb/messages.proto\x12\bmessages\"w\n" +
	"\vPlayerState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x10\n" +
	"\x03elo\x18\x04 \x01(\x02R\x03elo\x12\x18\n" +
	"\aisGuest\x18\x05 \x01(\bR\aisGuest\"\x89\x01\n" +
	"\tPieceMove\x12\x14\n" +
	"\x05piece\x18\x01 \x01(\x05R\x05piece\x12\x1a\n" +
	"\bfromFile\x18\x02 \x01(\x05R\bfromFile\x12\x1a\n" +
	"\bfromRank\x18\x03 \x01(\x05R\bfromRank\x12\x16\n" +
	"\x06toFile\x18\x04 \x01(\x05R\x06toFile\x12\x16\n" +
	"\x06toRank\x18\x05 \x01(\x05R\x06toRank\"Z\n" +
	"\n" +
	"PieceMoves\x12\x1a\n" +
	"\bfromFile\x18\x01 \x01(\x05R\bfromFile\x12\x1a\n" +
	"\bfromRank\x18\x02 \x01(\x05R\bfromRank\x12\x14\n" +
	"\x05moves\x18\x03 \x03(\x03R\x05moves\"#\n" +
	"\tBoardFile\x12\x16\n" +
	"\x06pieces\x18\x01 \x03(\rR\x06pieces\"Y\n" +
	"\n" +
	"ChessBoard\x12\"\n" +
	"\ris_white_turn\x18\x01 \x01(\bR\visWhiteTurn\x12'\n" +
	"\x04file\x18\x02 \x03(\v2\x13.messages.BoardFileR\x04file\"\x81\x02\n" +
	"\tChessGame\x12*\n" +
	"\x05board\x18\x01 \x01(\v2\x14.messages.ChessBoardR\x05board\x125\n" +
	"\vwhite_moves\x18\x02 \x03(\v2\x14.messages.PieceMovesR\n" +
	"whiteMoves\x125\n" +
	"\vblack_moves\x18\x03 \x03(\v2\x14.messages.PieceMovesR\n" +
	"blackMoves\x12,\n" +
	"\x12taken_white_pieces\x18\x04 \x03(\x05R\x10takenWhitePieces\x12,\n" +
	"\x12taken_black_pieces\x18\x05 \x03(\x05R\x10takenBlackPieces\"\xe0\x02\n" +
	"\n" +
	"ChessState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04game\x18\x02 \x01(\v2\x13.messages.ChessGameR\x04game\x120\n" +
	"\tmove_list\x18\x03 \x03(\v2\x13.messages.PieceMoveR\bmoveList\x128\n" +
	"\fwhite_player\x18\x04 \x01(\v2\x15.messages.PlayerStateR\vwhitePlayer\x128\n" +
	"\fblack_player\x18\x05 \x01(\v2\x15.messages.PlayerStateR\vblackPlayer\x12\x19\n" +
	"\bis_ended\x18\x06 \x01(\bR\aisEnded\x12\x1f\n" +
	"\vfirst_color\x18\a \x01(\rR\n" +
	"firstColor\x12!\n" +
	"\ftime_control\x18\b \x01(\rR\vtimeControl\x12\x14\n" +
	"\x05touch\x18\t \x01(\x03R\x05touch\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"]\n" +
	"\x04Init\x12*\n" +
	"\x05state\x18\x01 \x01(\v2\x14.messages.ChessStateR\x05state\x12)\n" +
	"\x04self\x18\x02 \x01(\v2\x15.messages.PlayerStateR\x04self\"{\n" +
	"\aPlayers\x127\n" +
	"\vwhitePlayer\x18\x01 \x01(\v2\x15.messages.PlayerStateR\vwhitePlayer\x127\n" +
	"\vblackPlayer\x18\x02 \x01(\v2\x15.messages.PlayerStateR\vblackPlayer\"b\n" +
	"\x04Move\x121\n" +
	"\tpieceMove\x18\x01 \x01(\v2\x13.messages.PieceMoveR\tpieceMove\x12'\n" +
	"\x04game\x18\x02 \x01(\v2\x13.messages.ChessGameR\x04game\"O\n" +
	"\x04Chat\x12-\n" +
	"\x06player\x18\x02 \x01(\v2\x15.messages.PlayerStateR\x06player\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\t\n" +
	"\aForfeit\"'\n" +
	"\fGameOutputID\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"\xa7\x02\n" +
	"\n" +
	"GameOutput\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12'\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.messages.ErrorH\x00R\x05error\x12$\n" +
	"\x04init\x18\x03 \x01(\v2\x0e.messages.InitH\x00R\x04init\x12-\n" +
	"\aplayers\x18\x04 \x01(\v2\x11.messages.PlayersH\x00R\aplayers\x12$\n" +
	"\x04move\x18\x05 \x01(\v2\x0e.messages.MoveH\x00R\x04move\x12$\n" +
	"\x04chat\x18\x06 \x01(\v2\x0e.messages.ChatH\x00R\x04chat\x12-\n" +
	"\aforfeit\x18\a \x01(\v2\x11.messages.ForfeitH\x00R\aforfeitB\a\n" +
	"\x05valueB\x11Z\x0fhexchess-dal/pbb\x06proto3"

var (
	file_pb_messages_proto_rawDescOnce sync.Once
	file_pb_messages_proto_rawDescData []byte
)

func file_pb_messages_proto_rawDescGZIP() []byte {
	file_pb_messages_proto_rawDescOnce.Do(func() {
		file_pb_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_messages_proto_rawDesc), len(file_pb_messages_proto_rawDesc)))
	})
	return file_pb_messages_proto_rawDescData
}

var file_pb_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pb_messages_proto_goTypes = []any{
	(*PlayerState)(nil),  // 0: messages.PlayerState
	(*PieceMove)(nil),    // 1: messages.PieceMove
	(*PieceMoves)(nil),   // 2: messages.PieceMoves
	(*BoardFile)(nil),    // 3: messages.BoardFile
	(*ChessBoard)(nil),   // 4: messages.ChessBoard
	(*ChessGame)(nil),    // 5: messages.ChessGame
	(*ChessState)(nil),   // 6: messages.ChessState
	(*Error)(nil),        // 7: messages.Error
	(*Init)(nil),         // 8: messages.Init
	(*Players)(nil),      // 9: messages.Players
	(*Move)(nil),         // 10: messages.Move
	(*Chat)(nil),         // 11: messages.Chat
	(*Forfeit)(nil),      // 12: messages.Forfeit
	(*GameOutputID)(nil), // 13: messages.GameOutputID
	(*GameOutput)(nil),   // 14: messages.GameOutput
}
var file_pb_messages_proto_depIdxs = []int32{
	3,  // 0: messages.ChessBoard.file:type_name -> messages.BoardFile
	4,  // 1: messages.ChessGame.board:type_name -> messages.ChessBoard
	2,  // 2: messages.ChessGame.white_moves:type_name -> messages.PieceMoves
	2,  // 3: messages.ChessGame.black_moves:type_name -> messages.PieceMoves
	5,  // 4: messages.ChessState.game:type_name -> messages.ChessGame
	1,  // 5: messages.ChessState.move_list:type_name -> messages.PieceMove
	0,  // 6: messages.ChessState.white_player:type_name -> messages.PlayerState
	0,  // 7: messages.ChessState.black_player:type_name -> messages.PlayerState
	6,  // 8: messages.Init.state:type_name -> messages.ChessState
	0,  // 9: messages.Init.self:type_name -> messages.PlayerState
	0,  // 10: messages.Players.whitePlayer:type_name -> messages.PlayerState
	0,  // 11: messages.Players.blackPlayer:type_name -> messages.PlayerState
	1,  // 12: messages.Move.pieceMove:type_name -> messages.PieceMove
	5,  // 13: messages.Move.game:type_name -> messages.ChessGame
	0,  // 14: messages.Chat.player:type_name -> messages.PlayerState
	7,  // 15: messages.GameOutput.error:type_name -> messages.Error
	8,  // 16: messages.GameOutput.init:type_name -> messages.Init
	9,  // 17: messages.GameOutput.players:type_name -> messages.Players
	10, // 18: messages.GameOutput.move:type_name -> messages.Move
	11, // 19: messages.GameOutput.chat:type_name -> messages.Chat
	12, // 20: messages.GameOutput.forfeit:type_name -> messages.Forfeit
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_pb_messages_proto_init() }
func file_pb_messages_proto_init() {
	if File_pb_messages_proto != nil {
		return
	}
	file_pb_messages_proto_msgTypes[14].OneofWrappers = []any{
		(*GameOutput_Error)(nil),
		(*GameOutput_Init)(nil),
		(*GameOutput_Players)(nil),
		(*GameOutput_Move)(nil),
		(*GameOutput_Chat)(nil),
		(*GameOutput_Forfeit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_messages_proto_rawDesc), len(file_pb_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_messages_proto_goTypes,
		DependencyIndexes: file_pb_messages_proto_depIdxs,
		MessageInfos:      file_pb_messages_proto_msgTypes,
	}.Build()
	File_pb_messages_proto = out.File
	file_pb_messages_proto_goTypes = nil
	file_pb_messages_proto_depIdxs = nil
}
