// Contract for data and messages for information exchange within Hexchess

syntax = "proto3";
option go_package = "hexchess-svc/pb";

package messages;

// user data state

message PlayerState {
  int64 id = 1;
  string name = 2;
  string country = 3;
  double elo = 4;
  bool isGuest = 5;
}

message ChatMessages {
  repeated ChatMessage chats = 1;
}

// chess state

message PieceMove {
  uint32 piece = 1;
  uint32 fromFile = 2;
  uint32 fromRank = 3;
  uint32 toFile = 4;
  uint32 toRank = 5;
}

message Hex {
  uint32 file = 1;
  uint32 rank = 2;
}

message PieceMoves {
  uint32 piece = 1;
  uint32 fromFile = 2;
  uint32 fromRank = 3;
  repeated Hex moves = 4;
}

message BoardFile {
  repeated uint32 pieces = 1;
}

message ChessBoard {
  bool is_white_turn = 1;
  repeated BoardFile file = 2;
}

message HistMove {
  uint32 piece = 1;
  uint32 from_file = 2;
  uint32 from_rank = 3;
  uint32 to_file = 4;
  uint32 to_rank = 5;
  string notation = 6;
  int64 white_timer_ms = 7;
  int64 black_timer_ms = 8;
}

message ChessGame {
  ChessBoard board = 1;
  repeated PieceMoves white_moves = 2;
  repeated PieceMoves black_moves = 3;
  repeated uint32 taken_white_pieces = 4;
  repeated uint32 taken_black_pieces = 5;
  repeated HistMove moves = 6;
}

enum EndKind {
  NOT_ENDED = 0;
  FINISHED = 1;
  ABORTED = 2;
}

message ChessState {
  string id = 1;
  ChessGame game = 2;
  PlayerState white_player = 4;
  PlayerState black_player = 5;
  string first_color = 6;
  string mode = 7;
  int64 touch = 8;
  ChessBoard initial_board = 9;
  int64 undo_id = 10;
  EndKind end_state = 11;
  int64 start_time_ms = 12;
}

message HistMoves {
  repeated HistMove moves = 1;
}

message PieceMoveList {
  repeated PieceMove moves = 1;
}

message MoveHistory {
  ChessGame initial_game = 1;
  repeated HistMove steps = 2;
}

// game ws api

message Move {
  uint32 promotion = 1;
  uint32 fromFile = 2;
  uint32 fromRank = 3;
  uint32 toFile = 4;
  uint32 toRank = 5;
}

message ChatMessage {
  PlayerState player = 1;
  string message = 2;
  string sent_at = 3;
  string id = 4;
}

message ForfeitInput {}

message MoveInput {
  Move move = 1;
}

message ChatInput {
  string message = 1;
}

message UndoInput {
  string kind = 1;
}

message PingInput {}

message GameInput {
  string messageId = 1;
  oneof value {
    ForfeitInput forfeit = 2;
    MoveInput move = 3;
    ChatInput chat = 4;
    UndoInput undo = 5;
    PingInput ping = 6;
  }
}

message ErrorOutput {
  string message = 1;
}

message InitOutput {
  ChessState state = 1;
  PlayerState self = 2;
}

message PlayersOutput {
  PlayerState white_player = 1;
  PlayerState black_player = 2;
}

message MoveOutput {
  HistMove move = 1;
  ChessGame game = 2;
  string updated_at = 3;
}

message UndoOutput {
  string kind = 1;
  int64 undo_id = 2;
  ChessGame game = 3;
}

message ForfeitOutput {
  EndKind end_state = 1;
}

message ReplayOutput {
  int64 id = 1;
  int64 white_id = 2;
  int64 black_id = 3;
  string white_name = 4;
  string black_name = 5;
  string white_country = 6;
  string black_country = 7;
  string mode = 8;
  string result = 9;
  string cause = 10;
  double win_elo_diff = 11;
  double lose_elo_diff = 12;
  double white_elo = 13;
  double black_elo = 14;
  double white_elo_diff = 15;
  double black_elo_diff = 16;
  string played_on = 17;
}

message GameOutputID {
  string game_id = 1;
  string message_id = 2;
}

message GameOutput {
  string game_id = 1;
  string message_id = 2;
  oneof value {
    ErrorOutput error = 3;
    InitOutput init = 4;
    PlayersOutput players = 5;
    MoveOutput move = 6;
    ChatMessage chat = 7;
    UndoOutput undo = 8;
    ForfeitOutput forfeit = 9;
    ReplayOutput replay = 10;
  }
}