// Code generated by MockGen. DO NOT EDIT.
// Source: game.go
//
// Generated by this command:
//
//	mockgen -source game.go -destination game_mock.go -package data
//

// Package data is a generated GoMock package.
package data

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGameplayDAL is a mock of GameplayDAL interface.
type MockGameplayDAL struct {
	ctrl     *gomock.Controller
	recorder *MockGameplayDALMockRecorder
	isgomock struct{}
}

// MockGameplayDALMockRecorder is the mock recorder for MockGameplayDAL.
type MockGameplayDALMockRecorder struct {
	mock *MockGameplayDAL
}

// NewMockGameplayDAL creates a new mock instance.
func NewMockGameplayDAL(ctrl *gomock.Controller) *MockGameplayDAL {
	mock := &MockGameplayDAL{ctrl: ctrl}
	mock.recorder = &MockGameplayDALMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameplayDAL) EXPECT() *MockGameplayDALMockRecorder {
	return m.recorder
}

// GetChessState mocks base method.
func (m *MockGameplayDAL) GetChessState(ctx context.Context, id string) (ChessState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChessState", ctx, id)
	ret0, _ := ret[0].(ChessState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChessState indicates an expected call of GetChessState.
func (mr *MockGameplayDALMockRecorder) GetChessState(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChessState", reflect.TypeOf((*MockGameplayDAL)(nil).GetChessState), ctx, id)
}

// GetChessStateCount mocks base method.
func (m *MockGameplayDAL) GetChessStateCount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChessStateCount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChessStateCount indicates an expected call of GetChessStateCount.
func (mr *MockGameplayDALMockRecorder) GetChessStateCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChessStateCount", reflect.TypeOf((*MockGameplayDAL)(nil).GetChessStateCount), ctx)
}

// SetChessState mocks base method.
func (m *MockGameplayDAL) SetChessState(ctx context.Context, id string, state ChessState) (ChessState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetChessState", ctx, id, state)
	ret0, _ := ret[0].(ChessState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetChessState indicates an expected call of SetChessState.
func (mr *MockGameplayDALMockRecorder) SetChessState(ctx, id, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetChessState", reflect.TypeOf((*MockGameplayDAL)(nil).SetChessState), ctx, id, state)
}

// WriteFinishedGame mocks base method.
func (m *MockGameplayDAL) WriteFinishedGame(ctx context.Context, state ChessState, isWhiteWin bool, cause ReplayCause) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFinishedGame", ctx, state, isWhiteWin, cause)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFinishedGame indicates an expected call of WriteFinishedGame.
func (mr *MockGameplayDALMockRecorder) WriteFinishedGame(ctx, state, isWhiteWin, cause any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFinishedGame", reflect.TypeOf((*MockGameplayDAL)(nil).WriteFinishedGame), ctx, state, isWhiteWin, cause)
}
