// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchInsertUser = `-- name: BatchInsertUser :batchone
INSERT INTO users (username, country, elo, highest_elo, start_elo, wins, losses, password, salt, google_account_id)
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10)
RETURNING id, username, country, elo, highest_elo, wins, losses, bio, joined_on
`

type BatchInsertUserBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchInsertUserParams struct {
	Username        string
	Country         pgtype.Text
	Elo             float64
	HighestElo      float64
	StartElo        float64
	Wins            int32
	Losses          int32
	Password        string
	Salt            string
	GoogleAccountID pgtype.Text
}

type BatchInsertUserRow struct {
	ID         int64
	Username   string
	Country    pgtype.Text
	Elo        float64
	HighestElo float64
	Wins       int32
	Losses     int32
	Bio        string
	JoinedOn   pgtype.Timestamptz
}

func (q *Queries) BatchInsertUser(ctx context.Context, arg []BatchInsertUserParams) *BatchInsertUserBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Username,
			a.Country,
			a.Elo,
			a.HighestElo,
			a.StartElo,
			a.Wins,
			a.Losses,
			a.Password,
			a.Salt,
			a.GoogleAccountID,
		}
		batch.Queue(batchInsertUser, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchInsertUserBatchResults{br, len(arg), false}
}

func (b *BatchInsertUserBatchResults) QueryRow(f func(int, BatchInsertUserRow, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i BatchInsertUserRow
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.Username,
			&i.Country,
			&i.Elo,
			&i.HighestElo,
			&i.Wins,
			&i.Losses,
			&i.Bio,
			&i.JoinedOn,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *BatchInsertUserBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
