// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchInsertUser = `-- name: BatchInsertUser :batchone
INSERT INTO users (
       username,
       country,
       password,
       salt,
       joined_on)
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5)
RETURNING
    id,
    username,
    country,
    bio,
    joined_on
`

type BatchInsertUserBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchInsertUserParams struct {
	Username string
	Country  string
	Password string
	Salt     string
	JoinedOn pgtype.Timestamptz
}

type BatchInsertUserRow struct {
	ID       int64
	Username string
	Country  string
	Bio      string
	JoinedOn pgtype.Timestamptz
}

func (q *Queries) BatchInsertUser(ctx context.Context, arg []BatchInsertUserParams) *BatchInsertUserBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Username,
			a.Country,
			a.Password,
			a.Salt,
			a.JoinedOn,
		}
		batch.Queue(batchInsertUser, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchInsertUserBatchResults{br, len(arg), false}
}

func (b *BatchInsertUserBatchResults) QueryRow(f func(int, BatchInsertUserRow, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i BatchInsertUserRow
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.Username,
			&i.Country,
			&i.Bio,
			&i.JoinedOn,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *BatchInsertUserBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
