// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBatchInsertUser implements pgx.CopyFromSource.
type iteratorForBatchInsertUser struct {
	rows                 []BatchInsertUserParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertUser) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertUser) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Username,
		r.rows[0].Country,
		r.rows[0].Elo,
		r.rows[0].HighestElo,
		r.rows[0].Wins,
		r.rows[0].Losses,
		r.rows[0].Password,
		r.rows[0].Salt,
	}, nil
}

func (r iteratorForBatchInsertUser) Err() error {
	return nil
}

func (q *Queries) BatchInsertUser(ctx context.Context, arg []BatchInsertUserParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"users"}, []string{"username", "country", "elo", "highest_elo", "wins", "losses", "password", "salt"}, &iteratorForBatchInsertUser{rows: arg})
}
