// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Challenge struct {
	ChallengerID int64
	ChallengeeID int64
	TimeControl  string
	StartColor   string
	MadeOn       pgtype.Timestamptz
}

type Replay struct {
	ID       int64
	WhiteID  int64
	BlackID  int64
	Result   int32
	Cause    int32
	PlayedOn pgtype.Timestamptz
	WinElo   float64
	LoseElo  float64
	MoveList []byte
}

type User struct {
	ID               int64
	Username         string
	Country          pgtype.Text
	Elo              float64
	HighestElo       float64
	Wins             int32
	Losses           int32
	Bio              string
	JoinedOn         pgtype.Timestamptz
	Password         string
	Salt             string
	LoginAttempts    int32
	LastLoginAttempt pgtype.Timestamptz
}

type UsersMetadatum struct {
	ID    int64
	Count pgtype.Int4
}
