// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CauseEnum string

const (
	CauseEnumCHECKMATE CauseEnum = "CHECKMATE"
	CauseEnumFORFEIT   CauseEnum = "FORFEIT"
	CauseEnumSTALEMATE CauseEnum = "STALEMATE"
)

func (e *CauseEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CauseEnum(s)
	case string:
		*e = CauseEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for CauseEnum: %T", src)
	}
	return nil
}

type NullCauseEnum struct {
	CauseEnum CauseEnum
	Valid     bool // Valid is true if CauseEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCauseEnum) Scan(value interface{}) error {
	if value == nil {
		ns.CauseEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CauseEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCauseEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CauseEnum), nil
}

type ColorEnum string

const (
	ColorEnumWHITE  ColorEnum = "WHITE"
	ColorEnumBLACK  ColorEnum = "BLACK"
	ColorEnumRANDOM ColorEnum = "RANDOM"
)

func (e *ColorEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ColorEnum(s)
	case string:
		*e = ColorEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ColorEnum: %T", src)
	}
	return nil
}

type NullColorEnum struct {
	ColorEnum ColorEnum
	Valid     bool // Valid is true if ColorEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullColorEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ColorEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ColorEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullColorEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ColorEnum), nil
}

type ModeEnum string

const (
	ModeEnumTIMED10          ModeEnum = "TIMED_1+0"
	ModeEnumTIMED32          ModeEnum = "TIMED_3+2"
	ModeEnumTIMED1510        ModeEnum = "TIMED_15+10"
	ModeEnumCORRESPONDENCE1  ModeEnum = "CORRESPONDENCE_1"
	ModeEnumCORRESPONDENCE7  ModeEnum = "CORRESPONDENCE_7"
	ModeEnumCORRESPONDENCE14 ModeEnum = "CORRESPONDENCE_14"
	ModeEnumTIMED50          ModeEnum = "TIMED_5+0"
)

func (e *ModeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModeEnum(s)
	case string:
		*e = ModeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ModeEnum: %T", src)
	}
	return nil
}

type NullModeEnum struct {
	ModeEnum ModeEnum
	Valid    bool // Valid is true if ModeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ModeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModeEnum), nil
}

type ResultEnum string

const (
	ResultEnumWHITEWINS ResultEnum = "WHITE_WINS"
	ResultEnumBLACKWINS ResultEnum = "BLACK_WINS"
	ResultEnumDRAW      ResultEnum = "DRAW"
	ResultEnumRANDOM    ResultEnum = "RANDOM"
)

func (e *ResultEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResultEnum(s)
	case string:
		*e = ResultEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ResultEnum: %T", src)
	}
	return nil
}

type NullResultEnum struct {
	ResultEnum ResultEnum
	Valid      bool // Valid is true if ResultEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResultEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ResultEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResultEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResultEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResultEnum), nil
}

type Challenge struct {
	ChallengerID int64
	ChallengeeID int64
	StartColor   ColorEnum
	MadeOn       pgtype.Timestamptz
	Mode         ModeEnum
}

type Replay struct {
	ID          int64
	WhiteID     int64
	BlackID     int64
	Mode        ModeEnum
	Result      ResultEnum
	Cause       CauseEnum
	PlayedOn    pgtype.Timestamptz
	WinEloDiff  float64
	LoseEloDiff float64
	WhiteElo    float64
	BlackElo    float64
	MoveHistory []byte
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}

type User struct {
	ID               int64
	Username         string
	Country          string
	Bio              string
	JoinedOn         pgtype.Timestamptz
	Password         string
	Salt             string
	LoginAttempts    int32
	LastLoginAttempt pgtype.Timestamptz
	GoogleAccountID  pgtype.Text
}

type UserModeElo struct {
	UserID     int64
	Mode       ModeEnum
	Elo        float64
	HighestElo float64
	Wins       int32
	Losses     int32
}

type UsersMetadatum struct {
	ID    int64
	Count pgtype.Int4
}
