// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: replay.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getReplayByID = `-- name: GetReplayByID :one
SELECT
    r.id,
    r.white_id,
    r.black_id,
    r.result,
    r.cause,
    r.played_on,
    r.win_elo,
    r.lose_elo,
    u1.username AS white_name,
    u1.country AS white_country,
    u1.elo AS white_elo,
    u2.username AS black_name,
    u2.country AS black_country,
    u2.elo AS black_elo
FROM replays r
         INNER JOIN users u1 ON u1.id = r.white_id
         INNER JOIN users u2 ON u2.id = r.black_id
WHERE r.id = $1
`

type GetReplayByIDRow struct {
	ID           int64
	WhiteID      int64
	BlackID      int64
	Result       int32
	Cause        int32
	PlayedOn     pgtype.Timestamp
	WinElo       float64
	LoseElo      float64
	WhiteName    string
	WhiteCountry pgtype.Text
	WhiteElo     float64
	BlackName    string
	BlackCountry pgtype.Text
	BlackElo     float64
}

func (q *Queries) GetReplayByID(ctx context.Context, id int64) (GetReplayByIDRow, error) {
	row := q.db.QueryRow(ctx, getReplayByID, id)
	var i GetReplayByIDRow
	err := row.Scan(
		&i.ID,
		&i.WhiteID,
		&i.BlackID,
		&i.Result,
		&i.Cause,
		&i.PlayedOn,
		&i.WinElo,
		&i.LoseElo,
		&i.WhiteName,
		&i.WhiteCountry,
		&i.WhiteElo,
		&i.BlackName,
		&i.BlackCountry,
		&i.BlackElo,
	)
	return i, err
}

const getReplayMoveList = `-- name: GetReplayMoveList :one
SELECT move_list AS move_list_json
FROM replays
WHERE id = $1
`

func (q *Queries) GetReplayMoveList(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getReplayMoveList, id)
	var move_list_json []byte
	err := row.Scan(&move_list_json)
	return move_list_json, err
}

const getUserReplays = `-- name: GetUserReplays :many
SELECT
    r.id,
    r.white_id,
    r.black_id,
    r.result,
    r.cause,
    r.played_on,
    r.win_elo,
    r.lose_elo,
    u1.username AS white_name,
    u1.country AS white_country,
    u1.elo AS white_elo,
    u2.username AS black_name,
    u2.country AS black_country,
    u2.elo AS black_elo
FROM replays r
         INNER JOIN users u1 ON u1.id = r.white_id
         INNER JOIN users u2 ON u2.id = r.black_id
WHERE r.id < $1
  AND (r.white_id = $2 OR r.black_id = $2)
ORDER BY r.id DESC
    LIMIT $3
`

type GetUserReplaysParams struct {
	AfterID pgtype.Int8
	UserID  int64
	PerPage int32
}

type GetUserReplaysRow struct {
	ID           int64
	WhiteID      int64
	BlackID      int64
	Result       int32
	Cause        int32
	PlayedOn     pgtype.Timestamp
	WinElo       float64
	LoseElo      float64
	WhiteName    string
	WhiteCountry pgtype.Text
	WhiteElo     float64
	BlackName    string
	BlackCountry pgtype.Text
	BlackElo     float64
}

func (q *Queries) GetUserReplays(ctx context.Context, arg GetUserReplaysParams) ([]GetUserReplaysRow, error) {
	rows, err := q.db.Query(ctx, getUserReplays, arg.AfterID, arg.UserID, arg.PerPage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserReplaysRow
	for rows.Next() {
		var i GetUserReplaysRow
		if err := rows.Scan(
			&i.ID,
			&i.WhiteID,
			&i.BlackID,
			&i.Result,
			&i.Cause,
			&i.PlayedOn,
			&i.WinElo,
			&i.LoseElo,
			&i.WhiteName,
			&i.WhiteCountry,
			&i.WhiteElo,
			&i.BlackName,
			&i.BlackCountry,
			&i.BlackElo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertReplay = `-- name: InsertReplay :one
INSERT INTO replays (white_id, black_id, result, cause, win_elo, lose_elo, move_list)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertReplayParams struct {
	WhiteID  int64
	BlackID  int64
	Result   int32
	Cause    int32
	WinElo   float64
	LoseElo  float64
	MoveList []byte
}

func (q *Queries) InsertReplay(ctx context.Context, arg InsertReplayParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertReplay,
		arg.WhiteID,
		arg.BlackID,
		arg.Result,
		arg.Cause,
		arg.WinElo,
		arg.LoseElo,
		arg.MoveList,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
