// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEloList = `-- name: GetEloList :many
SELECT id, elo FROM users WHERE id > $1 ORDER BY id LIMIT $2
`

type GetEloListParams struct {
	ID    int64
	Limit int32
}

type GetEloListRow struct {
	ID  int64
	Elo float64
}

func (q *Queries) GetEloList(ctx context.Context, arg GetEloListParams) ([]GetEloListRow, error) {
	rows, err := q.db.Query(ctx, getEloList, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEloListRow
	for rows.Next() {
		var i GetEloListRow
		if err := rows.Scan(&i.ID, &i.Elo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getElosByIds = `-- name: GetElosByIds :many
SELECT id, elo
FROM users
WHERE id = ANY($1::bigint[])
`

type GetElosByIdsRow struct {
	ID  int64
	Elo float64
}

func (q *Queries) GetElosByIds(ctx context.Context, id []int64) ([]GetElosByIdsRow, error) {
	rows, err := q.db.Query(ctx, getElosByIds, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetElosByIdsRow
	for rows.Next() {
		var i GetElosByIdsRow
		if err := rows.Scan(&i.ID, &i.Elo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrLoginAttempts = `-- name: IncrLoginAttempts :exec
UPDATE users
SET last_login_attempt = CURRENT_TIMESTAMP,
    login_attempts = login_attempts + 1
WHERE id = $1
`

func (q *Queries) IncrLoginAttempts(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrLoginAttempts, id)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (username, country, elo, highest_elo, start_elo, wins, losses, password, salt, google_account_id)
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10)
RETURNING id, username, country, elo, highest_elo, wins, losses, bio, joined_on
`

type InsertUserParams struct {
	Username        string
	Country         pgtype.Text
	Elo             float64
	HighestElo      float64
	StartElo        float64
	Wins            int32
	Losses          int32
	Password        string
	Salt            string
	GoogleAccountID pgtype.Text
}

type InsertUserRow struct {
	ID         int64
	Username   string
	Country    pgtype.Text
	Elo        float64
	HighestElo float64
	Wins       int32
	Losses     int32
	Bio        string
	JoinedOn   pgtype.Timestamptz
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Username,
		arg.Country,
		arg.Elo,
		arg.HighestElo,
		arg.StartElo,
		arg.Wins,
		arg.Losses,
		arg.Password,
		arg.Salt,
		arg.GoogleAccountID,
	)
	var i InsertUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Country,
		&i.Elo,
		&i.HighestElo,
		&i.Wins,
		&i.Losses,
		&i.Bio,
		&i.JoinedOn,
	)
	return i, err
}

const resetLoginAttempts = `-- name: ResetLoginAttempts :exec
UPDATE users
SET last_login_attempt = CURRENT_TIMESTAMP,
    login_attempts = 0
WHERE id = $1
`

func (q *Queries) ResetLoginAttempts(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, resetLoginAttempts, id)
	return err
}

const selectAllUsers = `-- name: SelectAllUsers :many
SELECT
    id,
    username,
    country,
    elo,
    wins,
    losses
FROM users
`

type SelectAllUsersRow struct {
	ID       int64
	Username string
	Country  pgtype.Text
	Elo      float64
	Wins     int32
	Losses   int32
}

func (q *Queries) SelectAllUsers(ctx context.Context) ([]SelectAllUsersRow, error) {
	rows, err := q.db.Query(ctx, selectAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectAllUsersRow
	for rows.Next() {
		var i SelectAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Country,
			&i.Elo,
			&i.Wins,
			&i.Losses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectByGoogleAccountID = `-- name: SelectByGoogleAccountID :one
SELECT id, username, country, elo
FROM users
WHERE google_account_id = $1
`

type SelectByGoogleAccountIDRow struct {
	ID       int64
	Username string
	Country  pgtype.Text
	Elo      float64
}

func (q *Queries) SelectByGoogleAccountID(ctx context.Context, googleaccountid pgtype.Text) (SelectByGoogleAccountIDRow, error) {
	row := q.db.QueryRow(ctx, selectByGoogleAccountID, googleaccountid)
	var i SelectByGoogleAccountIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Country,
		&i.Elo,
	)
	return i, err
}

const selectEloListAfterID = `-- name: SelectEloListAfterID :many
SELECT
    id,
    elo
FROM users
WHERE id > $1
ORDER BY id
    LIMIT $2
`

type SelectEloListAfterIDParams struct {
	AfterID int64
	Limit   int32
}

type SelectEloListAfterIDRow struct {
	ID  int64
	Elo float64
}

func (q *Queries) SelectEloListAfterID(ctx context.Context, arg SelectEloListAfterIDParams) ([]SelectEloListAfterIDRow, error) {
	rows, err := q.db.Query(ctx, selectEloListAfterID, arg.AfterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectEloListAfterIDRow
	for rows.Next() {
		var i SelectEloListAfterIDRow
		if err := rows.Scan(&i.ID, &i.Elo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectLoginByName = `-- name: SelectLoginByName :one
SELECT id, username, country, elo, password, salt, login_attempts, last_login_attempt
FROM users
WHERE UPPER(username) = UPPER($1::TEXT)
`

type SelectLoginByNameRow struct {
	ID               int64
	Username         string
	Country          pgtype.Text
	Elo              float64
	Password         string
	Salt             string
	LoginAttempts    int32
	LastLoginAttempt pgtype.Timestamptz
}

func (q *Queries) SelectLoginByName(ctx context.Context, username string) (SelectLoginByNameRow, error) {
	row := q.db.QueryRow(ctx, selectLoginByName, username)
	var i SelectLoginByNameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Country,
		&i.Elo,
		&i.Password,
		&i.Salt,
		&i.LoginAttempts,
		&i.LastLoginAttempt,
	)
	return i, err
}

const selectUserByID = `-- name: SelectUserByID :one
SELECT
    id,
    username,
    country,
    elo,
    highest_elo,
    wins,
    losses,
    bio,
    joined_on
FROM users
WHERE id = $1
`

type SelectUserByIDRow struct {
	ID         int64
	Username   string
	Country    pgtype.Text
	Elo        float64
	HighestElo float64
	Wins       int32
	Losses     int32
	Bio        string
	JoinedOn   pgtype.Timestamptz
}

func (q *Queries) SelectUserByID(ctx context.Context, id int64) (SelectUserByIDRow, error) {
	row := q.db.QueryRow(ctx, selectUserByID, id)
	var i SelectUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Country,
		&i.Elo,
		&i.HighestElo,
		&i.Wins,
		&i.Losses,
		&i.Bio,
		&i.JoinedOn,
	)
	return i, err
}

const selectUserStartElo = `-- name: SelectUserStartElo :one
SELECT start_elo, joined_on
FROM users
WHERE id = $1
`

type SelectUserStartEloRow struct {
	StartElo float64
	JoinedOn pgtype.Timestamptz
}

func (q *Queries) SelectUserStartElo(ctx context.Context, id int64) (SelectUserStartEloRow, error) {
	row := q.db.QueryRow(ctx, selectUserStartElo, id)
	var i SelectUserStartEloRow
	err := row.Scan(&i.StartElo, &i.JoinedOn)
	return i, err
}

const selectUsersByIDs = `-- name: SelectUsersByIDs :many
SELECT
    id,
    username,
    country,
    elo,
    highest_elo,
    wins,
    losses,
    bio,
    joined_on
FROM users
WHERE id = ANY($1::bigint[])
`

type SelectUsersByIDsRow struct {
	ID         int64
	Username   string
	Country    pgtype.Text
	Elo        float64
	HighestElo float64
	Wins       int32
	Losses     int32
	Bio        string
	JoinedOn   pgtype.Timestamptz
}

func (q *Queries) SelectUsersByIDs(ctx context.Context, ids []int64) ([]SelectUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, selectUsersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectUsersByIDsRow
	for rows.Next() {
		var i SelectUsersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Country,
			&i.Elo,
			&i.HighestElo,
			&i.Wins,
			&i.Losses,
			&i.Bio,
			&i.JoinedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUsersBySimilarity = `-- name: SelectUsersBySimilarity :many
SELECT
    id,
    username,
    country,
    elo,
    wins,
    losses,
    (username <-> $1)::BIGINT AS rank
FROM users
WHERE username % $1::TEXT
ORDER BY rank DESC
    LIMIT $3
OFFSET $2
`

type SelectUsersBySimilarityParams struct {
	Username string
	Offset   int32
	Limit    int32
}

type SelectUsersBySimilarityRow struct {
	ID       int64
	Username string
	Country  pgtype.Text
	Elo      float64
	Wins     int32
	Losses   int32
	Rank     int64
}

func (q *Queries) SelectUsersBySimilarity(ctx context.Context, arg SelectUsersBySimilarityParams) ([]SelectUsersBySimilarityRow, error) {
	rows, err := q.db.Query(ctx, selectUsersBySimilarity, arg.Username, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectUsersBySimilarityRow
	for rows.Next() {
		var i SelectUsersBySimilarityRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Country,
			&i.Elo,
			&i.Wins,
			&i.Losses,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateElo = `-- name: UpdateElo :exec
UPDATE users
SET
    elo = $1,
    highest_elo = GREATEST(highest_elo, $1),
    wins = wins + CASE WHEN $2::boolean THEN 1 ELSE 0 END,
    losses = losses + CASE WHEN NOT $2::boolean THEN 1 ELSE 0 END
WHERE id = $3
`

type UpdateEloParams struct {
	Elo float64
	Won bool
	ID  int64
}

func (q *Queries) UpdateElo(ctx context.Context, arg UpdateEloParams) error {
	_, err := q.db.Exec(ctx, updateElo, arg.Elo, arg.Won, arg.ID)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password = $1, salt = $2
WHERE id = $3
`

type UpdatePasswordParams struct {
	Password string
	Salt     string
	ID       int64
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.Password, arg.Salt, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    username = COALESCE($1, username),
    country = COALESCE($2, country),
    bio = COALESCE($3, bio)
WHERE id = $4
RETURNING
    id,
    username,
    country,
    elo,
    highest_elo,
    wins,
    losses,
    bio,
    joined_on
`

type UpdateUserParams struct {
	Username pgtype.Text
	Country  pgtype.Text
	Bio      pgtype.Text
	ID       int64
}

type UpdateUserRow struct {
	ID         int64
	Username   string
	Country    pgtype.Text
	Elo        float64
	HighestElo float64
	Wins       int32
	Losses     int32
	Bio        string
	JoinedOn   pgtype.Timestamptz
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Country,
		arg.Bio,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Country,
		&i.Elo,
		&i.HighestElo,
		&i.Wins,
		&i.Losses,
		&i.Bio,
		&i.JoinedOn,
	)
	return i, err
}
