// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BatchInsertUserParams struct {
	Username   string
	Country    pgtype.Text
	Elo        float64
	HighestElo float64
	Wins       int32
	Losses     int32
	Password   string
	Salt       string
}

const getElo = `-- name: GetElo :one
SELECT elo
FROM users
WHERE id = $1
`

func (q *Queries) GetElo(ctx context.Context, id int64) (float64, error) {
	row := q.db.QueryRow(ctx, getElo, id)
	var elo float64
	err := row.Scan(&elo)
	return elo, err
}

const getEloList = `-- name: GetEloList :many
SELECT id, elo FROM users WHERE id > $1 ORDER BY id LIMIT $2
`

type GetEloListParams struct {
	ID    int64
	Limit int32
}

type GetEloListRow struct {
	ID  int64
	Elo float64
}

func (q *Queries) GetEloList(ctx context.Context, arg GetEloListParams) ([]GetEloListRow, error) {
	rows, err := q.db.Query(ctx, getEloList, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEloListRow
	for rows.Next() {
		var i GetEloListRow
		if err := rows.Scan(&i.ID, &i.Elo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (username, country, elo, highest_elo, wins, losses, password, salt)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, username, country, elo, highest_elo, wins, losses, bio
`

type InsertUserParams struct {
	Username   string
	Country    pgtype.Text
	Elo        float64
	HighestElo float64
	Wins       int32
	Losses     int32
	Password   string
	Salt       string
}

type InsertUserRow struct {
	ID         int64
	Username   string
	Country    pgtype.Text
	Elo        float64
	HighestElo float64
	Wins       int32
	Losses     int32
	Bio        string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Username,
		arg.Country,
		arg.Elo,
		arg.HighestElo,
		arg.Wins,
		arg.Losses,
		arg.Password,
		arg.Salt,
	)
	var i InsertUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Country,
		&i.Elo,
		&i.HighestElo,
		&i.Wins,
		&i.Losses,
		&i.Bio,
	)
	return i, err
}

const selectAllUsers = `-- name: SelectAllUsers :many
SELECT
    id,
    username,
    country,
    elo,
    wins,
    losses
FROM users
`

type SelectAllUsersRow struct {
	ID       int64
	Username string
	Country  pgtype.Text
	Elo      float64
	Wins     int32
	Losses   int32
}

func (q *Queries) SelectAllUsers(ctx context.Context) ([]SelectAllUsersRow, error) {
	rows, err := q.db.Query(ctx, selectAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectAllUsersRow
	for rows.Next() {
		var i SelectAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Country,
			&i.Elo,
			&i.Wins,
			&i.Losses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectLoginByName = `-- name: SelectLoginByName :one
SELECT id, username, country, elo, password, salt
FROM users
WHERE UPPER(username) = UPPER($1::TEXT)
`

type SelectLoginByNameRow struct {
	ID       int64
	Username string
	Country  pgtype.Text
	Elo      float64
	Password string
	Salt     string
}

func (q *Queries) SelectLoginByName(ctx context.Context, username string) (SelectLoginByNameRow, error) {
	row := q.db.QueryRow(ctx, selectLoginByName, username)
	var i SelectLoginByNameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Country,
		&i.Elo,
		&i.Password,
		&i.Salt,
	)
	return i, err
}

const selectUserByID = `-- name: SelectUserByID :one
SELECT
    id,
    username,
    country,
    elo,
    highest_elo,
    wins,
    losses,
    bio,
    joined_on
FROM users
WHERE id = $1
`

type SelectUserByIDRow struct {
	ID         int64
	Username   string
	Country    pgtype.Text
	Elo        float64
	HighestElo float64
	Wins       int32
	Losses     int32
	Bio        string
	JoinedOn   pgtype.Timestamp
}

func (q *Queries) SelectUserByID(ctx context.Context, id int64) (SelectUserByIDRow, error) {
	row := q.db.QueryRow(ctx, selectUserByID, id)
	var i SelectUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Country,
		&i.Elo,
		&i.HighestElo,
		&i.Wins,
		&i.Losses,
		&i.Bio,
		&i.JoinedOn,
	)
	return i, err
}

const selectUsersAfterID = `-- name: SelectUsersAfterID :many
SELECT
    id,
    elo
FROM users
WHERE id > $1
ORDER BY id
    LIMIT $2
`

type SelectUsersAfterIDParams struct {
	AfterId int64
	Limit   int32
}

type SelectUsersAfterIDRow struct {
	ID  int64
	Elo float64
}

func (q *Queries) SelectUsersAfterID(ctx context.Context, arg SelectUsersAfterIDParams) ([]SelectUsersAfterIDRow, error) {
	rows, err := q.db.Query(ctx, selectUsersAfterID, arg.AfterId, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectUsersAfterIDRow
	for rows.Next() {
		var i SelectUsersAfterIDRow
		if err := rows.Scan(&i.ID, &i.Elo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUsersByIDs = `-- name: SelectUsersByIDs :many
SELECT
    id,
    username,
    country,
    elo,
    highest_elo,
    wins,
    losses,
    bio,
    joined_on
FROM users
WHERE id = ANY($1::bigint[])
`

type SelectUsersByIDsRow struct {
	ID         int64
	Username   string
	Country    pgtype.Text
	Elo        float64
	HighestElo float64
	Wins       int32
	Losses     int32
	Bio        string
	JoinedOn   pgtype.Timestamp
}

func (q *Queries) SelectUsersByIDs(ctx context.Context, ids []int64) ([]SelectUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, selectUsersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectUsersByIDsRow
	for rows.Next() {
		var i SelectUsersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Country,
			&i.Elo,
			&i.HighestElo,
			&i.Wins,
			&i.Losses,
			&i.Bio,
			&i.JoinedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUsersBySimilarity = `-- name: SelectUsersBySimilarity :many
SELECT
    id,
    username,
    country,
    elo,
    wins,
    losses,
    (username <-> $1)::BIGINT AS rank
FROM users
WHERE username % $1::TEXT
ORDER BY rank DESC
    LIMIT $3
OFFSET $2
`

type SelectUsersBySimilarityParams struct {
	Username string
	Offset   int32
	Limit    int32
}

type SelectUsersBySimilarityRow struct {
	ID       int64
	Username string
	Country  pgtype.Text
	Elo      float64
	Wins     int32
	Losses   int32
	Rank     int64
}

func (q *Queries) SelectUsersBySimilarity(ctx context.Context, arg SelectUsersBySimilarityParams) ([]SelectUsersBySimilarityRow, error) {
	rows, err := q.db.Query(ctx, selectUsersBySimilarity, arg.Username, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectUsersBySimilarityRow
	for rows.Next() {
		var i SelectUsersBySimilarityRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Country,
			&i.Elo,
			&i.Wins,
			&i.Losses,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLosses = `-- name: UpdateLosses :exec
UPDATE users
SET elo = $1,
    losses = losses + 1
WHERE id = $2
`

type UpdateLossesParams struct {
	Elo float64
	ID  int64
}

func (q *Queries) UpdateLosses(ctx context.Context, arg UpdateLossesParams) error {
	_, err := q.db.Exec(ctx, updateLosses, arg.Elo, arg.ID)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password = $1, salt = $2
WHERE id = $3
`

type UpdatePasswordParams struct {
	Password string
	Salt     string
	ID       int64
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.Password, arg.Salt, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    username = COALESCE($1, username),
    country = COALESCE($2, country),
    bio = COALESCE($3, bio)
WHERE id = $4
    RETURNING id, username, country, elo, highest_elo, wins, losses, bio, joined_on, password, salt
`

type UpdateUserParams struct {
	Username pgtype.Text
	Country  pgtype.Text
	Bio      pgtype.Text
	ID       int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Country,
		arg.Bio,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Country,
		&i.Elo,
		&i.HighestElo,
		&i.Wins,
		&i.Losses,
		&i.Bio,
		&i.JoinedOn,
		&i.Password,
		&i.Salt,
	)
	return i, err
}

const updateWins = `-- name: UpdateWins :exec
UPDATE users
SET elo = $1,
    wins = wins + 1,
    highest_elo = GREATEST(highest_elo, $1)
WHERE id = $2
`

type UpdateWinsParams struct {
	Elo float64
	ID  int64
}

func (q *Queries) UpdateWins(ctx context.Context, arg UpdateWinsParams) error {
	_, err := q.db.Exec(ctx, updateWins, arg.Elo, arg.ID)
	return err
}
