// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const incrLoginAttempts = `-- name: IncrLoginAttempts :exec
UPDATE users
SET last_login_attempt = CURRENT_TIMESTAMP,
    login_attempts = login_attempts + 1
WHERE id = $1
`

func (q *Queries) IncrLoginAttempts(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrLoginAttempts, id)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (
       username,
       country,
       password,
       salt,
       google_account_id,
       joined_on)
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        COALESCE($6::TIMESTAMPTZ, CURRENT_TIMESTAMP))
RETURNING
    id,
    username,
    country,
    bio,
    joined_on
`

type InsertUserParams struct {
	Username        string
	Country         string
	Password        string
	Salt            string
	GoogleAccountID pgtype.Text
	JoinedOn        pgtype.Timestamptz
}

type InsertUserRow struct {
	ID       int64
	Username string
	Country  string
	Bio      string
	JoinedOn pgtype.Timestamptz
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Username,
		arg.Country,
		arg.Password,
		arg.Salt,
		arg.GoogleAccountID,
		arg.JoinedOn,
	)
	var i InsertUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Country,
		&i.Bio,
		&i.JoinedOn,
	)
	return i, err
}

const resetLoginAttempts = `-- name: ResetLoginAttempts :exec
UPDATE users
SET last_login_attempt = CURRENT_TIMESTAMP,
    login_attempts = 0
WHERE id = $1
`

func (q *Queries) ResetLoginAttempts(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, resetLoginAttempts, id)
	return err
}

const selectByGoogleAccountID = `-- name: SelectByGoogleAccountID :one
SELECT id, username, country
FROM users
WHERE google_account_id = $1
`

type SelectByGoogleAccountIDRow struct {
	ID       int64
	Username string
	Country  string
}

func (q *Queries) SelectByGoogleAccountID(ctx context.Context, googleaccountid pgtype.Text) (SelectByGoogleAccountIDRow, error) {
	row := q.db.QueryRow(ctx, selectByGoogleAccountID, googleaccountid)
	var i SelectByGoogleAccountIDRow
	err := row.Scan(&i.ID, &i.Username, &i.Country)
	return i, err
}

const selectEloList = `-- name: SelectEloList :many
SELECT user_id, elo FROM user_mode_elos
WHERE user_id > $1 AND mode = $2
ORDER BY user_id
LIMIT $3
`

type SelectEloListParams struct {
	ID    int64
	Mode  ModeEnum
	Limit int32
}

type SelectEloListRow struct {
	UserID int64
	Elo    float64
}

func (q *Queries) SelectEloList(ctx context.Context, arg SelectEloListParams) ([]SelectEloListRow, error) {
	rows, err := q.db.Query(ctx, selectEloList, arg.ID, arg.Mode, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectEloListRow
	for rows.Next() {
		var i SelectEloListRow
		if err := rows.Scan(&i.UserID, &i.Elo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectLoginByName = `-- name: SelectLoginByName :one
SELECT id, username, country, password, salt, login_attempts, last_login_attempt
FROM users
WHERE UPPER(username) = UPPER($1::TEXT)
`

type SelectLoginByNameRow struct {
	ID               int64
	Username         string
	Country          string
	Password         string
	Salt             string
	LoginAttempts    int32
	LastLoginAttempt pgtype.Timestamptz
}

func (q *Queries) SelectLoginByName(ctx context.Context, username string) (SelectLoginByNameRow, error) {
	row := q.db.QueryRow(ctx, selectLoginByName, username)
	var i SelectLoginByNameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Country,
		&i.Password,
		&i.Salt,
		&i.LoginAttempts,
		&i.LastLoginAttempt,
	)
	return i, err
}

const selectUserByID = `-- name: SelectUserByID :one
SELECT
    id,
    username,
    country,
    bio,
    joined_on
FROM users
WHERE id = $1
`

type SelectUserByIDRow struct {
	ID       int64
	Username string
	Country  string
	Bio      string
	JoinedOn pgtype.Timestamptz
}

func (q *Queries) SelectUserByID(ctx context.Context, id int64) (SelectUserByIDRow, error) {
	row := q.db.QueryRow(ctx, selectUserByID, id)
	var i SelectUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Country,
		&i.Bio,
		&i.JoinedOn,
	)
	return i, err
}

const selectUserElosById = `-- name: SelectUserElosById :many
SELECT user_id, mode, elo, highest_elo, wins, losses
FROM user_mode_elos
WHERE user_id = $1
`

func (q *Queries) SelectUserElosById(ctx context.Context, id int64) ([]UserModeElo, error) {
	rows, err := q.db.Query(ctx, selectUserElosById, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserModeElo
	for rows.Next() {
		var i UserModeElo
		if err := rows.Scan(
			&i.UserID,
			&i.Mode,
			&i.Elo,
			&i.HighestElo,
			&i.Wins,
			&i.Losses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserModeElosByIds = `-- name: SelectUserModeElosByIds :many
SELECT user_id, elo
FROM user_mode_elos
WHERE user_id = ANY($1::bigint[]) AND mode = $2
`

type SelectUserModeElosByIdsParams struct {
	ID   []int64
	Mode ModeEnum
}

type SelectUserModeElosByIdsRow struct {
	UserID int64
	Elo    float64
}

func (q *Queries) SelectUserModeElosByIds(ctx context.Context, arg SelectUserModeElosByIdsParams) ([]SelectUserModeElosByIdsRow, error) {
	rows, err := q.db.Query(ctx, selectUserModeElosByIds, arg.ID, arg.Mode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectUserModeElosByIdsRow
	for rows.Next() {
		var i SelectUserModeElosByIdsRow
		if err := rows.Scan(&i.UserID, &i.Elo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserWithEloByIDs = `-- name: SelectUserWithEloByIDs :many
SELECT
    u.id,
    u.username,
    u.country,
    u.bio,
    u.joined_on,
    e.elo,
    e.highest_elo,
    e.wins,
    e.losses
FROM users u
INNER JOIN user_mode_elos e
    ON u.id = e.user_id AND e.mode = $1
WHERE id = ANY($2::bigint[])
`

type SelectUserWithEloByIDsParams struct {
	Mode ModeEnum
	Ids  []int64
}

type SelectUserWithEloByIDsRow struct {
	ID         int64
	Username   string
	Country    string
	Bio        string
	JoinedOn   pgtype.Timestamptz
	Elo        float64
	HighestElo float64
	Wins       int32
	Losses     int32
}

func (q *Queries) SelectUserWithEloByIDs(ctx context.Context, arg SelectUserWithEloByIDsParams) ([]SelectUserWithEloByIDsRow, error) {
	rows, err := q.db.Query(ctx, selectUserWithEloByIDs, arg.Mode, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectUserWithEloByIDsRow
	for rows.Next() {
		var i SelectUserWithEloByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Country,
			&i.Bio,
			&i.JoinedOn,
			&i.Elo,
			&i.HighestElo,
			&i.Wins,
			&i.Losses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUsersBySimilarity = `-- name: SelectUsersBySimilarity :many
SELECT
    id,
    username,
    country,
    (username <-> $1)::BIGINT AS rank
FROM users
WHERE username % $1::TEXT
ORDER BY rank DESC
    LIMIT $3
OFFSET $2
`

type SelectUsersBySimilarityParams struct {
	Username string
	Offset   int32
	Limit    int32
}

type SelectUsersBySimilarityRow struct {
	ID       int64
	Username string
	Country  string
	Rank     int64
}

func (q *Queries) SelectUsersBySimilarity(ctx context.Context, arg SelectUsersBySimilarityParams) ([]SelectUsersBySimilarityRow, error) {
	rows, err := q.db.Query(ctx, selectUsersBySimilarity, arg.Username, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectUsersBySimilarityRow
	for rows.Next() {
		var i SelectUsersBySimilarityRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Country,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password = $1, salt = $2
WHERE id = $3
`

type UpdatePasswordParams struct {
	Password string
	Salt     string
	ID       int64
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.Password, arg.Salt, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    username = COALESCE($1, username),
    country = COALESCE($2, country),
    bio = COALESCE($3, bio)
WHERE id = $4
RETURNING
    id,
    username,
    country,
    bio,
    joined_on
`

type UpdateUserParams struct {
	Username pgtype.Text
	Country  pgtype.Text
	Bio      pgtype.Text
	ID       int64
}

type UpdateUserRow struct {
	ID       int64
	Username string
	Country  string
	Bio      string
	JoinedOn pgtype.Timestamptz
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Country,
		arg.Bio,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Country,
		&i.Bio,
		&i.JoinedOn,
	)
	return i, err
}

const upsertElo = `-- name: UpsertElo :exec
INSERT INTO user_mode_elos AS u (user_id, mode, elo, highest_elo, wins, losses)
VALUES (
    $1,
    $2,
    $3,
    $3,
    $4,
    $5)
ON CONFLICT ON CONSTRAINT user_mode_elos_pkey
DO UPDATE
SET
    elo = $3,
    highest_elo = GREATEST(u.highest_elo, $3),
    wins = u.wins + $4,
    losses = u.losses + $5
`

type UpsertEloParams struct {
	UserID int64
	Mode   ModeEnum
	Elo    float64
	Wins   int32
	Losses int32
}

func (q *Queries) UpsertElo(ctx context.Context, arg UpsertEloParams) error {
	_, err := q.db.Exec(ctx, upsertElo,
		arg.UserID,
		arg.Mode,
		arg.Elo,
		arg.Wins,
		arg.Losses,
	)
	return err
}
